/** Generated by pnpm generate:contracts; edit the canonical operation registry. */
export const runtimeOperations: readonly { method: string; path: string; status: number; demo: boolean; milestone: string }[] = [
  {
    "method": "get",
    "path": "/session",
    "status": 200,
    "demo": false,
    "milestone": "M0"
  },
  {
    "method": "get",
    "path": "/organization",
    "status": 200,
    "demo": false,
    "milestone": "M0"
  },
  {
    "method": "get",
    "path": "/navigation",
    "status": 200,
    "demo": false,
    "milestone": "M0"
  },
  {
    "method": "get",
    "path": "/dashboard",
    "status": 200,
    "demo": false,
    "milestone": "M0"
  },
  {
    "method": "get",
    "path": "/applications",
    "status": 200,
    "demo": false,
    "milestone": "M0"
  },
  {
    "method": "get",
    "path": "/cis",
    "status": 200,
    "demo": false,
    "milestone": "M0"
  },
  {
    "method": "get",
    "path": "/cis/{id}",
    "status": 200,
    "demo": false,
    "milestone": "M0"
  },
  {
    "method": "get",
    "path": "/search",
    "status": 200,
    "demo": false,
    "milestone": "M1"
  },
  {
    "method": "get",
    "path": "/applications/{id}",
    "status": 200,
    "demo": false,
    "milestone": "M1"
  },
  {
    "method": "get",
    "path": "/environments/{id}",
    "status": 200,
    "demo": false,
    "milestone": "M1"
  },
  {
    "method": "get",
    "path": "/relations",
    "status": 200,
    "demo": false,
    "milestone": "M1"
  },
  {
    "method": "get",
    "path": "/topology",
    "status": 200,
    "demo": false,
    "milestone": "M1"
  },
  {
    "method": "get",
    "path": "/pools",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "get",
    "path": "/capacity",
    "status": 200,
    "demo": false,
    "milestone": "M1"
  },
  {
    "method": "get",
    "path": "/catalog",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "get",
    "path": "/catalog/{id}",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "get",
    "path": "/requests",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "get",
    "path": "/requests/{id}",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "get",
    "path": "/jobs",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "get",
    "path": "/jobs/{id}",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "get",
    "path": "/pipelines",
    "status": 200,
    "demo": false,
    "milestone": "M3"
  },
  {
    "method": "get",
    "path": "/pipelines/{id}",
    "status": 200,
    "demo": false,
    "milestone": "M3"
  },
  {
    "method": "get",
    "path": "/releases",
    "status": 200,
    "demo": false,
    "milestone": "M3"
  },
  {
    "method": "get",
    "path": "/releases/{id}",
    "status": 200,
    "demo": false,
    "milestone": "M3"
  },
  {
    "method": "get",
    "path": "/observability/metrics",
    "status": 200,
    "demo": false,
    "milestone": "M4"
  },
  {
    "method": "get",
    "path": "/observability/traces",
    "status": 200,
    "demo": false,
    "milestone": "M4"
  },
  {
    "method": "get",
    "path": "/observability/traces/{id}",
    "status": 200,
    "demo": false,
    "milestone": "M4"
  },
  {
    "method": "get",
    "path": "/observability/logs",
    "status": 200,
    "demo": false,
    "milestone": "M4"
  },
  {
    "method": "get",
    "path": "/incidents",
    "status": 200,
    "demo": false,
    "milestone": "M4"
  },
  {
    "method": "get",
    "path": "/incidents/{id}",
    "status": 200,
    "demo": false,
    "milestone": "M4"
  },
  {
    "method": "get",
    "path": "/audit",
    "status": 200,
    "demo": false,
    "milestone": "M1"
  },
  {
    "method": "get",
    "path": "/admin/access",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "get",
    "path": "/admin/navigation",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "get",
    "path": "/admin/cmdb-models",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "get",
    "path": "/integrations",
    "status": 200,
    "demo": false,
    "milestone": "M4"
  },
  {
    "method": "post",
    "path": "/cis",
    "status": 201,
    "demo": false,
    "milestone": "M1"
  },
  {
    "method": "patch",
    "path": "/cis/{id}",
    "status": 200,
    "demo": false,
    "milestone": "M0"
  },
  {
    "method": "post",
    "path": "/relations",
    "status": 201,
    "demo": false,
    "milestone": "M1"
  },
  {
    "method": "delete",
    "path": "/relations/{id}",
    "status": 200,
    "demo": false,
    "milestone": "M1"
  },
  {
    "method": "post",
    "path": "/requests",
    "status": 201,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "patch",
    "path": "/requests/{id}",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "post",
    "path": "/requests/{id}/submit",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "post",
    "path": "/requests/{id}/approve",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "post",
    "path": "/requests/{id}/reject",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "post",
    "path": "/requests/{id}/cancel",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "post",
    "path": "/requests/{id}/provision",
    "status": 202,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "post",
    "path": "/requests/{id}/retry",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "post",
    "path": "/pipelines",
    "status": 202,
    "demo": false,
    "milestone": "M3"
  },
  {
    "method": "post",
    "path": "/pipelines/{id}/cancel",
    "status": 200,
    "demo": false,
    "milestone": "M3"
  },
  {
    "method": "post",
    "path": "/pipelines/{id}/retry",
    "status": 202,
    "demo": false,
    "milestone": "M3"
  },
  {
    "method": "post",
    "path": "/releases/{id}/approve",
    "status": 202,
    "demo": false,
    "milestone": "M3"
  },
  {
    "method": "post",
    "path": "/releases/{id}/reject",
    "status": 200,
    "demo": false,
    "milestone": "M3"
  },
  {
    "method": "post",
    "path": "/releases/{id}/rollback",
    "status": 202,
    "demo": false,
    "milestone": "M3"
  },
  {
    "method": "post",
    "path": "/incidents/{id}/acknowledge",
    "status": 200,
    "demo": false,
    "milestone": "M4"
  },
  {
    "method": "post",
    "path": "/incidents/{id}/investigate",
    "status": 200,
    "demo": false,
    "milestone": "M4"
  },
  {
    "method": "post",
    "path": "/admin/assignments",
    "status": 201,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "delete",
    "path": "/admin/assignments/{id}",
    "status": 200,
    "demo": false,
    "milestone": "M0"
  },
  {
    "method": "patch",
    "path": "/admin/users/{id}",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "patch",
    "path": "/admin/navigation/{id}",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "post",
    "path": "/admin/catalog/{id}/revisions",
    "status": 201,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "patch",
    "path": "/admin/catalog/{id}",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "post",
    "path": "/admin/catalog/{id}/publish",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "post",
    "path": "/admin/catalog/{id}/disable",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "post",
    "path": "/admin/cmdb-fields",
    "status": 201,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "patch",
    "path": "/admin/cmdb-fields/{id}",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "post",
    "path": "/integrations/{id}/test",
    "status": 200,
    "demo": false,
    "milestone": "M4"
  },
  {
    "method": "get",
    "path": "/personas",
    "status": 200,
    "demo": true,
    "milestone": "M0"
  },
  {
    "method": "get",
    "path": "/guide",
    "status": 200,
    "demo": true,
    "milestone": "M0"
  },
  {
    "method": "post",
    "path": "/persona",
    "status": 200,
    "demo": true,
    "milestone": "M0"
  },
  {
    "method": "post",
    "path": "/reset",
    "status": 200,
    "demo": true,
    "milestone": "M0"
  },
  {
    "method": "post",
    "path": "/clock/advance",
    "status": 200,
    "demo": true,
    "milestone": "M0"
  },
  {
    "method": "post",
    "path": "/scenarios",
    "status": 200,
    "demo": true,
    "milestone": "M2"
  },
  {
    "method": "get",
    "path": "/notifications",
    "status": 200,
    "demo": false,
    "milestone": "M4"
  }
]
