/** Generated by pnpm generate:contracts; edit the canonical operation registry. */
export const runtimeOperations: readonly { method: string; path: string; status: number; demo: boolean; milestone: string }[] = [
  {
    "method": "get",
    "path": "/session",
    "status": 200,
    "demo": false,
    "milestone": "M0"
  },
  {
    "method": "get",
    "path": "/organization",
    "status": 200,
    "demo": false,
    "milestone": "M0"
  },
  {
    "method": "get",
    "path": "/navigation",
    "status": 200,
    "demo": false,
    "milestone": "M0"
  },
  {
    "method": "get",
    "path": "/dashboard",
    "status": 200,
    "demo": false,
    "milestone": "M0"
  },
  {
    "method": "get",
    "path": "/applications",
    "status": 200,
    "demo": false,
    "milestone": "M0"
  },
  {
    "method": "get",
    "path": "/cis",
    "status": 200,
    "demo": false,
    "milestone": "M0"
  },
  {
    "method": "get",
    "path": "/cis/{id}",
    "status": 200,
    "demo": false,
    "milestone": "M0"
  },
  {
    "method": "get",
    "path": "/search",
    "status": 200,
    "demo": false,
    "milestone": "M1"
  },
  {
    "method": "get",
    "path": "/applications/{id}",
    "status": 200,
    "demo": false,
    "milestone": "M1"
  },
  {
    "method": "get",
    "path": "/environments/{id}",
    "status": 200,
    "demo": false,
    "milestone": "M1"
  },
  {
    "method": "get",
    "path": "/relations",
    "status": 200,
    "demo": false,
    "milestone": "M1"
  },
  {
    "method": "get",
    "path": "/topology",
    "status": 200,
    "demo": false,
    "milestone": "M1"
  },
  {
    "method": "get",
    "path": "/pools",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "get",
    "path": "/capacity",
    "status": 200,
    "demo": false,
    "milestone": "M1"
  },
  {
    "method": "get",
    "path": "/catalog",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "get",
    "path": "/catalog/{id}",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "get",
    "path": "/requests",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "get",
    "path": "/requests/{id}",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "get",
    "path": "/jobs",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "get",
    "path": "/jobs/{id}",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "get",
    "path": "/pipelines",
    "status": 200,
    "demo": false,
    "milestone": "M3"
  },
  {
    "method": "get",
    "path": "/pipelines/{id}",
    "status": 200,
    "demo": false,
    "milestone": "M3"
  },
  {
    "method": "get",
    "path": "/releases",
    "status": 200,
    "demo": false,
    "milestone": "M3"
  },
  {
    "method": "get",
    "path": "/releases/{id}",
    "status": 200,
    "demo": false,
    "milestone": "M3"
  },
  {
    "method": "get",
    "path": "/observability/metrics",
    "status": 200,
    "demo": false,
    "milestone": "M4"
  },
  {
    "method": "get",
    "path": "/observability/traces",
    "status": 200,
    "demo": false,
    "milestone": "M4"
  },
  {
    "method": "get",
    "path": "/observability/traces/{id}",
    "status": 200,
    "demo": false,
    "milestone": "M4"
  },
  {
    "method": "get",
    "path": "/observability/logs",
    "status": 200,
    "demo": false,
    "milestone": "M4"
  },
  {
    "method": "get",
    "path": "/incidents",
    "status": 200,
    "demo": false,
    "milestone": "M4"
  },
  {
    "method": "get",
    "path": "/incidents/{id}",
    "status": 200,
    "demo": false,
    "milestone": "M4"
  },
  {
    "method": "get",
    "path": "/audit",
    "status": 200,
    "demo": false,
    "milestone": "M1"
  },
  {
    "method": "get",
    "path": "/admin/access",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "get",
    "path": "/admin/navigation",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "get",
    "path": "/admin/cmdb-models",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "get",
    "path": "/integrations",
    "status": 200,
    "demo": false,
    "milestone": "M4"
  },
  {
    "method": "post",
    "path": "/cis",
    "status": 201,
    "demo": false,
    "milestone": "M1"
  },
  {
    "method": "patch",
    "path": "/cis/{id}",
    "status": 200,
    "demo": false,
    "milestone": "M0"
  },
  {
    "method": "post",
    "path": "/relations",
    "status": 201,
    "demo": false,
    "milestone": "M1"
  },
  {
    "method": "delete",
    "path": "/relations/{id}",
    "status": 200,
    "demo": false,
    "milestone": "M1"
  },
  {
    "method": "post",
    "path": "/requests",
    "status": 201,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "patch",
    "path": "/requests/{id}",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "post",
    "path": "/requests/{id}/submit",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "post",
    "path": "/requests/{id}/approve",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "post",
    "path": "/requests/{id}/reject",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "post",
    "path": "/requests/{id}/cancel",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "post",
    "path": "/requests/{id}/provision",
    "status": 202,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "post",
    "path": "/requests/{id}/retry",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "post",
    "path": "/pipelines",
    "status": 202,
    "demo": false,
    "milestone": "M3"
  },
  {
    "method": "post",
    "path": "/pipelines/{id}/cancel",
    "status": 200,
    "demo": false,
    "milestone": "M3"
  },
  {
    "method": "post",
    "path": "/pipelines/{id}/retry",
    "status": 202,
    "demo": false,
    "milestone": "M3"
  },
  {
    "method": "post",
    "path": "/releases/{id}/approve",
    "status": 202,
    "demo": false,
    "milestone": "M3"
  },
  {
    "method": "post",
    "path": "/releases/{id}/reject",
    "status": 200,
    "demo": false,
    "milestone": "M3"
  },
  {
    "method": "post",
    "path": "/releases/{id}/rollback",
    "status": 202,
    "demo": false,
    "milestone": "M3"
  },
  {
    "method": "post",
    "path": "/incidents/{id}/acknowledge",
    "status": 200,
    "demo": false,
    "milestone": "M4"
  },
  {
    "method": "post",
    "path": "/incidents/{id}/investigate",
    "status": 200,
    "demo": false,
    "milestone": "M4"
  },
  {
    "method": "post",
    "path": "/admin/assignments",
    "status": 201,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "delete",
    "path": "/admin/assignments/{id}",
    "status": 200,
    "demo": false,
    "milestone": "M0"
  },
  {
    "method": "patch",
    "path": "/admin/users/{id}",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "patch",
    "path": "/admin/navigation/{id}",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "post",
    "path": "/admin/catalog/{id}/revisions",
    "status": 201,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "patch",
    "path": "/admin/catalog/{id}",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "post",
    "path": "/admin/catalog/{id}/publish",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "post",
    "path": "/admin/catalog/{id}/disable",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "post",
    "path": "/admin/cmdb-fields",
    "status": 201,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "patch",
    "path": "/admin/cmdb-fields/{id}",
    "status": 200,
    "demo": false,
    "milestone": "M2"
  },
  {
    "method": "post",
    "path": "/integrations/{id}/test",
    "status": 200,
    "demo": false,
    "milestone": "M4"
  },
  {
    "method": "get",
    "path": "/personas",
    "status": 200,
    "demo": true,
    "milestone": "M0"
  },
  {
    "method": "get",
    "path": "/guide",
    "status": 200,
    "demo": true,
    "milestone": "M0"
  },
  {
    "method": "post",
    "path": "/persona",
    "status": 200,
    "demo": true,
    "milestone": "M0"
  },
  {
    "method": "post",
    "path": "/reset",
    "status": 200,
    "demo": true,
    "milestone": "M0"
  },
  {
    "method": "post",
    "path": "/clock/advance",
    "status": 200,
    "demo": true,
    "milestone": "M0"
  },
  {
    "method": "post",
    "path": "/scenarios",
    "status": 200,
    "demo": true,
    "milestone": "M2"
  },
  {
    "method": "get",
    "path": "/admin/users",
    "status": 200,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "get",
    "path": "/admin/users/{id}",
    "status": 200,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "get",
    "path": "/admin/teams",
    "status": 200,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "get",
    "path": "/admin/teams/{id}",
    "status": 200,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "get",
    "path": "/admin/platform-features",
    "status": 200,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "get",
    "path": "/admin/platform-features/{id}",
    "status": 200,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "get",
    "path": "/admin/platform-features/{id}/preview",
    "status": 200,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "get",
    "path": "/admin/capability-registry",
    "status": 200,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "get",
    "path": "/admin/platform-routes",
    "status": 200,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "get",
    "path": "/admin/platform-routes/{id}",
    "status": 200,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "get",
    "path": "/admin/platform-routes/{id}/diagnostic",
    "status": 200,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "get",
    "path": "/admin/platform-route-registry",
    "status": 200,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "get",
    "path": "/admin/channels",
    "status": 200,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "get",
    "path": "/admin/notification-templates",
    "status": 200,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "get",
    "path": "/admin/notification-policies",
    "status": 200,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "get",
    "path": "/notification-channels",
    "status": 200,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "get",
    "path": "/notification-subscriptions",
    "status": 200,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "get",
    "path": "/notification-attempts",
    "status": 200,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "get",
    "path": "/notification-attempts/{id}",
    "status": 200,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "get",
    "path": "/notifications",
    "status": 200,
    "demo": false,
    "milestone": "M4"
  },
  {
    "method": "post",
    "path": "/admin/users",
    "status": 201,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "post",
    "path": "/admin/teams",
    "status": 201,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "patch",
    "path": "/admin/teams/{id}",
    "status": 200,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "post",
    "path": "/admin/platform-features",
    "status": 201,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "post",
    "path": "/admin/platform-features/{id}/revisions",
    "status": 201,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "post",
    "path": "/admin/platform-features/{id}/validate",
    "status": 200,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "post",
    "path": "/admin/platform-features/{id}/activate",
    "status": 200,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "post",
    "path": "/admin/platform-features/{id}/disable",
    "status": 200,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "post",
    "path": "/admin/platform-features/{id}/restore",
    "status": 201,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "post",
    "path": "/admin/platform-routes",
    "status": 201,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "post",
    "path": "/admin/platform-routes/{id}/revisions",
    "status": 201,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "post",
    "path": "/admin/platform-routes/{id}/validate",
    "status": 200,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "post",
    "path": "/admin/platform-routes/{id}/activate",
    "status": 200,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "post",
    "path": "/admin/platform-routes/{id}/disable",
    "status": 200,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "post",
    "path": "/admin/platform-routes/{id}/test",
    "status": 200,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "post",
    "path": "/admin/platform-routes/{id}/restore",
    "status": 201,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "post",
    "path": "/admin/channels",
    "status": 201,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "patch",
    "path": "/admin/channels/{id}",
    "status": 200,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "post",
    "path": "/admin/channels/{id}/test",
    "status": 201,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "post",
    "path": "/admin/notification-templates",
    "status": 201,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "post",
    "path": "/admin/notification-templates/{id}/revisions",
    "status": 201,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "post",
    "path": "/admin/notification-templates/{id}/activate",
    "status": 200,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "post",
    "path": "/admin/notification-templates/{id}/disable",
    "status": 200,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "patch",
    "path": "/admin/notification-policies/{id}",
    "status": 200,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "post",
    "path": "/notification-subscriptions",
    "status": 201,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "patch",
    "path": "/notification-subscriptions/{id}",
    "status": 200,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "post",
    "path": "/notification-attempts/{id}/retry",
    "status": 201,
    "demo": false,
    "milestone": "W5"
  },
  {
    "method": "get",
    "path": "/resource-objects",
    "status": 200,
    "demo": false,
    "milestone": "W2"
  },
  {
    "method": "get",
    "path": "/resource-objects/{id}",
    "status": 200,
    "demo": false,
    "milestone": "W2"
  },
  {
    "method": "get",
    "path": "/bindings",
    "status": 200,
    "demo": false,
    "milestone": "W2"
  },
  {
    "method": "get",
    "path": "/bindings/{id}",
    "status": 200,
    "demo": false,
    "milestone": "W2"
  },
  {
    "method": "get",
    "path": "/resource-inventory",
    "status": 200,
    "demo": false,
    "milestone": "W2"
  },
  {
    "method": "get",
    "path": "/resource-inventory/{ciId}",
    "status": 200,
    "demo": false,
    "milestone": "W2"
  },
  {
    "method": "get",
    "path": "/applications/{id}/resources",
    "status": 200,
    "demo": false,
    "milestone": "W2"
  },
  {
    "method": "get",
    "path": "/work-items",
    "status": 200,
    "demo": false,
    "milestone": "W2"
  },
  {
    "method": "get",
    "path": "/changes",
    "status": 200,
    "demo": false,
    "milestone": "W2"
  },
  {
    "method": "get",
    "path": "/changes/{id}",
    "status": 200,
    "demo": false,
    "milestone": "W2"
  },
  {
    "method": "post",
    "path": "/changes",
    "status": 201,
    "demo": false,
    "milestone": "W2"
  },
  {
    "method": "patch",
    "path": "/changes/{id}",
    "status": 200,
    "demo": false,
    "milestone": "W2"
  },
  {
    "method": "post",
    "path": "/changes/{id}/submit",
    "status": 200,
    "demo": false,
    "milestone": "W2"
  },
  {
    "method": "post",
    "path": "/changes/{id}/approve",
    "status": 200,
    "demo": false,
    "milestone": "W2"
  },
  {
    "method": "post",
    "path": "/changes/{id}/reject",
    "status": 200,
    "demo": false,
    "milestone": "W2"
  },
  {
    "method": "post",
    "path": "/changes/{id}/cancel",
    "status": 200,
    "demo": false,
    "milestone": "W2"
  },
  {
    "method": "post",
    "path": "/changes/{id}/execute",
    "status": 202,
    "demo": false,
    "milestone": "W2"
  },
  {
    "method": "post",
    "path": "/changes/{id}/retry",
    "status": 200,
    "demo": false,
    "milestone": "W2"
  },
  {
    "method": "get",
    "path": "/applications/{id}/delivery-options",
    "status": 200,
    "demo": false,
    "milestone": "W3"
  },
  {
    "method": "get",
    "path": "/pipeline-definitions",
    "status": 200,
    "demo": false,
    "milestone": "W3"
  },
  {
    "method": "get",
    "path": "/pipeline-definitions/{id}",
    "status": 200,
    "demo": false,
    "milestone": "W3"
  },
  {
    "method": "post",
    "path": "/pipeline-definitions",
    "status": 201,
    "demo": false,
    "milestone": "W3"
  },
  {
    "method": "patch",
    "path": "/pipeline-definitions/{id}",
    "status": 200,
    "demo": false,
    "milestone": "W3"
  },
  {
    "method": "post",
    "path": "/pipeline-definitions/{id}/validate",
    "status": 200,
    "demo": false,
    "milestone": "W3"
  },
  {
    "method": "post",
    "path": "/pipeline-definitions/{id}/submit",
    "status": 200,
    "demo": false,
    "milestone": "W3"
  },
  {
    "method": "post",
    "path": "/pipeline-definitions/{id}/approve",
    "status": 200,
    "demo": false,
    "milestone": "W3"
  },
  {
    "method": "post",
    "path": "/pipeline-definitions/{id}/reject",
    "status": 200,
    "demo": false,
    "milestone": "W3"
  },
  {
    "method": "post",
    "path": "/pipeline-definitions/{id}/cancel",
    "status": 200,
    "demo": false,
    "milestone": "W3"
  },
  {
    "method": "post",
    "path": "/pipeline-definitions/{id}/activate",
    "status": 200,
    "demo": false,
    "milestone": "W3"
  },
  {
    "method": "post",
    "path": "/pipeline-definitions/{id}/revisions",
    "status": 201,
    "demo": false,
    "milestone": "W3"
  },
  {
    "method": "post",
    "path": "/pipeline-definitions/{id}/runs",
    "status": 202,
    "demo": false,
    "milestone": "W3"
  },
  {
    "method": "get",
    "path": "/service-configs",
    "status": 200,
    "demo": false,
    "milestone": "W3"
  },
  {
    "method": "get",
    "path": "/service-configs/{id}",
    "status": 200,
    "demo": false,
    "milestone": "W3"
  },
  {
    "method": "post",
    "path": "/service-configs",
    "status": 201,
    "demo": false,
    "milestone": "W3"
  },
  {
    "method": "patch",
    "path": "/service-configs/{id}",
    "status": 200,
    "demo": false,
    "milestone": "W3"
  },
  {
    "method": "post",
    "path": "/service-configs/{id}/validate",
    "status": 200,
    "demo": false,
    "milestone": "W3"
  },
  {
    "method": "post",
    "path": "/service-configs/{id}/submit",
    "status": 200,
    "demo": false,
    "milestone": "W3"
  },
  {
    "method": "post",
    "path": "/service-configs/{id}/approve",
    "status": 200,
    "demo": false,
    "milestone": "W3"
  },
  {
    "method": "post",
    "path": "/service-configs/{id}/reject",
    "status": 200,
    "demo": false,
    "milestone": "W3"
  },
  {
    "method": "post",
    "path": "/service-configs/{id}/cancel",
    "status": 200,
    "demo": false,
    "milestone": "W3"
  },
  {
    "method": "post",
    "path": "/service-configs/{id}/apply",
    "status": 202,
    "demo": false,
    "milestone": "W3"
  },
  {
    "method": "post",
    "path": "/service-configs/{id}/revisions",
    "status": 201,
    "demo": false,
    "milestone": "W3"
  },
  {
    "method": "post",
    "path": "/service-configs/{id}/restore",
    "status": 201,
    "demo": false,
    "milestone": "W3"
  },
  {
    "method": "get",
    "path": "/traffic-policies",
    "status": 200,
    "demo": false,
    "milestone": "W3"
  },
  {
    "method": "get",
    "path": "/traffic-policies/{id}",
    "status": 200,
    "demo": false,
    "milestone": "W3"
  },
  {
    "method": "post",
    "path": "/traffic-policies",
    "status": 201,
    "demo": false,
    "milestone": "W3"
  },
  {
    "method": "patch",
    "path": "/traffic-policies/{id}",
    "status": 200,
    "demo": false,
    "milestone": "W3"
  },
  {
    "method": "post",
    "path": "/traffic-policies/{id}/validate",
    "status": 200,
    "demo": false,
    "milestone": "W3"
  },
  {
    "method": "post",
    "path": "/traffic-policies/{id}/submit",
    "status": 200,
    "demo": false,
    "milestone": "W3"
  },
  {
    "method": "post",
    "path": "/traffic-policies/{id}/approve",
    "status": 200,
    "demo": false,
    "milestone": "W3"
  },
  {
    "method": "post",
    "path": "/traffic-policies/{id}/reject",
    "status": 200,
    "demo": false,
    "milestone": "W3"
  },
  {
    "method": "post",
    "path": "/traffic-policies/{id}/cancel",
    "status": 200,
    "demo": false,
    "milestone": "W3"
  },
  {
    "method": "post",
    "path": "/traffic-policies/{id}/start",
    "status": 202,
    "demo": false,
    "milestone": "W3"
  },
  {
    "method": "post",
    "path": "/traffic-policies/{id}/revisions",
    "status": 201,
    "demo": false,
    "milestone": "W3"
  },
  {
    "method": "get",
    "path": "/monitor-policies",
    "status": 200,
    "demo": false,
    "milestone": "W4"
  },
  {
    "method": "get",
    "path": "/monitor-policies/{id}",
    "status": 200,
    "demo": false,
    "milestone": "W4"
  },
  {
    "method": "get",
    "path": "/alert-rules",
    "status": 200,
    "demo": false,
    "milestone": "W4"
  },
  {
    "method": "get",
    "path": "/alert-rules/{id}",
    "status": 200,
    "demo": false,
    "milestone": "W4"
  },
  {
    "method": "get",
    "path": "/slo-policies",
    "status": 200,
    "demo": false,
    "milestone": "W4"
  },
  {
    "method": "get",
    "path": "/slo-policies/{id}",
    "status": 200,
    "demo": false,
    "milestone": "W4"
  },
  {
    "method": "get",
    "path": "/silences",
    "status": 200,
    "demo": false,
    "milestone": "W4"
  },
  {
    "method": "get",
    "path": "/silences/{id}",
    "status": 200,
    "demo": false,
    "milestone": "W4"
  },
  {
    "method": "get",
    "path": "/alert-evaluations",
    "status": 200,
    "demo": false,
    "milestone": "W4"
  },
  {
    "method": "get",
    "path": "/alert-evaluations/{id}",
    "status": 200,
    "demo": false,
    "milestone": "W4"
  },
  {
    "method": "get",
    "path": "/notification-deliveries",
    "status": 200,
    "demo": false,
    "milestone": "W4"
  },
  {
    "method": "get",
    "path": "/notification-deliveries/{id}",
    "status": 200,
    "demo": false,
    "milestone": "W4"
  },
  {
    "method": "post",
    "path": "/monitor-policies",
    "status": 201,
    "demo": false,
    "milestone": "W4"
  },
  {
    "method": "post",
    "path": "/monitor-policies/{id}/revise",
    "status": 201,
    "demo": false,
    "milestone": "W4"
  },
  {
    "method": "post",
    "path": "/monitor-policies/{id}/validate",
    "status": 200,
    "demo": false,
    "milestone": "W4"
  },
  {
    "method": "post",
    "path": "/monitor-policies/{id}/submit",
    "status": 200,
    "demo": false,
    "milestone": "W4"
  },
  {
    "method": "post",
    "path": "/monitor-policies/{id}/approve",
    "status": 200,
    "demo": false,
    "milestone": "W4"
  },
  {
    "method": "post",
    "path": "/monitor-policies/{id}/reject",
    "status": 200,
    "demo": false,
    "milestone": "W4"
  },
  {
    "method": "post",
    "path": "/monitor-policies/{id}/activate",
    "status": 200,
    "demo": false,
    "milestone": "W4"
  },
  {
    "method": "post",
    "path": "/alert-rules",
    "status": 201,
    "demo": false,
    "milestone": "W4"
  },
  {
    "method": "post",
    "path": "/alert-rules/{id}/revise",
    "status": 201,
    "demo": false,
    "milestone": "W4"
  },
  {
    "method": "post",
    "path": "/alert-rules/{id}/validate",
    "status": 200,
    "demo": false,
    "milestone": "W4"
  },
  {
    "method": "post",
    "path": "/alert-rules/{id}/submit",
    "status": 200,
    "demo": false,
    "milestone": "W4"
  },
  {
    "method": "post",
    "path": "/alert-rules/{id}/approve",
    "status": 200,
    "demo": false,
    "milestone": "W4"
  },
  {
    "method": "post",
    "path": "/alert-rules/{id}/reject",
    "status": 200,
    "demo": false,
    "milestone": "W4"
  },
  {
    "method": "post",
    "path": "/alert-rules/{id}/activate",
    "status": 200,
    "demo": false,
    "milestone": "W4"
  },
  {
    "method": "post",
    "path": "/slo-policies",
    "status": 201,
    "demo": false,
    "milestone": "W4"
  },
  {
    "method": "post",
    "path": "/slo-policies/{id}/revise",
    "status": 201,
    "demo": false,
    "milestone": "W4"
  },
  {
    "method": "post",
    "path": "/slo-policies/{id}/validate",
    "status": 200,
    "demo": false,
    "milestone": "W4"
  },
  {
    "method": "post",
    "path": "/slo-policies/{id}/submit",
    "status": 200,
    "demo": false,
    "milestone": "W4"
  },
  {
    "method": "post",
    "path": "/slo-policies/{id}/approve",
    "status": 200,
    "demo": false,
    "milestone": "W4"
  },
  {
    "method": "post",
    "path": "/slo-policies/{id}/reject",
    "status": 200,
    "demo": false,
    "milestone": "W4"
  },
  {
    "method": "post",
    "path": "/slo-policies/{id}/activate",
    "status": 200,
    "demo": false,
    "milestone": "W4"
  },
  {
    "method": "post",
    "path": "/silences",
    "status": 201,
    "demo": false,
    "milestone": "W4"
  }
]
