// User-visible strings of @cms/fields (zh-Hant). Key rule: docs/v2/waves/W0.md §4.6.
export const fieldsCopy = {
  "fields.clear": "清除",
  "fields.group.main": "基本資料",
  "fields.group.media": "媒體",
  "fields.group.relations": "關聯",
  "fields.group.settings": "設定",
  "fields.required": "必填",
  "fields.unset": "未設定",
  "fields.choose": "請選擇",
  "fields.markdown.edit": "編輯",
  "fields.markdown.preview": "預覽",
  "fields.markdown.empty": "沒有內容",
  "fields.datetime.date": "日期",
  "fields.datetime.time": "時間",
  "fields.datetime.pick": "選擇日期",
  "fields.datetime.clear": "清除",
  "fields.boolean.yes": "是",
  "fields.ref.untitled": "未命名",
  "fields.ref.restricted": "你無法檢視這個項目",
  "fields.ref.missing": "連結的項目已不存在",
  "fields.media.unavailable": "無法顯示這個媒體",
  "fields.principal.linked": "已連結會員帳號",
  "fields.unknown.note": "這個欄位目前無法在這裡編輯，儲存時會保留原本的內容。",
  "fields.error.REQUIRED": "這是必填欄位。",
  "fields.error.RESERVED_KEY": "這個名稱是保留欄位。",
  "fields.error.WRONG_TYPE": "格式不正確。",
  "fields.error.TOO_LONG": "內容太長。",
  "fields.error.INVALID_DATETIME": "日期時間不正確。",
  "fields.error.NOT_IN_ENUM": "請從選項中選擇。",
  "fields.error.INVALID_UUID": "連結的項目不正確。",
  "fields.error.REF_TARGET_NOT_FOUND": "連結的項目已不存在。",
  "fields.error.REF_TARGET_WRONG_TYPE": "連結的項目類型不正確。",
  "fields.error.PRINCIPAL_REF_UNRESOLVED": "找不到這個會員帳號。",
} as const;

export type FieldsCopyKey = keyof typeof fieldsCopy;
