apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gateway-produce
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway-produce
      app.kubernetes.io/part-of: ojbquay
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gateway-consume
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway-consume
      app.kubernetes.io/part-of: ojbquay
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gateway-produce
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gateway-produce
  minReplicas: 2
  maxReplicas: 10
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
