import type { ContractContext } from '../contracts.ts'

export function registerFutureContracts({ z, d, w, s, id, version, listQuery, windowQuery, pageFields, logEntry, metricSeries, traceSummary, read, command }: ContractContext) {
  read('/pools', 'listPools', z.array(s.ResourcePool), 'M2', z.strictObject({ provider: d.providerSchema.optional(), projectId: id.optional() }))
  read('/capacity', 'getCapacity', z.array(w.Capacity), 'M1', z.strictObject({ provider: d.providerSchema.optional(), projectId: id.optional() }))
  read('/catalog', 'listCatalog', d.pageSchema(s.CatalogItem), 'M2', listQuery({ revision: version.optional() }))
  read('/catalog/{id}', 'getCatalog', s.CatalogItem, 'M2', z.strictObject({ revision: version.optional() }))
  read('/requests', 'listRequests', d.pageSchema(s.Request), 'M2', listQuery({ state: d.requestSchema.shape.state.optional(), applicationId: id.optional(), requesterId: id.optional() }, ['id', 'updatedAt']))
  read('/requests/{id}', 'getRequest', z.strictObject({ request: s.Request, jobs: z.array(s.ProvisionJob) }), 'M2')
  read('/jobs', 'listJobs', d.pageSchema(s.ProvisionJob), 'M2', listQuery({ requestId: id.optional(), state: d.provisionJobSchema.shape.state.optional() }, ['id', 'updatedAt']))
  read('/jobs/{id}', 'getJob', z.strictObject({ job: s.ProvisionJob, logs: z.array(logEntry).max(500) }), 'M2')
  read('/pipelines', 'listPipelines', d.pageSchema(s.PipelineRun), 'M3', listQuery({ applicationId: id.optional(), environmentId: id.optional(), state: d.pipelineRunSchema.shape.state.optional() }, ['id', 'updatedAt']))
  read('/pipelines/{id}', 'getPipeline', z.strictObject({ run: s.PipelineRun, logs: z.array(s.DeliveryLog).max(500) }), 'M3')
  read('/releases', 'listReleases', d.pageSchema(s.Release), 'M3', listQuery({ environmentId: id.optional(), state: d.releaseSchema.shape.state.optional(), kind: d.releaseSchema.shape.kind.optional() }, ['id', 'updatedAt']))
  read('/releases/{id}', 'getRelease', s.ReleaseDetail, 'M3')
  read('/observability/metrics', 'getMetrics', z.strictObject({ series: z.array(metricSeries) }), 'M4', windowQuery({ step: z.literal('60s').default('60s') }))
  read('/observability/traces', 'listTraces', d.pageSchema(traceSummary), 'M4', windowQuery({ ...pageFields, status: z.enum(['ok', 'error']).optional(), sort: z.enum(['id', 'start', 'durationMs']).default('start') }))
  read('/observability/traces/{id}', 'getTrace', w.Trace, 'M4')
  read('/observability/logs', 'listLogs', d.pageSchema(logEntry), 'M4', windowQuery({ ...pageFields, traceId: id.optional(), releaseId: id.optional(), level: logEntry.shape.level.optional(), sort: z.enum(['id', 'occurredAt']).default('occurredAt') }))
  read('/incidents', 'listIncidents', d.pageSchema(w.IncidentView), 'M4', listQuery({ environmentId: id.optional(), ciId: id.optional(), state: d.incidentSchema.shape.state.optional(), severity: d.incidentSchema.shape.severity.optional() }, ['id', 'updatedAt']))
  read('/incidents/{id}', 'getIncident', w.IncidentView, 'M4')
  read('/audit', 'listAudit', d.pageSchema(s.AuditEvent), 'M1', listQuery({ entityType: id.optional(), entityId: id.optional(), correlationId: id.optional(), actorId: id.optional(), from: d.timestampSchema.optional(), to: d.timestampSchema.optional() }, ['id', 'occurredAt']))
  read('/admin/access', 'getAccess', z.strictObject({ organizations: z.array(s.Organization), users: z.array(s.User), assignments: z.array(s.RoleAssignment), policyVersion: version }), 'M2')
  const identityPageQuery = z.strictObject({ page: pageFields.page, pageSize: pageFields.pageSize })
  read('/admin/users', 'listAdminUsers', d.pageSchema(s.User), 'W5', identityPageQuery)
  read('/admin/users/{id}', 'getAdminUser', s.User, 'W5')
  read('/admin/teams', 'listAdminTeams', d.pageSchema(s.Team), 'W5', identityPageQuery)
  read('/admin/teams/{id}', 'getAdminTeam', s.Team, 'W5')
  read('/admin/platform-features', 'listPlatformFeatures', d.pageSchema(s.PlatformFeature), 'W5', identityPageQuery)
  read('/admin/platform-features/{id}', 'getPlatformFeature', s.PlatformFeature, 'W5')
  read('/admin/platform-features/{id}/preview', 'previewPlatformFeature', s.FeaturePreview, 'W5')
  read('/admin/capability-registry', 'getCapabilityRegistry', s.CapabilityRegistry, 'W5')
  read('/admin/platform-routes', 'listPlatformRoutes', d.pageSchema(s.PlatformRoute), 'W5', identityPageQuery)
  read('/admin/platform-routes/{id}', 'getPlatformRoute', s.PlatformRoute, 'W5')
  read('/admin/platform-routes/{id}/diagnostic', 'getPlatformRouteDiagnostic', s.PlatformRouteDiagnostic, 'W5')
  read('/admin/platform-route-registry', 'getPlatformRouteRegistry', z.array(s.PlatformRouteRegistryEntry), 'W5')
  read('/admin/channels', 'listAdminChannels', z.array(s.Channel), 'W5')
  read('/admin/notification-templates', 'listAdminNotificationTemplates', z.array(s.NotificationTemplate), 'W5')
  read('/admin/notification-policies', 'listAdminNotificationPolicies', z.array(s.NotificationPolicy), 'W5')
  read('/notification-channels', 'listNotificationChannels', z.array(s.Channel), 'W5', z.strictObject({ environmentId: id }))
  read('/notification-subscriptions', 'listNotificationSubscriptions', d.pageSchema(s.NotificationSubscription), 'W5',
    z.strictObject({ environmentId: id.optional(), page: pageFields.page, pageSize: pageFields.pageSize }))
  read('/notification-attempts', 'listNotificationAttempts', d.pageSchema(s.NotificationAttemptView), 'W5',
    z.strictObject({ environmentId: id.optional(), status: s.NotificationAttempt.shape.status.optional(),
      page: pageFields.page, pageSize: pageFields.pageSize }))
  read('/notification-attempts/{id}', 'getNotificationAttempt', s.NotificationAttemptView, 'W5')
  read('/admin/navigation', 'getAdminNavigation', z.array(s.NavigationItem), 'M2', z.strictObject({ center: d.centerSchema.optional() }))
  read('/admin/cmdb-models', 'getModels', z.strictObject({ kinds: z.array(d.ciKindSchema), fields: z.array(s.ModelField) }), 'M2')
  read('/notifications', 'getNotifications', z.strictObject({ items: z.array(s.Notification).max(20) }), 'M4')
  read('/integrations', 'listIntegrations', z.array(s.Integration), 'M4')

  command('post', '/requests', 'createRequest', w.CreateRequest, 'M2', 201)
  command('patch', '/requests/{id}', 'patchRequest', w.PatchRequest, 'M2')
  for (const action of ['submit', 'approve', 'reject', 'cancel', 'provision', 'retry']) command('post', `/requests/{id}/${action}`, `${action}Request`, ['submit', 'provision'].includes(action) ? w.VersionCommand : w.ReasonCommand, 'M2', action === 'provision' ? 202 : 200)
  command('post', '/pipelines', 'createPipeline', w.CreatePipeline, 'M3', 202)
  command('post', '/pipelines/{id}/cancel', 'cancelPipeline', w.ReasonCommand, 'M3')
  command('post', '/pipelines/{id}/retry', 'retryPipeline', w.ReasonCommand, 'M3', 202)
  command('post', '/releases/{id}/approve', 'approveRelease', w.ReasonCommand, 'M3', 202)
  command('post', '/releases/{id}/reject', 'rejectRelease', w.ReasonCommand, 'M3')
  command('post', '/releases/{id}/rollback', 'rollbackRelease', w.RollbackRelease, 'M3', 202)
  command('post', '/incidents/{id}/acknowledge', 'acknowledgeIncident', w.AcknowledgeIncident, 'M4')
  command('post', '/incidents/{id}/investigate', 'investigateIncident', w.ReasonCommand, 'M4')
  command('post', '/admin/assignments', 'createAssignment', w.CreateAssignment, 'M2', 201)
  command('post', '/admin/users', 'createAdminUser', w.CreateUser, 'W5', 201)
  command('post', '/admin/teams', 'createAdminTeam', w.CreateTeam, 'W5', 201)
  command('patch', '/admin/teams/{id}', 'patchAdminTeam', w.PatchTeam, 'W5')
  command('post', '/admin/platform-features', 'createPlatformFeature', w.CreateFeature, 'W5', 201)
  command('post', '/admin/platform-features/{id}/revisions', 'revisePlatformFeature', w.ReviseFeature, 'W5', 201)
  for (const action of ['validate', 'activate', 'disable']) command('post', `/admin/platform-features/{id}/${action}`, `${action}PlatformFeature`, w.FeatureAction, 'W5')
  command('post', '/admin/platform-features/{id}/restore', 'restorePlatformFeature', w.RestoreFeature, 'W5', 201)
  command('post', '/admin/platform-routes', 'createPlatformRoute', w.CreatePlatformRoute, 'W5', 201)
  command('post', '/admin/platform-routes/{id}/revisions', 'revisePlatformRoute', w.RevisePlatformRoute, 'W5', 201)
  for (const action of ['validate', 'activate', 'disable', 'test']) command('post', `/admin/platform-routes/{id}/${action}`, `${action}PlatformRoute`, w.PlatformRouteAction, 'W5')
  command('post', '/admin/platform-routes/{id}/restore', 'restorePlatformRoute', w.RestorePlatformRoute, 'W5', 201)
  command('post', '/admin/channels', 'createChannel', w.CreateChannel, 'W5', 201)
  command('patch', '/admin/channels/{id}', 'patchChannel', w.PatchChannel, 'W5')
  command('post', '/admin/channels/{id}/test', 'testChannel', w.TestChannel, 'W5', 201)
  command('post', '/admin/notification-templates', 'createNotificationTemplate', w.CreateNotificationTemplate, 'W5', 201)
  command('post', '/admin/notification-templates/{id}/revisions', 'reviseNotificationTemplate', w.ReviseNotificationTemplate, 'W5', 201)
  for (const action of ['activate', 'disable']) command('post', `/admin/notification-templates/{id}/${action}`, `${action}NotificationTemplate`, w.NotificationTemplateAction, 'W5')
  command('patch', '/admin/notification-policies/{id}', 'patchNotificationPolicy', w.PatchNotificationPolicy, 'W5')
  command('post', '/notification-subscriptions', 'createNotificationSubscription', w.CreateNotificationSubscription, 'W5', 201)
  command('patch', '/notification-subscriptions/{id}', 'patchNotificationSubscription', w.PatchNotificationSubscription, 'W5')
  command('post', '/notification-attempts/{id}/retry', 'retryNotificationAttempt', w.RetryNotificationAttempt, 'W5', 201)
  command('patch', '/admin/users/{id}', 'patchUser', w.PatchUser, 'M2')
  command('patch', '/admin/navigation/{id}', 'patchNavigation', w.PatchNavigation, 'M2')
  command('post', '/admin/catalog/{id}/revisions', 'createCatalogRevision', w.CreateCatalogRevision, 'M2', 201)
  command('patch', '/admin/catalog/{id}', 'patchCatalog', w.PatchCatalog, 'M2')
  command('post', '/admin/catalog/{id}/publish', 'publishCatalog', w.PublishCatalog, 'M2')
  command('post', '/admin/catalog/{id}/disable', 'disableCatalog', w.ReasonCommand, 'M2')
  command('post', '/admin/cmdb-fields', 'createModelField', w.CreateModelField, 'M2', 201)
  command('patch', '/admin/cmdb-fields/{id}', 'patchModelField', w.PatchModelField, 'M2')
  command('post', '/integrations/{id}/test', 'testIntegration', w.VersionCommand, 'M4')
  command('post', '/scenarios', 'setScenario', w.ScenarioBody, 'M2', 200, true)
}
