// Generated by scripts/gen-fixtures.mjs from fixtures/*.json. Do not edit; run `npm run gen -w @cms/mocks`.
import type { components } from "@cms/api";

type S = components["schemas"];

export const me: Record<string, S["Me"]> = {
  "seed-admin": {
    "principal": {
      "id": "10000000-0000-4000-8000-000000000001",
      "username": "seed-admin",
      "displayName": "Platform admin",
      "status": "active"
    },
    "roles": [
      {
        "code": "admin",
        "contentTypeCodes": []
      }
    ],
    "surfaces": {
      "front": true,
      "back": true,
      "admin": true
    }
  },
  "seed-editor-album": {
    "principal": {
      "id": "10000000-0000-4000-8000-000000000002",
      "username": "seed-editor-album",
      "displayName": "Album editor",
      "status": "active"
    },
    "roles": [
      {
        "code": "editor",
        "contentTypeCodes": [
          "album",
          "photo"
        ]
      }
    ],
    "surfaces": {
      "front": true,
      "back": true,
      "admin": false
    }
  },
  "seed-operator-album": {
    "principal": {
      "id": "10000000-0000-4000-8000-000000000003",
      "username": "seed-operator-album",
      "displayName": "Album operator",
      "status": "active"
    },
    "roles": [
      {
        "code": "operator",
        "contentTypeCodes": [
          "album",
          "photo"
        ]
      }
    ],
    "surfaces": {
      "front": true,
      "back": true,
      "admin": false
    }
  },
  "seed-member-clinic": {
    "principal": {
      "id": "10000000-0000-4000-8000-000000000004",
      "username": "seed-member-clinic",
      "displayName": "Clinic member",
      "status": "active"
    },
    "roles": [
      {
        "code": "member",
        "contentTypeCodes": []
      }
    ],
    "surfaces": {
      "front": true,
      "back": false,
      "admin": false
    }
  },
  "seed-editor-clinic": {
    "principal": {
      "id": "10000000-0000-4000-8000-000000000005",
      "username": "seed-editor-clinic",
      "displayName": "Clinic editor",
      "status": "active"
    },
    "roles": [
      {
        "code": "editor",
        "contentTypeCodes": [
          "clinic_profile",
          "vet"
        ]
      }
    ],
    "surfaces": {
      "front": true,
      "back": true,
      "admin": false
    }
  },
  "seed-operator-clinic": {
    "principal": {
      "id": "10000000-0000-4000-8000-000000000006",
      "username": "seed-operator-clinic",
      "displayName": "Clinic operator",
      "status": "active"
    },
    "roles": [
      {
        "code": "operator",
        "contentTypeCodes": [
          "clinic_profile",
          "owner",
          "pet",
          "vet",
          "visit"
        ]
      }
    ],
    "surfaces": {
      "front": true,
      "back": true,
      "admin": false
    }
  },
  "seed-editor-projects": {
    "principal": {
      "id": "10000000-0000-4000-8000-000000000007",
      "username": "seed-editor-projects",
      "displayName": "Projects editor",
      "status": "active"
    },
    "roles": [
      {
        "code": "editor",
        "contentTypeCodes": [
          "project",
          "milestone"
        ]
      }
    ],
    "surfaces": {
      "front": true,
      "back": true,
      "admin": false
    }
  },
  "seed-operator-projects": {
    "principal": {
      "id": "10000000-0000-4000-8000-000000000008",
      "username": "seed-operator-projects",
      "displayName": "Projects operator",
      "status": "active"
    },
    "roles": [
      {
        "code": "operator",
        "contentTypeCodes": [
          "project",
          "issue",
          "milestone"
        ]
      }
    ],
    "surfaces": {
      "front": true,
      "back": true,
      "admin": false
    }
  },
  "seed-member-projects": {
    "principal": {
      "id": "10000000-0000-4000-8000-000000000009",
      "username": "seed-member-projects",
      "displayName": "Projects member",
      "status": "active"
    },
    "roles": [
      {
        "code": "member",
        "contentTypeCodes": []
      }
    ],
    "surfaces": {
      "front": true,
      "back": false,
      "admin": false
    }
  }
};

export const principals: S["PrincipalList"] = {
  "items": [
    {
      "id": "10000000-0000-4000-8000-000000000001",
      "username": "seed-admin",
      "displayName": "Platform admin",
      "email": null,
      "status": "active"
    },
    {
      "id": "10000000-0000-4000-8000-000000000002",
      "username": "seed-editor-album",
      "displayName": "Album editor",
      "email": null,
      "status": "active"
    },
    {
      "id": "10000000-0000-4000-8000-000000000005",
      "username": "seed-editor-clinic",
      "displayName": "Clinic editor",
      "email": null,
      "status": "active"
    },
    {
      "id": "10000000-0000-4000-8000-000000000007",
      "username": "seed-editor-projects",
      "displayName": "Projects editor",
      "email": null,
      "status": "active"
    },
    {
      "id": "10000000-0000-4000-8000-000000000004",
      "username": "seed-member-clinic",
      "displayName": "Clinic member",
      "email": null,
      "status": "active"
    },
    {
      "id": "10000000-0000-4000-8000-000000000009",
      "username": "seed-member-projects",
      "displayName": "Projects member",
      "email": null,
      "status": "active"
    },
    {
      "id": "10000000-0000-4000-8000-000000000003",
      "username": "seed-operator-album",
      "displayName": "Album operator",
      "email": null,
      "status": "active"
    },
    {
      "id": "10000000-0000-4000-8000-000000000006",
      "username": "seed-operator-clinic",
      "displayName": "Clinic operator",
      "email": null,
      "status": "active"
    },
    {
      "id": "10000000-0000-4000-8000-000000000008",
      "username": "seed-operator-projects",
      "displayName": "Projects operator",
      "email": null,
      "status": "active"
    }
  ],
  "page": 0,
  "size": 9,
  "total": 9
};

export const workContentTypes: S["WorkContentTypeList"] = {
  "items": [
    {
      "key": "album",
      "displayName": "Album",
      "pluralDisplayName": "Albums",
      "titleField": "title",
      "slugPolicy": "required",
      "fields": [
        {
          "key": "title",
          "type": "string",
          "required": true,
          "refTarget": null,
          "enumValues": []
        },
        {
          "key": "description",
          "type": "markdown",
          "required": false,
          "refTarget": null,
          "enumValues": []
        },
        {
          "key": "cover",
          "type": "media-ref",
          "required": false,
          "refTarget": null,
          "enumValues": []
        },
        {
          "key": "visibility",
          "type": "enum",
          "required": false,
          "refTarget": null,
          "enumValues": [
            "public",
            "unlisted"
          ]
        },
        {
          "key": "sortMode",
          "type": "enum",
          "required": false,
          "refTarget": null,
          "enumValues": [
            "manual",
            "captured_at"
          ]
        }
      ]
    },
    {
      "key": "photo",
      "displayName": "Photo",
      "pluralDisplayName": "Photos",
      "titleField": "title",
      "slugPolicy": "optional",
      "fields": [
        {
          "key": "title",
          "type": "string",
          "required": false,
          "refTarget": null,
          "enumValues": []
        },
        {
          "key": "caption",
          "type": "string",
          "required": false,
          "refTarget": null,
          "enumValues": []
        },
        {
          "key": "album",
          "type": "ref",
          "required": true,
          "refTarget": "album",
          "enumValues": []
        },
        {
          "key": "sortOrder",
          "type": "int",
          "required": false,
          "refTarget": null,
          "enumValues": []
        },
        {
          "key": "takenAt",
          "type": "datetime",
          "required": false,
          "refTarget": null,
          "enumValues": []
        },
        {
          "key": "media",
          "type": "media-ref",
          "required": false,
          "refTarget": null,
          "enumValues": []
        }
      ]
    },
    {
      "key": "page",
      "displayName": "Page",
      "pluralDisplayName": "Pages",
      "titleField": "title",
      "slugPolicy": "required",
      "fields": [
        {
          "key": "title",
          "type": "string",
          "required": true,
          "refTarget": null,
          "enumValues": []
        },
        {
          "key": "body",
          "type": "markdown",
          "required": false,
          "refTarget": null,
          "enumValues": []
        }
      ]
    },
    {
      "key": "clinic_profile",
      "displayName": "Clinic profile",
      "pluralDisplayName": "Clinic profiles",
      "titleField": "name",
      "slugPolicy": "required",
      "fields": [
        {
          "key": "name",
          "type": "string",
          "required": true,
          "refTarget": null,
          "enumValues": []
        },
        {
          "key": "intro",
          "type": "markdown",
          "required": true,
          "refTarget": null,
          "enumValues": []
        },
        {
          "key": "address",
          "type": "string",
          "required": false,
          "refTarget": null,
          "enumValues": []
        },
        {
          "key": "telephone",
          "type": "string",
          "required": false,
          "refTarget": null,
          "enumValues": []
        },
        {
          "key": "hours",
          "type": "markdown",
          "required": false,
          "refTarget": null,
          "enumValues": []
        },
        {
          "key": "hero",
          "type": "media-ref",
          "required": false,
          "refTarget": null,
          "enumValues": []
        }
      ]
    },
    {
      "key": "owner",
      "displayName": "Owner",
      "pluralDisplayName": "Owners",
      "titleField": "title",
      "slugPolicy": "optional",
      "fields": [
        {
          "key": "title",
          "type": "string",
          "required": true,
          "refTarget": null,
          "enumValues": []
        },
        {
          "key": "firstName",
          "type": "string",
          "required": false,
          "refTarget": null,
          "enumValues": []
        },
        {
          "key": "lastName",
          "type": "string",
          "required": false,
          "refTarget": null,
          "enumValues": []
        },
        {
          "key": "address",
          "type": "string",
          "required": false,
          "refTarget": null,
          "enumValues": []
        },
        {
          "key": "city",
          "type": "string",
          "required": false,
          "refTarget": null,
          "enumValues": []
        },
        {
          "key": "telephone",
          "type": "string",
          "required": false,
          "refTarget": null,
          "enumValues": []
        },
        {
          "key": "email",
          "type": "string",
          "required": false,
          "refTarget": null,
          "enumValues": []
        },
        {
          "key": "ownerPrincipalId",
          "type": "principal-ref",
          "required": false,
          "refTarget": null,
          "enumValues": []
        }
      ]
    },
    {
      "key": "pet",
      "displayName": "Pet",
      "pluralDisplayName": "Pets",
      "titleField": "title",
      "slugPolicy": "optional",
      "fields": [
        {
          "key": "title",
          "type": "string",
          "required": true,
          "refTarget": null,
          "enumValues": []
        },
        {
          "key": "name",
          "type": "string",
          "required": false,
          "refTarget": null,
          "enumValues": []
        },
        {
          "key": "petType",
          "type": "enum",
          "required": false,
          "refTarget": null,
          "enumValues": [
            "cat",
            "dog",
            "bird",
            "hamster",
            "lizard",
            "snake",
            "other"
          ]
        },
        {
          "key": "birthDate",
          "type": "datetime",
          "required": false,
          "refTarget": null,
          "enumValues": []
        },
        {
          "key": "owner",
          "type": "ref",
          "required": true,
          "refTarget": "owner",
          "enumValues": []
        },
        {
          "key": "ownerPrincipalId",
          "type": "principal-ref",
          "required": false,
          "refTarget": null,
          "enumValues": []
        },
        {
          "key": "notes",
          "type": "markdown",
          "required": false,
          "refTarget": null,
          "enumValues": []
        },
        {
          "key": "photo",
          "type": "media-ref",
          "required": false,
          "refTarget": null,
          "enumValues": []
        }
      ]
    },
    {
      "key": "vet",
      "displayName": "Vet",
      "pluralDisplayName": "Vets",
      "titleField": "title",
      "slugPolicy": "optional",
      "fields": [
        {
          "key": "title",
          "type": "string",
          "required": true,
          "refTarget": null,
          "enumValues": []
        },
        {
          "key": "firstName",
          "type": "string",
          "required": false,
          "refTarget": null,
          "enumValues": []
        },
        {
          "key": "lastName",
          "type": "string",
          "required": false,
          "refTarget": null,
          "enumValues": []
        },
        {
          "key": "specialty",
          "type": "enum",
          "required": false,
          "refTarget": null,
          "enumValues": [
            "general",
            "radiology",
            "surgery",
            "dentistry"
          ]
        },
        {
          "key": "bio",
          "type": "markdown",
          "required": false,
          "refTarget": null,
          "enumValues": []
        },
        {
          "key": "photo",
          "type": "media-ref",
          "required": false,
          "refTarget": null,
          "enumValues": []
        }
      ]
    },
    {
      "key": "visit",
      "displayName": "Visit",
      "pluralDisplayName": "Visits",
      "titleField": "title",
      "slugPolicy": "none",
      "fields": [
        {
          "key": "title",
          "type": "string",
          "required": false,
          "refTarget": null,
          "enumValues": []
        },
        {
          "key": "pet",
          "type": "ref",
          "required": true,
          "refTarget": "pet",
          "enumValues": []
        },
        {
          "key": "owner",
          "type": "ref",
          "required": false,
          "refTarget": "owner",
          "enumValues": []
        },
        {
          "key": "vet",
          "type": "ref",
          "required": false,
          "refTarget": "vet",
          "enumValues": []
        },
        {
          "key": "scheduledAt",
          "type": "datetime",
          "required": false,
          "refTarget": null,
          "enumValues": []
        },
        {
          "key": "description",
          "type": "string",
          "required": false,
          "refTarget": null,
          "enumValues": []
        },
        {
          "key": "visitKind",
          "type": "enum",
          "required": false,
          "refTarget": null,
          "enumValues": [
            "checkup",
            "vaccine",
            "surgery",
            "other"
          ]
        },
        {
          "key": "ownerPrincipalId",
          "type": "principal-ref",
          "required": false,
          "refTarget": null,
          "enumValues": []
        }
      ]
    },
    {
      "key": "project",
      "displayName": "Project",
      "pluralDisplayName": "Projects",
      "titleField": "title",
      "slugPolicy": "required",
      "fields": [
        {
          "key": "title",
          "type": "string",
          "required": true,
          "refTarget": null,
          "enumValues": []
        },
        {
          "key": "summary",
          "type": "markdown",
          "required": false,
          "refTarget": null,
          "enumValues": []
        },
        {
          "key": "cover",
          "type": "media-ref",
          "required": false,
          "refTarget": null,
          "enumValues": []
        },
        {
          "key": "visibility",
          "type": "enum",
          "required": false,
          "refTarget": null,
          "enumValues": [
            "public",
            "private"
          ]
        },
        {
          "key": "lifecycle",
          "type": "enum",
          "required": false,
          "refTarget": null,
          "enumValues": [
            "active",
            "completed"
          ]
        }
      ]
    },
    {
      "key": "issue",
      "displayName": "Issue",
      "pluralDisplayName": "Issues",
      "titleField": "title",
      "slugPolicy": "optional",
      "fields": [
        {
          "key": "title",
          "type": "string",
          "required": true,
          "refTarget": null,
          "enumValues": []
        },
        {
          "key": "project",
          "type": "ref",
          "required": true,
          "refTarget": "project",
          "enumValues": []
        },
        {
          "key": "milestone",
          "type": "ref",
          "required": false,
          "refTarget": "milestone",
          "enumValues": []
        },
        {
          "key": "body",
          "type": "markdown",
          "required": false,
          "refTarget": null,
          "enumValues": []
        },
        {
          "key": "status",
          "type": "enum",
          "required": true,
          "refTarget": null,
          "enumValues": [
            "backlog",
            "ready",
            "in_progress",
            "in_review",
            "done"
          ]
        },
        {
          "key": "assigneePrincipalId",
          "type": "string",
          "required": false,
          "refTarget": null,
          "enumValues": []
        },
        {
          "key": "sortOrder",
          "type": "int",
          "required": false,
          "refTarget": null,
          "enumValues": []
        }
      ]
    },
    {
      "key": "milestone",
      "displayName": "Milestone",
      "pluralDisplayName": "Milestones",
      "titleField": "title",
      "slugPolicy": "required",
      "fields": [
        {
          "key": "title",
          "type": "string",
          "required": true,
          "refTarget": null,
          "enumValues": []
        },
        {
          "key": "project",
          "type": "ref",
          "required": true,
          "refTarget": "project",
          "enumValues": []
        },
        {
          "key": "description",
          "type": "markdown",
          "required": false,
          "refTarget": null,
          "enumValues": []
        },
        {
          "key": "dueDate",
          "type": "datetime",
          "required": false,
          "refTarget": null,
          "enumValues": []
        },
        {
          "key": "status",
          "type": "enum",
          "required": false,
          "refTarget": null,
          "enumValues": [
            "planned",
            "reached",
            "missed"
          ]
        },
        {
          "key": "sortOrder",
          "type": "int",
          "required": false,
          "refTarget": null,
          "enumValues": []
        }
      ]
    }
  ]
};

export const adminContentTypes: S["AdminContentTypeList"] = {
  "items": [
    {
      "key": "album",
      "displayName": "Album",
      "pluralDisplayName": "Albums",
      "titleField": "title",
      "slugPolicy": "required",
      "enabled": true,
      "fields": [
        {
          "key": "title",
          "type": "string",
          "required": true,
          "indexed": true,
          "refTarget": null
        },
        {
          "key": "description",
          "type": "markdown",
          "required": false,
          "indexed": false,
          "refTarget": null
        },
        {
          "key": "cover",
          "type": "media-ref",
          "required": false,
          "indexed": false,
          "refTarget": null
        },
        {
          "key": "visibility",
          "type": "enum",
          "required": false,
          "indexed": true,
          "refTarget": null
        },
        {
          "key": "sortMode",
          "type": "enum",
          "required": false,
          "indexed": false,
          "refTarget": null
        }
      ]
    },
    {
      "key": "photo",
      "displayName": "Photo",
      "pluralDisplayName": "Photos",
      "titleField": "title",
      "slugPolicy": "optional",
      "enabled": true,
      "fields": [
        {
          "key": "title",
          "type": "string",
          "required": false,
          "indexed": true,
          "refTarget": null
        },
        {
          "key": "caption",
          "type": "string",
          "required": false,
          "indexed": false,
          "refTarget": null
        },
        {
          "key": "album",
          "type": "ref",
          "required": true,
          "indexed": false,
          "refTarget": "album"
        },
        {
          "key": "sortOrder",
          "type": "int",
          "required": false,
          "indexed": true,
          "refTarget": null
        },
        {
          "key": "takenAt",
          "type": "datetime",
          "required": false,
          "indexed": false,
          "refTarget": null
        },
        {
          "key": "media",
          "type": "media-ref",
          "required": false,
          "indexed": false,
          "refTarget": null
        }
      ]
    },
    {
      "key": "page",
      "displayName": "Page",
      "pluralDisplayName": "Pages",
      "titleField": "title",
      "slugPolicy": "required",
      "enabled": true,
      "fields": [
        {
          "key": "title",
          "type": "string",
          "required": true,
          "indexed": true,
          "refTarget": null
        },
        {
          "key": "body",
          "type": "markdown",
          "required": false,
          "indexed": false,
          "refTarget": null
        }
      ]
    },
    {
      "key": "clinic_profile",
      "displayName": "Clinic profile",
      "pluralDisplayName": "Clinic profiles",
      "titleField": "name",
      "slugPolicy": "required",
      "enabled": true,
      "fields": [
        {
          "key": "name",
          "type": "string",
          "required": true,
          "indexed": true,
          "refTarget": null
        },
        {
          "key": "intro",
          "type": "markdown",
          "required": true,
          "indexed": false,
          "refTarget": null
        },
        {
          "key": "address",
          "type": "string",
          "required": false,
          "indexed": false,
          "refTarget": null
        },
        {
          "key": "telephone",
          "type": "string",
          "required": false,
          "indexed": false,
          "refTarget": null
        },
        {
          "key": "hours",
          "type": "markdown",
          "required": false,
          "indexed": false,
          "refTarget": null
        },
        {
          "key": "hero",
          "type": "media-ref",
          "required": false,
          "indexed": false,
          "refTarget": null
        }
      ]
    },
    {
      "key": "owner",
      "displayName": "Owner",
      "pluralDisplayName": "Owners",
      "titleField": "title",
      "slugPolicy": "optional",
      "enabled": true,
      "fields": [
        {
          "key": "title",
          "type": "string",
          "required": true,
          "indexed": true,
          "refTarget": null
        },
        {
          "key": "firstName",
          "type": "string",
          "required": false,
          "indexed": true,
          "refTarget": null
        },
        {
          "key": "lastName",
          "type": "string",
          "required": false,
          "indexed": true,
          "refTarget": null
        },
        {
          "key": "address",
          "type": "string",
          "required": false,
          "indexed": false,
          "refTarget": null
        },
        {
          "key": "city",
          "type": "string",
          "required": false,
          "indexed": true,
          "refTarget": null
        },
        {
          "key": "telephone",
          "type": "string",
          "required": false,
          "indexed": false,
          "refTarget": null
        },
        {
          "key": "email",
          "type": "string",
          "required": false,
          "indexed": false,
          "refTarget": null
        },
        {
          "key": "ownerPrincipalId",
          "type": "principal-ref",
          "required": false,
          "indexed": true,
          "refTarget": null
        }
      ]
    },
    {
      "key": "pet",
      "displayName": "Pet",
      "pluralDisplayName": "Pets",
      "titleField": "title",
      "slugPolicy": "optional",
      "enabled": true,
      "fields": [
        {
          "key": "title",
          "type": "string",
          "required": true,
          "indexed": true,
          "refTarget": null
        },
        {
          "key": "name",
          "type": "string",
          "required": false,
          "indexed": true,
          "refTarget": null
        },
        {
          "key": "petType",
          "type": "enum",
          "required": false,
          "indexed": true,
          "refTarget": null
        },
        {
          "key": "birthDate",
          "type": "datetime",
          "required": false,
          "indexed": false,
          "refTarget": null
        },
        {
          "key": "owner",
          "type": "ref",
          "required": true,
          "indexed": false,
          "refTarget": "owner"
        },
        {
          "key": "ownerPrincipalId",
          "type": "principal-ref",
          "required": false,
          "indexed": true,
          "refTarget": null
        },
        {
          "key": "notes",
          "type": "markdown",
          "required": false,
          "indexed": false,
          "refTarget": null
        },
        {
          "key": "photo",
          "type": "media-ref",
          "required": false,
          "indexed": false,
          "refTarget": null
        }
      ]
    },
    {
      "key": "vet",
      "displayName": "Vet",
      "pluralDisplayName": "Vets",
      "titleField": "title",
      "slugPolicy": "optional",
      "enabled": true,
      "fields": [
        {
          "key": "title",
          "type": "string",
          "required": true,
          "indexed": true,
          "refTarget": null
        },
        {
          "key": "firstName",
          "type": "string",
          "required": false,
          "indexed": true,
          "refTarget": null
        },
        {
          "key": "lastName",
          "type": "string",
          "required": false,
          "indexed": true,
          "refTarget": null
        },
        {
          "key": "specialty",
          "type": "enum",
          "required": false,
          "indexed": true,
          "refTarget": null
        },
        {
          "key": "bio",
          "type": "markdown",
          "required": false,
          "indexed": false,
          "refTarget": null
        },
        {
          "key": "photo",
          "type": "media-ref",
          "required": false,
          "indexed": false,
          "refTarget": null
        }
      ]
    },
    {
      "key": "visit",
      "displayName": "Visit",
      "pluralDisplayName": "Visits",
      "titleField": "title",
      "slugPolicy": "none",
      "enabled": true,
      "fields": [
        {
          "key": "title",
          "type": "string",
          "required": false,
          "indexed": true,
          "refTarget": null
        },
        {
          "key": "pet",
          "type": "ref",
          "required": true,
          "indexed": false,
          "refTarget": "pet"
        },
        {
          "key": "owner",
          "type": "ref",
          "required": false,
          "indexed": false,
          "refTarget": "owner"
        },
        {
          "key": "vet",
          "type": "ref",
          "required": false,
          "indexed": false,
          "refTarget": "vet"
        },
        {
          "key": "scheduledAt",
          "type": "datetime",
          "required": false,
          "indexed": true,
          "refTarget": null
        },
        {
          "key": "description",
          "type": "string",
          "required": false,
          "indexed": false,
          "refTarget": null
        },
        {
          "key": "visitKind",
          "type": "enum",
          "required": false,
          "indexed": true,
          "refTarget": null
        },
        {
          "key": "ownerPrincipalId",
          "type": "principal-ref",
          "required": false,
          "indexed": true,
          "refTarget": null
        }
      ]
    },
    {
      "key": "project",
      "displayName": "Project",
      "pluralDisplayName": "Projects",
      "titleField": "title",
      "slugPolicy": "required",
      "enabled": true,
      "fields": [
        {
          "key": "title",
          "type": "string",
          "required": true,
          "indexed": true,
          "refTarget": null
        },
        {
          "key": "summary",
          "type": "markdown",
          "required": false,
          "indexed": false,
          "refTarget": null
        },
        {
          "key": "cover",
          "type": "media-ref",
          "required": false,
          "indexed": false,
          "refTarget": null
        },
        {
          "key": "visibility",
          "type": "enum",
          "required": false,
          "indexed": true,
          "refTarget": null
        },
        {
          "key": "lifecycle",
          "type": "enum",
          "required": false,
          "indexed": true,
          "refTarget": null
        }
      ]
    },
    {
      "key": "issue",
      "displayName": "Issue",
      "pluralDisplayName": "Issues",
      "titleField": "title",
      "slugPolicy": "optional",
      "enabled": true,
      "fields": [
        {
          "key": "title",
          "type": "string",
          "required": true,
          "indexed": true,
          "refTarget": null
        },
        {
          "key": "project",
          "type": "ref",
          "required": true,
          "indexed": false,
          "refTarget": "project"
        },
        {
          "key": "milestone",
          "type": "ref",
          "required": false,
          "indexed": false,
          "refTarget": "milestone"
        },
        {
          "key": "body",
          "type": "markdown",
          "required": false,
          "indexed": false,
          "refTarget": null
        },
        {
          "key": "status",
          "type": "enum",
          "required": true,
          "indexed": true,
          "refTarget": null
        },
        {
          "key": "assigneePrincipalId",
          "type": "string",
          "required": false,
          "indexed": true,
          "refTarget": null
        },
        {
          "key": "sortOrder",
          "type": "int",
          "required": false,
          "indexed": true,
          "refTarget": null
        }
      ]
    },
    {
      "key": "milestone",
      "displayName": "Milestone",
      "pluralDisplayName": "Milestones",
      "titleField": "title",
      "slugPolicy": "required",
      "enabled": true,
      "fields": [
        {
          "key": "title",
          "type": "string",
          "required": true,
          "indexed": true,
          "refTarget": null
        },
        {
          "key": "project",
          "type": "ref",
          "required": true,
          "indexed": false,
          "refTarget": "project"
        },
        {
          "key": "description",
          "type": "markdown",
          "required": false,
          "indexed": false,
          "refTarget": null
        },
        {
          "key": "dueDate",
          "type": "datetime",
          "required": false,
          "indexed": false,
          "refTarget": null
        },
        {
          "key": "status",
          "type": "enum",
          "required": false,
          "indexed": true,
          "refTarget": null
        },
        {
          "key": "sortOrder",
          "type": "int",
          "required": false,
          "indexed": true,
          "refTarget": null
        }
      ]
    }
  ]
};

export const publicContentTypes: S["PublicContentTypeList"] = {
  "items": [
    {
      "key": "album",
      "displayName": "Album",
      "pluralDisplayName": "Albums",
      "titleField": "title",
      "fields": [
        {
          "key": "title",
          "type": "string",
          "required": true
        },
        {
          "key": "description",
          "type": "markdown",
          "required": false
        },
        {
          "key": "cover",
          "type": "media-ref",
          "required": false
        },
        {
          "key": "visibility",
          "type": "enum",
          "required": false
        },
        {
          "key": "sortMode",
          "type": "enum",
          "required": false
        }
      ]
    },
    {
      "key": "photo",
      "displayName": "Photo",
      "pluralDisplayName": "Photos",
      "titleField": "title",
      "fields": [
        {
          "key": "title",
          "type": "string",
          "required": false
        },
        {
          "key": "caption",
          "type": "string",
          "required": false
        },
        {
          "key": "album",
          "type": "ref",
          "required": true
        },
        {
          "key": "sortOrder",
          "type": "int",
          "required": false
        },
        {
          "key": "takenAt",
          "type": "datetime",
          "required": false
        },
        {
          "key": "media",
          "type": "media-ref",
          "required": false
        }
      ]
    },
    {
      "key": "page",
      "displayName": "Page",
      "pluralDisplayName": "Pages",
      "titleField": "title",
      "fields": [
        {
          "key": "title",
          "type": "string",
          "required": true
        },
        {
          "key": "body",
          "type": "markdown",
          "required": false
        }
      ]
    },
    {
      "key": "clinic_profile",
      "displayName": "Clinic profile",
      "pluralDisplayName": "Clinic profiles",
      "titleField": "name",
      "fields": [
        {
          "key": "name",
          "type": "string",
          "required": true
        },
        {
          "key": "intro",
          "type": "markdown",
          "required": true
        },
        {
          "key": "address",
          "type": "string",
          "required": false
        },
        {
          "key": "telephone",
          "type": "string",
          "required": false
        },
        {
          "key": "hours",
          "type": "markdown",
          "required": false
        },
        {
          "key": "hero",
          "type": "media-ref",
          "required": false
        }
      ]
    },
    {
      "key": "vet",
      "displayName": "Vet",
      "pluralDisplayName": "Vets",
      "titleField": "title",
      "fields": [
        {
          "key": "title",
          "type": "string",
          "required": true
        },
        {
          "key": "firstName",
          "type": "string",
          "required": false
        },
        {
          "key": "lastName",
          "type": "string",
          "required": false
        },
        {
          "key": "specialty",
          "type": "enum",
          "required": false
        },
        {
          "key": "bio",
          "type": "markdown",
          "required": false
        },
        {
          "key": "photo",
          "type": "media-ref",
          "required": false
        }
      ]
    },
    {
      "key": "project",
      "displayName": "Project",
      "pluralDisplayName": "Projects",
      "titleField": "title",
      "fields": [
        {
          "key": "title",
          "type": "string",
          "required": true
        },
        {
          "key": "summary",
          "type": "markdown",
          "required": false
        },
        {
          "key": "cover",
          "type": "media-ref",
          "required": false
        },
        {
          "key": "visibility",
          "type": "enum",
          "required": false
        },
        {
          "key": "lifecycle",
          "type": "enum",
          "required": false
        }
      ]
    },
    {
      "key": "milestone",
      "displayName": "Milestone",
      "pluralDisplayName": "Milestones",
      "titleField": "title",
      "fields": [
        {
          "key": "title",
          "type": "string",
          "required": true
        },
        {
          "key": "project",
          "type": "ref",
          "required": true
        },
        {
          "key": "description",
          "type": "markdown",
          "required": false
        },
        {
          "key": "dueDate",
          "type": "datetime",
          "required": false
        },
        {
          "key": "status",
          "type": "enum",
          "required": false
        },
        {
          "key": "sortOrder",
          "type": "int",
          "required": false
        }
      ]
    }
  ]
};

export const workEntries: S["WorkEntry"][] = [
  {
    "id": "30000000-0000-4000-8000-000000000001",
    "contentType": "album",
    "slug": "coast-light-2026",
    "publicationState": "published",
    "version": 2,
    "title": "Coast Light 2026",
    "payload": {
      "title": "Coast Light 2026",
      "description": "Sea and concrete.",
      "visibility": "public",
      "sortMode": "manual",
      "cover": "20000000-0000-4000-8000-000000000001"
    },
    "dirty": false,
    "publishedAt": "2026-09-20T00:01:00Z",
    "updatedAt": "2026-09-20T00:01:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000002",
    "contentType": "photo",
    "slug": "coast-harbour",
    "publicationState": "published",
    "version": 2,
    "title": "Harbour wall",
    "payload": {
      "title": "Harbour wall",
      "album": "30000000-0000-4000-8000-000000000001",
      "media": "20000000-0000-4000-8000-000000000001",
      "sortOrder": 10,
      "caption": "Tide against the harbour wall."
    },
    "dirty": false,
    "publishedAt": "2026-09-20T00:02:00Z",
    "updatedAt": "2026-09-20T00:02:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000003",
    "contentType": "photo",
    "slug": "coast-sun",
    "publicationState": "published",
    "version": 2,
    "title": "Late sun",
    "payload": {
      "title": "Late sun",
      "album": "30000000-0000-4000-8000-000000000001",
      "media": "20000000-0000-4000-8000-000000000002",
      "sortOrder": 20,
      "caption": "Late sun on the flats."
    },
    "dirty": false,
    "publishedAt": "2026-09-20T00:03:00Z",
    "updatedAt": "2026-09-20T00:03:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000004",
    "contentType": "photo",
    "slug": "coast-concrete",
    "publicationState": "published",
    "version": 2,
    "title": "Concrete edge",
    "payload": {
      "title": "Concrete edge",
      "album": "30000000-0000-4000-8000-000000000001",
      "media": "20000000-0000-4000-8000-000000000003",
      "sortOrder": 30,
      "caption": "A concrete edge catching spray."
    },
    "dirty": false,
    "publishedAt": "2026-09-20T00:04:00Z",
    "updatedAt": "2026-09-20T00:04:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000005",
    "contentType": "photo",
    "slug": "coast-salt",
    "publicationState": "published",
    "version": 2,
    "title": "Salt air",
    "payload": {
      "title": "Salt air",
      "album": "30000000-0000-4000-8000-000000000001",
      "media": "20000000-0000-4000-8000-000000000004",
      "sortOrder": 40
    },
    "dirty": false,
    "publishedAt": "2026-09-20T00:05:00Z",
    "updatedAt": "2026-09-20T00:05:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000006",
    "contentType": "photo",
    "slug": "coast-window",
    "publicationState": "published",
    "version": 2,
    "title": "Window light",
    "payload": {
      "title": "Window light",
      "album": "30000000-0000-4000-8000-000000000001",
      "media": "20000000-0000-4000-8000-000000000005",
      "sortOrder": 50
    },
    "dirty": false,
    "publishedAt": "2026-09-20T00:06:00Z",
    "updatedAt": "2026-09-20T00:06:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000007",
    "contentType": "photo",
    "slug": "coast-ferry",
    "publicationState": "published",
    "version": 2,
    "title": "Last ferry",
    "payload": {
      "title": "Last ferry",
      "album": "30000000-0000-4000-8000-000000000001",
      "media": "20000000-0000-4000-8000-000000000006",
      "sortOrder": 60
    },
    "dirty": false,
    "publishedAt": "2026-09-20T00:07:00Z",
    "updatedAt": "2026-09-20T00:07:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000008",
    "contentType": "album",
    "slug": "private-studio",
    "publicationState": "draft",
    "version": 1,
    "title": "Studio (unpublished)",
    "payload": {
      "title": "Studio (unpublished)",
      "visibility": "public",
      "sortMode": "manual"
    },
    "dirty": false,
    "publishedAt": null,
    "updatedAt": "2026-09-20T00:08:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000009",
    "contentType": "photo",
    "slug": "studio-polaroid",
    "publicationState": "draft",
    "version": 1,
    "title": "Polaroid test",
    "payload": {
      "title": "Polaroid test",
      "album": "30000000-0000-4000-8000-000000000008",
      "media": "20000000-0000-4000-8000-000000000007",
      "sortOrder": 10,
      "caption": "Not for the wall yet."
    },
    "dirty": false,
    "publishedAt": null,
    "updatedAt": "2026-09-20T00:09:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000010",
    "contentType": "photo",
    "slug": "studio-softbox",
    "publicationState": "draft",
    "version": 1,
    "title": "Softbox",
    "payload": {
      "title": "Softbox",
      "album": "30000000-0000-4000-8000-000000000008",
      "media": "20000000-0000-4000-8000-000000000008",
      "sortOrder": 20
    },
    "dirty": false,
    "publishedAt": null,
    "updatedAt": "2026-09-20T00:10:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000011",
    "contentType": "album",
    "slug": "unlisted-proof",
    "publicationState": "published",
    "version": 2,
    "title": "Unlisted proof",
    "payload": {
      "title": "Unlisted proof",
      "visibility": "unlisted",
      "sortMode": "manual"
    },
    "dirty": false,
    "publishedAt": "2026-09-20T00:11:00Z",
    "updatedAt": "2026-09-20T00:11:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000012",
    "contentType": "clinic_profile",
    "slug": "home",
    "publicationState": "published",
    "version": 2,
    "title": null,
    "payload": {
      "name": "Cedar Pet Clinic",
      "intro": "A small neighbourhood clinic for well animals.",
      "address": "14 Cedar Street",
      "telephone": "6085553000",
      "hours": "Mon–Fri 08:00–17:00"
    },
    "dirty": false,
    "publishedAt": "2026-09-20T00:12:00Z",
    "updatedAt": "2026-09-20T00:12:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000013",
    "contentType": "vet",
    "slug": "james-carter",
    "publicationState": "published",
    "version": 2,
    "title": "James Carter",
    "payload": {
      "title": "James Carter",
      "firstName": "James",
      "lastName": "Carter",
      "specialty": "radiology",
      "bio": "Imaging."
    },
    "dirty": false,
    "publishedAt": "2026-09-20T00:13:00Z",
    "updatedAt": "2026-09-20T00:13:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000014",
    "contentType": "vet",
    "slug": "helen-leary",
    "publicationState": "published",
    "version": 2,
    "title": "Helen Leary",
    "payload": {
      "title": "Helen Leary",
      "firstName": "Helen",
      "lastName": "Leary",
      "specialty": "dentistry",
      "bio": "Teeth."
    },
    "dirty": false,
    "publishedAt": "2026-09-20T00:14:00Z",
    "updatedAt": "2026-09-20T00:14:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000015",
    "contentType": "vet",
    "slug": "linda-douglas",
    "publicationState": "draft",
    "version": 1,
    "title": "Linda Douglas",
    "payload": {
      "title": "Linda Douglas",
      "firstName": "Linda",
      "lastName": "Douglas",
      "specialty": "surgery",
      "bio": "Draft surgeon."
    },
    "dirty": false,
    "publishedAt": null,
    "updatedAt": "2026-09-20T00:15:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000016",
    "contentType": "owner",
    "slug": "george-franklin",
    "publicationState": "published",
    "version": 2,
    "title": "George Franklin",
    "payload": {
      "title": "George Franklin",
      "firstName": "George",
      "lastName": "Franklin",
      "city": "Madison",
      "telephone": "6085551023",
      "ownerPrincipalId": "10000000-0000-4000-8000-000000000004"
    },
    "dirty": false,
    "publishedAt": "2026-09-20T00:16:00Z",
    "updatedAt": "2026-09-20T00:16:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000017",
    "contentType": "owner",
    "slug": "betty-davis",
    "publicationState": "published",
    "version": 2,
    "title": "Betty Davis",
    "payload": {
      "title": "Betty Davis",
      "firstName": "Betty",
      "lastName": "Davis",
      "city": "Madison"
    },
    "dirty": false,
    "publishedAt": "2026-09-20T00:17:00Z",
    "updatedAt": "2026-09-20T00:17:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000018",
    "contentType": "owner",
    "slug": "eduardo-rodriquez",
    "publicationState": "published",
    "version": 2,
    "title": "Eduardo Rodriquez",
    "payload": {
      "title": "Eduardo Rodriquez",
      "firstName": "Eduardo",
      "lastName": "Rodriquez",
      "city": "McFarland"
    },
    "dirty": false,
    "publishedAt": "2026-09-20T00:18:00Z",
    "updatedAt": "2026-09-20T00:18:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000019",
    "contentType": "pet",
    "slug": "leo",
    "publicationState": "published",
    "version": 2,
    "title": "Leo",
    "payload": {
      "title": "Leo",
      "name": "Leo",
      "petType": "cat",
      "owner": "30000000-0000-4000-8000-000000000016",
      "ownerPrincipalId": "10000000-0000-4000-8000-000000000004"
    },
    "dirty": false,
    "publishedAt": "2026-09-20T00:19:00Z",
    "updatedAt": "2026-09-20T00:19:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000020",
    "contentType": "pet",
    "slug": "basil",
    "publicationState": "published",
    "version": 2,
    "title": "Basil",
    "payload": {
      "title": "Basil",
      "name": "Basil",
      "petType": "hamster",
      "owner": "30000000-0000-4000-8000-000000000017"
    },
    "dirty": false,
    "publishedAt": "2026-09-20T00:20:00Z",
    "updatedAt": "2026-09-20T00:20:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000021",
    "contentType": "pet",
    "slug": "jewel",
    "publicationState": "published",
    "version": 2,
    "title": "Jewel",
    "payload": {
      "title": "Jewel",
      "name": "Jewel",
      "petType": "dog",
      "owner": "30000000-0000-4000-8000-000000000018"
    },
    "dirty": false,
    "publishedAt": "2026-09-20T00:21:00Z",
    "updatedAt": "2026-09-20T00:21:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000022",
    "contentType": "visit",
    "slug": "leo-rabies",
    "publicationState": "published",
    "version": 2,
    "title": "Leo rabies shot",
    "payload": {
      "title": "Leo rabies shot",
      "pet": "30000000-0000-4000-8000-000000000019",
      "owner": "30000000-0000-4000-8000-000000000016",
      "vet": "30000000-0000-4000-8000-000000000013",
      "scheduledAt": "2026-03-01T10:00:00Z",
      "description": "rabies shot",
      "visitKind": "vaccine",
      "ownerPrincipalId": "10000000-0000-4000-8000-000000000004"
    },
    "dirty": false,
    "publishedAt": "2026-09-20T00:22:00Z",
    "updatedAt": "2026-09-20T00:22:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000023",
    "contentType": "visit",
    "slug": "leo-checkup",
    "publicationState": "draft",
    "version": 1,
    "title": "Leo checkup",
    "payload": {
      "title": "Leo checkup",
      "pet": "30000000-0000-4000-8000-000000000019",
      "owner": "30000000-0000-4000-8000-000000000016",
      "vet": "30000000-0000-4000-8000-000000000013",
      "scheduledAt": "2026-09-20T09:00:00Z",
      "description": "annual checkup",
      "visitKind": "checkup",
      "ownerPrincipalId": "10000000-0000-4000-8000-000000000004"
    },
    "dirty": false,
    "publishedAt": null,
    "updatedAt": "2026-09-20T00:23:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000024",
    "contentType": "project",
    "slug": "cms-scaffold",
    "publicationState": "published",
    "version": 2,
    "title": "CMS Scaffold",
    "payload": {
      "title": "CMS Scaffold",
      "summary": "Reusable CMS kernel with three surfaces.",
      "visibility": "public",
      "lifecycle": "active"
    },
    "dirty": false,
    "publishedAt": "2026-09-20T00:24:00Z",
    "updatedAt": "2026-09-20T00:24:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000025",
    "contentType": "project",
    "slug": "internal-ops",
    "publicationState": "published",
    "version": 2,
    "title": "Internal Ops",
    "payload": {
      "title": "Internal Ops",
      "summary": "Not for the public site.",
      "visibility": "private",
      "lifecycle": "active"
    },
    "dirty": false,
    "publishedAt": "2026-09-20T00:25:00Z",
    "updatedAt": "2026-09-20T00:25:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000026",
    "contentType": "project",
    "slug": "draft-lab",
    "publicationState": "draft",
    "version": 1,
    "title": "Draft Lab",
    "payload": {
      "title": "Draft Lab",
      "summary": "Still a draft.",
      "visibility": "public",
      "lifecycle": "active"
    },
    "dirty": false,
    "publishedAt": null,
    "updatedAt": "2026-09-20T00:26:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000027",
    "contentType": "milestone",
    "slug": "m1-specs",
    "publicationState": "published",
    "version": 2,
    "title": "M1 Specs",
    "payload": {
      "title": "M1 Specs",
      "project": "30000000-0000-4000-8000-000000000024",
      "status": "planned",
      "sortOrder": 10
    },
    "dirty": false,
    "publishedAt": "2026-09-20T00:27:00Z",
    "updatedAt": "2026-09-20T00:27:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000028",
    "contentType": "milestone",
    "slug": "m2-kernel",
    "publicationState": "published",
    "version": 2,
    "title": "M2 Kernel",
    "payload": {
      "title": "M2 Kernel",
      "project": "30000000-0000-4000-8000-000000000024",
      "status": "planned",
      "sortOrder": 20
    },
    "dirty": false,
    "publishedAt": "2026-09-20T00:28:00Z",
    "updatedAt": "2026-09-20T00:28:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000029",
    "contentType": "milestone",
    "slug": "m3-surfaces",
    "publicationState": "published",
    "version": 2,
    "title": "M3 Surfaces",
    "payload": {
      "title": "M3 Surfaces",
      "project": "30000000-0000-4000-8000-000000000024",
      "status": "planned",
      "sortOrder": 30
    },
    "dirty": false,
    "publishedAt": "2026-09-20T00:29:00Z",
    "updatedAt": "2026-09-20T00:29:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000030",
    "contentType": "issue",
    "slug": "write-album-pack",
    "publicationState": "draft",
    "version": 1,
    "title": "Write album pack",
    "payload": {
      "title": "Write album pack",
      "project": "30000000-0000-4000-8000-000000000024",
      "milestone": "30000000-0000-4000-8000-000000000027",
      "status": "done",
      "sortOrder": 10
    },
    "dirty": false,
    "publishedAt": null,
    "updatedAt": "2026-09-20T00:30:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000031",
    "contentType": "issue",
    "slug": "visit-timeline-query",
    "publicationState": "draft",
    "version": 1,
    "title": "Visit timeline query",
    "payload": {
      "title": "Visit timeline query",
      "project": "30000000-0000-4000-8000-000000000024",
      "status": "in_progress",
      "sortOrder": 20
    },
    "dirty": false,
    "publishedAt": null,
    "updatedAt": "2026-09-20T00:31:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000032",
    "contentType": "issue",
    "slug": "kanban-dnd",
    "publicationState": "draft",
    "version": 1,
    "title": "Kanban DnD",
    "payload": {
      "title": "Kanban DnD",
      "project": "30000000-0000-4000-8000-000000000024",
      "status": "ready",
      "sortOrder": 30
    },
    "dirty": false,
    "publishedAt": null,
    "updatedAt": "2026-09-20T00:32:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000033",
    "contentType": "issue",
    "slug": "private-project-leak-test",
    "publicationState": "draft",
    "version": 1,
    "title": "Private project leak test",
    "payload": {
      "title": "Private project leak test",
      "project": "30000000-0000-4000-8000-000000000024",
      "status": "backlog",
      "sortOrder": 40
    },
    "dirty": false,
    "publishedAt": null,
    "updatedAt": "2026-09-20T00:33:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000034",
    "contentType": "issue",
    "slug": "secret-infra-task",
    "publicationState": "draft",
    "version": 1,
    "title": "Secret infra task",
    "payload": {
      "title": "Secret infra task",
      "project": "30000000-0000-4000-8000-000000000025",
      "status": "backlog",
      "sortOrder": 10
    },
    "dirty": false,
    "publishedAt": null,
    "updatedAt": "2026-09-20T00:34:00Z"
  }
];

export const publicEntries: S["PublicEntry"][] = [
  {
    "id": "30000000-0000-4000-8000-000000000001",
    "contentType": "album",
    "slug": "coast-light-2026",
    "title": "Coast Light 2026",
    "payload": {
      "title": "Coast Light 2026",
      "description": "Sea and concrete.",
      "visibility": "public",
      "sortMode": "manual",
      "cover": {
        "id": "20000000-0000-4000-8000-000000000001",
        "mediaId": "20000000-0000-4000-8000-000000000001",
        "title": "Harbour wall",
        "altText": "Harbour wall",
        "contentType": "image/png",
        "byteSize": 1240,
        "width": 64,
        "height": 64,
        "variants": {
          "original": {
            "url": "/api/v1/public/media/20000000-0000-4000-8000-000000000001/file/original",
            "width": 64,
            "height": 64,
            "contentType": "image/png",
            "byteSize": 1240
          },
          "thumbnail": {
            "url": "/api/v1/public/media/20000000-0000-4000-8000-000000000001/file/thumbnail",
            "width": 64,
            "height": 64,
            "contentType": "image/jpeg",
            "byteSize": 1432
          },
          "web": {
            "url": "/api/v1/public/media/20000000-0000-4000-8000-000000000001/file/web",
            "width": 64,
            "height": 64,
            "contentType": "image/jpeg",
            "byteSize": 1432
          }
        }
      }
    },
    "publishedAt": "2026-09-20T00:01:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000002",
    "contentType": "photo",
    "slug": "coast-harbour",
    "title": "Harbour wall",
    "payload": {
      "title": "Harbour wall",
      "album": "30000000-0000-4000-8000-000000000001",
      "media": {
        "id": "20000000-0000-4000-8000-000000000001",
        "mediaId": "20000000-0000-4000-8000-000000000001",
        "title": "Harbour wall",
        "altText": "Harbour wall",
        "contentType": "image/png",
        "byteSize": 1240,
        "width": 64,
        "height": 64,
        "variants": {
          "original": {
            "url": "/api/v1/public/media/20000000-0000-4000-8000-000000000001/file/original",
            "width": 64,
            "height": 64,
            "contentType": "image/png",
            "byteSize": 1240
          },
          "thumbnail": {
            "url": "/api/v1/public/media/20000000-0000-4000-8000-000000000001/file/thumbnail",
            "width": 64,
            "height": 64,
            "contentType": "image/jpeg",
            "byteSize": 1432
          },
          "web": {
            "url": "/api/v1/public/media/20000000-0000-4000-8000-000000000001/file/web",
            "width": 64,
            "height": 64,
            "contentType": "image/jpeg",
            "byteSize": 1432
          }
        }
      },
      "sortOrder": 10,
      "caption": "Tide against the harbour wall."
    },
    "publishedAt": "2026-09-20T00:02:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000003",
    "contentType": "photo",
    "slug": "coast-sun",
    "title": "Late sun",
    "payload": {
      "title": "Late sun",
      "album": "30000000-0000-4000-8000-000000000001",
      "media": {
        "id": "20000000-0000-4000-8000-000000000002",
        "mediaId": "20000000-0000-4000-8000-000000000002",
        "title": "Late sun",
        "altText": "Late sun",
        "contentType": "image/png",
        "byteSize": 1240,
        "width": 64,
        "height": 64,
        "variants": {
          "original": {
            "url": "/api/v1/public/media/20000000-0000-4000-8000-000000000002/file/original",
            "width": 64,
            "height": 64,
            "contentType": "image/png",
            "byteSize": 1240
          },
          "thumbnail": {
            "url": "/api/v1/public/media/20000000-0000-4000-8000-000000000002/file/thumbnail",
            "width": 64,
            "height": 64,
            "contentType": "image/jpeg",
            "byteSize": 1432
          },
          "web": {
            "url": "/api/v1/public/media/20000000-0000-4000-8000-000000000002/file/web",
            "width": 64,
            "height": 64,
            "contentType": "image/jpeg",
            "byteSize": 1432
          }
        }
      },
      "sortOrder": 20,
      "caption": "Late sun on the flats."
    },
    "publishedAt": "2026-09-20T00:03:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000004",
    "contentType": "photo",
    "slug": "coast-concrete",
    "title": "Concrete edge",
    "payload": {
      "title": "Concrete edge",
      "album": "30000000-0000-4000-8000-000000000001",
      "media": {
        "id": "20000000-0000-4000-8000-000000000003",
        "mediaId": "20000000-0000-4000-8000-000000000003",
        "title": "Concrete edge",
        "altText": "Concrete edge",
        "contentType": "image/png",
        "byteSize": 1240,
        "width": 64,
        "height": 64,
        "variants": {
          "original": {
            "url": "/api/v1/public/media/20000000-0000-4000-8000-000000000003/file/original",
            "width": 64,
            "height": 64,
            "contentType": "image/png",
            "byteSize": 1240
          },
          "thumbnail": {
            "url": "/api/v1/public/media/20000000-0000-4000-8000-000000000003/file/thumbnail",
            "width": 64,
            "height": 64,
            "contentType": "image/jpeg",
            "byteSize": 1432
          },
          "web": {
            "url": "/api/v1/public/media/20000000-0000-4000-8000-000000000003/file/web",
            "width": 64,
            "height": 64,
            "contentType": "image/jpeg",
            "byteSize": 1432
          }
        }
      },
      "sortOrder": 30,
      "caption": "A concrete edge catching spray."
    },
    "publishedAt": "2026-09-20T00:04:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000005",
    "contentType": "photo",
    "slug": "coast-salt",
    "title": "Salt air",
    "payload": {
      "title": "Salt air",
      "album": "30000000-0000-4000-8000-000000000001",
      "media": {
        "id": "20000000-0000-4000-8000-000000000004",
        "mediaId": "20000000-0000-4000-8000-000000000004",
        "title": "Salt air",
        "altText": "Salt air",
        "contentType": "image/png",
        "byteSize": 1240,
        "width": 64,
        "height": 64,
        "variants": {
          "original": {
            "url": "/api/v1/public/media/20000000-0000-4000-8000-000000000004/file/original",
            "width": 64,
            "height": 64,
            "contentType": "image/png",
            "byteSize": 1240
          },
          "thumbnail": {
            "url": "/api/v1/public/media/20000000-0000-4000-8000-000000000004/file/thumbnail",
            "width": 64,
            "height": 64,
            "contentType": "image/jpeg",
            "byteSize": 1432
          },
          "web": {
            "url": "/api/v1/public/media/20000000-0000-4000-8000-000000000004/file/web",
            "width": 64,
            "height": 64,
            "contentType": "image/jpeg",
            "byteSize": 1432
          }
        }
      },
      "sortOrder": 40
    },
    "publishedAt": "2026-09-20T00:05:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000006",
    "contentType": "photo",
    "slug": "coast-window",
    "title": "Window light",
    "payload": {
      "title": "Window light",
      "album": "30000000-0000-4000-8000-000000000001",
      "media": {
        "id": "20000000-0000-4000-8000-000000000005",
        "mediaId": "20000000-0000-4000-8000-000000000005",
        "title": "Window light",
        "altText": "Window light",
        "contentType": "image/png",
        "byteSize": 1240,
        "width": 64,
        "height": 64,
        "variants": {
          "original": {
            "url": "/api/v1/public/media/20000000-0000-4000-8000-000000000005/file/original",
            "width": 64,
            "height": 64,
            "contentType": "image/png",
            "byteSize": 1240
          },
          "thumbnail": {
            "url": "/api/v1/public/media/20000000-0000-4000-8000-000000000005/file/thumbnail",
            "width": 64,
            "height": 64,
            "contentType": "image/jpeg",
            "byteSize": 1432
          },
          "web": {
            "url": "/api/v1/public/media/20000000-0000-4000-8000-000000000005/file/web",
            "width": 64,
            "height": 64,
            "contentType": "image/jpeg",
            "byteSize": 1432
          }
        }
      },
      "sortOrder": 50
    },
    "publishedAt": "2026-09-20T00:06:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000007",
    "contentType": "photo",
    "slug": "coast-ferry",
    "title": "Last ferry",
    "payload": {
      "title": "Last ferry",
      "album": "30000000-0000-4000-8000-000000000001",
      "media": {
        "id": "20000000-0000-4000-8000-000000000006",
        "mediaId": "20000000-0000-4000-8000-000000000006",
        "title": "Last ferry",
        "altText": "Last ferry",
        "contentType": "image/png",
        "byteSize": 1240,
        "width": 64,
        "height": 64,
        "variants": {
          "original": {
            "url": "/api/v1/public/media/20000000-0000-4000-8000-000000000006/file/original",
            "width": 64,
            "height": 64,
            "contentType": "image/png",
            "byteSize": 1240
          },
          "thumbnail": {
            "url": "/api/v1/public/media/20000000-0000-4000-8000-000000000006/file/thumbnail",
            "width": 64,
            "height": 64,
            "contentType": "image/jpeg",
            "byteSize": 1432
          },
          "web": {
            "url": "/api/v1/public/media/20000000-0000-4000-8000-000000000006/file/web",
            "width": 64,
            "height": 64,
            "contentType": "image/jpeg",
            "byteSize": 1432
          }
        }
      },
      "sortOrder": 60
    },
    "publishedAt": "2026-09-20T00:07:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000011",
    "contentType": "album",
    "slug": "unlisted-proof",
    "title": "Unlisted proof",
    "payload": {
      "title": "Unlisted proof",
      "visibility": "unlisted",
      "sortMode": "manual"
    },
    "publishedAt": "2026-09-20T00:11:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000012",
    "contentType": "clinic_profile",
    "slug": "home",
    "title": "Cedar Pet Clinic",
    "payload": {
      "name": "Cedar Pet Clinic",
      "intro": "A small neighbourhood clinic for well animals.",
      "address": "14 Cedar Street",
      "telephone": "6085553000",
      "hours": "Mon–Fri 08:00–17:00"
    },
    "publishedAt": "2026-09-20T00:12:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000013",
    "contentType": "vet",
    "slug": "james-carter",
    "title": "James Carter",
    "payload": {
      "title": "James Carter",
      "firstName": "James",
      "lastName": "Carter",
      "specialty": "radiology",
      "bio": "Imaging."
    },
    "publishedAt": "2026-09-20T00:13:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000014",
    "contentType": "vet",
    "slug": "helen-leary",
    "title": "Helen Leary",
    "payload": {
      "title": "Helen Leary",
      "firstName": "Helen",
      "lastName": "Leary",
      "specialty": "dentistry",
      "bio": "Teeth."
    },
    "publishedAt": "2026-09-20T00:14:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000024",
    "contentType": "project",
    "slug": "cms-scaffold",
    "title": "CMS Scaffold",
    "payload": {
      "title": "CMS Scaffold",
      "summary": "Reusable CMS kernel with three surfaces.",
      "visibility": "public",
      "lifecycle": "active"
    },
    "publishedAt": "2026-09-20T00:24:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000027",
    "contentType": "milestone",
    "slug": "m1-specs",
    "title": "M1 Specs",
    "payload": {
      "title": "M1 Specs",
      "project": "30000000-0000-4000-8000-000000000024",
      "status": "planned",
      "sortOrder": 10
    },
    "publishedAt": "2026-09-20T00:27:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000028",
    "contentType": "milestone",
    "slug": "m2-kernel",
    "title": "M2 Kernel",
    "payload": {
      "title": "M2 Kernel",
      "project": "30000000-0000-4000-8000-000000000024",
      "status": "planned",
      "sortOrder": 20
    },
    "publishedAt": "2026-09-20T00:28:00Z"
  },
  {
    "id": "30000000-0000-4000-8000-000000000029",
    "contentType": "milestone",
    "slug": "m3-surfaces",
    "title": "M3 Surfaces",
    "payload": {
      "title": "M3 Surfaces",
      "project": "30000000-0000-4000-8000-000000000024",
      "status": "planned",
      "sortOrder": 30
    },
    "publishedAt": "2026-09-20T00:29:00Z"
  }
];

export const mediaAssets: S["MediaAssetList"] = {
  "items": [
    {
      "id": "20000000-0000-4000-8000-000000000008",
      "mediaId": "20000000-0000-4000-8000-000000000008",
      "title": "Softbox",
      "altText": "Softbox",
      "contentType": "image/png",
      "byteSize": 1240,
      "width": 64,
      "height": 64,
      "variants": {
        "original": {
          "url": "/api/v1/media/20000000-0000-4000-8000-000000000008/file/original",
          "width": 64,
          "height": 64,
          "contentType": "image/png",
          "byteSize": 1240
        },
        "thumbnail": {
          "url": "/api/v1/media/20000000-0000-4000-8000-000000000008/file/thumbnail",
          "width": 64,
          "height": 64,
          "contentType": "image/jpeg",
          "byteSize": 1432
        },
        "web": {
          "url": "/api/v1/media/20000000-0000-4000-8000-000000000008/file/web",
          "width": 64,
          "height": 64,
          "contentType": "image/jpeg",
          "byteSize": 1432
        }
      }
    },
    {
      "id": "20000000-0000-4000-8000-000000000007",
      "mediaId": "20000000-0000-4000-8000-000000000007",
      "title": "Polaroid test",
      "altText": "Polaroid test",
      "contentType": "image/png",
      "byteSize": 1240,
      "width": 64,
      "height": 64,
      "variants": {
        "original": {
          "url": "/api/v1/media/20000000-0000-4000-8000-000000000007/file/original",
          "width": 64,
          "height": 64,
          "contentType": "image/png",
          "byteSize": 1240
        },
        "thumbnail": {
          "url": "/api/v1/media/20000000-0000-4000-8000-000000000007/file/thumbnail",
          "width": 64,
          "height": 64,
          "contentType": "image/jpeg",
          "byteSize": 1432
        },
        "web": {
          "url": "/api/v1/media/20000000-0000-4000-8000-000000000007/file/web",
          "width": 64,
          "height": 64,
          "contentType": "image/jpeg",
          "byteSize": 1432
        }
      }
    },
    {
      "id": "20000000-0000-4000-8000-000000000006",
      "mediaId": "20000000-0000-4000-8000-000000000006",
      "title": "Last ferry",
      "altText": "Last ferry",
      "contentType": "image/png",
      "byteSize": 1240,
      "width": 64,
      "height": 64,
      "variants": {
        "original": {
          "url": "/api/v1/media/20000000-0000-4000-8000-000000000006/file/original",
          "width": 64,
          "height": 64,
          "contentType": "image/png",
          "byteSize": 1240
        },
        "thumbnail": {
          "url": "/api/v1/media/20000000-0000-4000-8000-000000000006/file/thumbnail",
          "width": 64,
          "height": 64,
          "contentType": "image/jpeg",
          "byteSize": 1432
        },
        "web": {
          "url": "/api/v1/media/20000000-0000-4000-8000-000000000006/file/web",
          "width": 64,
          "height": 64,
          "contentType": "image/jpeg",
          "byteSize": 1432
        }
      }
    },
    {
      "id": "20000000-0000-4000-8000-000000000005",
      "mediaId": "20000000-0000-4000-8000-000000000005",
      "title": "Window light",
      "altText": "Window light",
      "contentType": "image/png",
      "byteSize": 1240,
      "width": 64,
      "height": 64,
      "variants": {
        "original": {
          "url": "/api/v1/media/20000000-0000-4000-8000-000000000005/file/original",
          "width": 64,
          "height": 64,
          "contentType": "image/png",
          "byteSize": 1240
        },
        "thumbnail": {
          "url": "/api/v1/media/20000000-0000-4000-8000-000000000005/file/thumbnail",
          "width": 64,
          "height": 64,
          "contentType": "image/jpeg",
          "byteSize": 1432
        },
        "web": {
          "url": "/api/v1/media/20000000-0000-4000-8000-000000000005/file/web",
          "width": 64,
          "height": 64,
          "contentType": "image/jpeg",
          "byteSize": 1432
        }
      }
    },
    {
      "id": "20000000-0000-4000-8000-000000000004",
      "mediaId": "20000000-0000-4000-8000-000000000004",
      "title": "Salt air",
      "altText": "Salt air",
      "contentType": "image/png",
      "byteSize": 1240,
      "width": 64,
      "height": 64,
      "variants": {
        "original": {
          "url": "/api/v1/media/20000000-0000-4000-8000-000000000004/file/original",
          "width": 64,
          "height": 64,
          "contentType": "image/png",
          "byteSize": 1240
        },
        "thumbnail": {
          "url": "/api/v1/media/20000000-0000-4000-8000-000000000004/file/thumbnail",
          "width": 64,
          "height": 64,
          "contentType": "image/jpeg",
          "byteSize": 1432
        },
        "web": {
          "url": "/api/v1/media/20000000-0000-4000-8000-000000000004/file/web",
          "width": 64,
          "height": 64,
          "contentType": "image/jpeg",
          "byteSize": 1432
        }
      }
    },
    {
      "id": "20000000-0000-4000-8000-000000000003",
      "mediaId": "20000000-0000-4000-8000-000000000003",
      "title": "Concrete edge",
      "altText": "Concrete edge",
      "contentType": "image/png",
      "byteSize": 1240,
      "width": 64,
      "height": 64,
      "variants": {
        "original": {
          "url": "/api/v1/media/20000000-0000-4000-8000-000000000003/file/original",
          "width": 64,
          "height": 64,
          "contentType": "image/png",
          "byteSize": 1240
        },
        "thumbnail": {
          "url": "/api/v1/media/20000000-0000-4000-8000-000000000003/file/thumbnail",
          "width": 64,
          "height": 64,
          "contentType": "image/jpeg",
          "byteSize": 1432
        },
        "web": {
          "url": "/api/v1/media/20000000-0000-4000-8000-000000000003/file/web",
          "width": 64,
          "height": 64,
          "contentType": "image/jpeg",
          "byteSize": 1432
        }
      }
    },
    {
      "id": "20000000-0000-4000-8000-000000000002",
      "mediaId": "20000000-0000-4000-8000-000000000002",
      "title": "Late sun",
      "altText": "Late sun",
      "contentType": "image/png",
      "byteSize": 1240,
      "width": 64,
      "height": 64,
      "variants": {
        "original": {
          "url": "/api/v1/media/20000000-0000-4000-8000-000000000002/file/original",
          "width": 64,
          "height": 64,
          "contentType": "image/png",
          "byteSize": 1240
        },
        "thumbnail": {
          "url": "/api/v1/media/20000000-0000-4000-8000-000000000002/file/thumbnail",
          "width": 64,
          "height": 64,
          "contentType": "image/jpeg",
          "byteSize": 1432
        },
        "web": {
          "url": "/api/v1/media/20000000-0000-4000-8000-000000000002/file/web",
          "width": 64,
          "height": 64,
          "contentType": "image/jpeg",
          "byteSize": 1432
        }
      }
    },
    {
      "id": "20000000-0000-4000-8000-000000000001",
      "mediaId": "20000000-0000-4000-8000-000000000001",
      "title": "Harbour wall",
      "altText": "Harbour wall",
      "contentType": "image/png",
      "byteSize": 1240,
      "width": 64,
      "height": 64,
      "variants": {
        "original": {
          "url": "/api/v1/media/20000000-0000-4000-8000-000000000001/file/original",
          "width": 64,
          "height": 64,
          "contentType": "image/png",
          "byteSize": 1240
        },
        "thumbnail": {
          "url": "/api/v1/media/20000000-0000-4000-8000-000000000001/file/thumbnail",
          "width": 64,
          "height": 64,
          "contentType": "image/jpeg",
          "byteSize": 1432
        },
        "web": {
          "url": "/api/v1/media/20000000-0000-4000-8000-000000000001/file/web",
          "width": 64,
          "height": 64,
          "contentType": "image/jpeg",
          "byteSize": 1432
        }
      }
    }
  ]
};

export const mediaQuota: S["MediaQuota"] = {
  "usedFiles": 8,
  "usedBytes": 32832,
  "maxFiles": 2000,
  "maxLibraryBytes": 1073741824,
  "maxFileBytes": 15728640
};
