// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentStatusKind = { "kind": "idle" } | { "kind": "busy", task: string | null, } | { "kind": "error", message: string, };
