// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StreamId } from "./StreamId";

/**
 * AI completion stream (§3.2). Cancellable mid-stream by the frontend.
 */
export type AiChunk = { "kind": "start", stream_id: StreamId, } | { "kind": "text", stream_id: StreamId, delta: string, } | { "kind": "done", stream_id: StreamId, } | { "kind": "error", stream_id: StreamId, message: string, } | { "kind": "cancelled", stream_id: StreamId, };
