// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * D-9: Obsidian-compatible `^block-id`. Stored without the caret.
 */
export type BlockId = string;
