// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EdgeId } from "./EdgeId";
import type { EdgeKind } from "./EdgeKind";
import type { NodeId } from "./NodeId";

export type Edge = { id: EdgeId, from: NodeId, to: NodeId, kind: EdgeKind, };
