// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentStatusKind } from "./AgentStatusKind";
import type { EdgeId } from "./EdgeId";
import type { FsChangeKind } from "./FsChangeKind";
import type { NodeId } from "./NodeId";
import type { PluginId } from "./PluginId";
import type { SessionId } from "./SessionId";

export type Event = { "kind": "fs_changed", path: string, change: FsChangeKind, } | { "kind": "agent_status", session_id: SessionId, status: AgentStatusKind, } | { "kind": "pty_exited", session_id: SessionId, exit_code: number | null, } | { "kind": "node_changed", node_id: NodeId, } | { "kind": "edge_changed", edge_id: EdgeId, } | { "kind": "plugin_event", plugin_id: PluginId, topic: string, payload: unknown, };
