// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * §12.3: v1 publicly opens only the three extension points needed to
 * build Inbox (D2). Other points are recorded but not callable in v1.
 */
export type ExtensionPoint = "ui_panel" | "event_subscription" | "mcp_backend";
