// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionId } from "./SessionId";
import type { TombstoneSubject } from "./TombstoneSubject";

export type NodeKind = { "type": "document", path: string, } | { "type": "terminal", session_id: SessionId, } | { "type": "tombstone", reason: string, was: TombstoneSubject, };
