// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeId } from "./NodeId";
import type { NodeKind } from "./NodeKind";

export type Node = { id: NodeId, kind: NodeKind, x: number, y: number, w: number, h: number, group: string | null, };
