// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Origin = { "kind": "user" } | { "kind": "ai" } | { "kind": "remote" } | { "kind": "plugin", id: string, };
