// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpBackend } from "./McpBackend";
import type { PluginId } from "./PluginId";
import type { PluginPermission } from "./PluginPermission";

export type PluginManifest = { id: PluginId, name: string, version: string, 
/**
 * Path (relative to plugin dir) to the frontend entry bundle.
 */
frontend: string, mcp: McpBackend | null, 
/**
 * `plugin:<id>:<topic>` channels this plugin subscribes to (D-11).
 */
subscribes: Array<string>, 
/**
 * Declared upfront; write categories still pass the approve gate at runtime.
 */
permissions: Array<PluginPermission>, };
