// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PluginPermission = "read_document" | "read_canvas" | "write_document" | "write_canvas" | "inject_command";
