// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionId } from "./SessionId";
import type { StreamId } from "./StreamId";

export type PtyBatch = { stream_id: StreamId, session_id: SessionId, frames: Array<string>, dropped_old: number, };
