// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionId } from "./SessionId";

export type ReadCommand = { "kind": "open_file", path: string, } | { "kind": "read_document", path: string, } | { "kind": "list_nodes" } | { "kind": "list_edges" } | { "kind": "get_terminal_output", session_id: SessionId, last_n_lines: number | null, };
