// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeId } from "./NodeId";

/**
 * D-6 reserved type. The document loader (C2/E0 territory) reads
 * `run_in: <node-id>` frontmatter and materializes it into an `Edge {
 * kind: Triggers, from: doc_node, to: target_node }`. Runtime callers
 * (C4 Edge Router) only ever read materialized edges.
 */
export type RunInDirective = { doc_node: NodeId, target_node: NodeId, };
