// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionId } from "./SessionId";
import type { SessionState } from "./SessionState";

export type SessionMeta = { id: SessionId, cwd: string, cmd: string | null, shell: string, state: SessionState, last_activity_ms: bigint, };
