// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TombstoneSubject = { "type": "document", path: string, } | { "type": "terminal", cwd: string, cmd: string | null, shell: string | null, };
