// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EdgeId } from "./EdgeId";
import type { EdgeKind } from "./EdgeKind";
import type { NodeId } from "./NodeId";
import type { NodeKind } from "./NodeKind";
import type { Origin } from "./Origin";
import type { SessionId } from "./SessionId";

export type WriteCommand = { "kind": "spawn_pty", origin: Origin, cwd: string, cmd: string | null, shell: string | null, } | { "kind": "kill_pty", origin: Origin, session_id: SessionId, } | { "kind": "resize_pty", origin: Origin, session_id: SessionId, cols: number, rows: number, } | { "kind": "attach_session_view", origin: Origin, session_id: SessionId, } | { "kind": "detach_session_view", origin: Origin, session_id: SessionId, } | { "kind": "write_document", origin: Origin, path: string, content: string, expected_hash: string | null, } | { "kind": "create_node", origin: Origin, node_kind: NodeKind, x: number, y: number, } | { "kind": "update_node_position", origin: Origin, node_id: NodeId, x: number, y: number, } | { "kind": "delete_node", origin: Origin, node_id: NodeId, } | { "kind": "create_edge", origin: Origin, from: NodeId, to: NodeId, edge_kind: EdgeKind, } | { "kind": "delete_edge", origin: Origin, edge_id: EdgeId, } | { "kind": "inject_command", origin: Origin, target: SessionId, command: string, };
