/**
 * Start and stop a kith-runner process for E2E (W6 §5.1.2).
 * The toml is a complete §4.5 document: auth stays "api_key" (the harness text), including for
 * operator_personal, so RT-06 does not refuse the process when a CLI API-key variable is set.
 * operator_member_id is written only for operator_personal (INV-13). Paths are siblings, not nested (RT-07).
 */
import { spawn, type ChildProcess } from "node:child_process";
import { randomBytes } from "node:crypto";
import { appendFileSync, chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { ApiClient } from "../fixtures/kith.ts";
import { E2E_DIR, KITH_DIR } from "./paths.ts";
import { redactText } from "./redact.ts";
import { track } from "./server.ts";

export type RunnerQuota = "api_key" | "operator_personal";

export type RunnerInvocation = { argv: string[]; cwd: string; stdin: string };

export type RunnerHandle = {
  root: string;
  logFile: string;
  invocations(): RunnerInvocation[];
  stop(): Promise<number | null>;
  exited: Promise<number | null>;
};

export type StartRunnerOpts = {
  name: string;
  token: string;
  quota: RunnerQuota;
  operatorId?: string;
  rooms?: string[];
  timeoutS?: number;
  kithUrl?: string;
};

const live = new Set<ChildProcess>();
let exitHooked = false;

function hookExit(): void {
  if (exitHooked) return;
  exitHooked = true;
  process.on("exit", () => {
    for (const child of live) {
      if (child.pid !== undefined) {
        try {
          process.kill(-child.pid, "SIGKILL");
        } catch {
          // Already gone, or not a process-group leader.
        }
      }
    }
  });
}

function signalGroup(pid: number, signal: NodeJS.Signals): void {
  try {
    process.kill(-pid, signal);
  } catch (e) {
    const code = (e as NodeJS.ErrnoException).code;
    if (code === "ESRCH") return;
    try {
      process.kill(pid, signal);
    } catch (e2) {
      if ((e2 as NodeJS.ErrnoException).code !== "ESRCH") throw e2;
    }
  }
}

function tomlString(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n").replace(/\t/g, "\\t")}"`;
}

function runDir(): string {
  const dir = process.env.KITH_E2E_RUN_DIR;
  if (!dir) throw new Error("KITH_E2E_RUN_DIR is not set");
  return dir;
}

function runnerToml(opts: StartRunnerOpts, paths: { token: string; state: string; work: string; fakeCli: string }, kithUrl: string): string {
  const timeout = opts.timeoutS ?? 20;
  const lines = [
    "# Generated by e2e/harness/runner.ts (W6 §5.1.2).",
    `kith_url = ${tomlString(kithUrl)}`,
    `bot_token_file = ${tomlString(paths.token)}`,
    `state_dir = ${tomlString(paths.state)}`,
    `quota_class = ${tomlString(opts.quota)}`,
  ];
  if (opts.operatorId) lines.push(`operator_member_id = ${tomlString(opts.operatorId)}`);
  lines.push(`auth = "api_key"`);
  if (opts.rooms) lines.push(`rooms = [${opts.rooms.map(tomlString).join(", ")}]`);
  lines.push(
    "",
    "[adapter]",
    `kind = "command"`,
    `executable = ${tomlString(process.execPath)}`,
    `workdir = ${tomlString(paths.work)}`,
    `timeout_s = ${timeout}`,
    "",
    "[adapter.command]",
    `argv = [${tomlString(paths.fakeCli)}]`,
    "",
  );
  return lines.join("\n");
}

export async function startRunner(opts: StartRunnerOpts): Promise<RunnerHandle> {
  if (!/^[A-Za-z0-9_-]{1,32}$/.test(opts.name)) throw new Error("runner name must be 1-32 letters, digits, _ or -");
  if (opts.quota === "operator_personal" && !opts.operatorId) {
    throw new Error("operatorId is required when quota is operator_personal (INV-13)");
  }
  if (opts.rooms && (opts.rooms.length === 0 || opts.rooms.some((id) => !/^[A-Za-z0-9_-]{1,64}$/.test(id)))) {
    throw new Error("rooms must be a non-empty array of room ids");
  }
  const kithUrl = (opts.kithUrl ?? process.env.KITH_E2E_BASE_URL ?? "").replace(/\/+$/, "");
  if (kithUrl === "") throw new Error("kithUrl is required (KITH_E2E_BASE_URL is not set)");

  const rand = randomBytes(4).toString("hex");
  const root = join(runDir(), "state", `runner-${opts.name}-${rand}`);
  const work = join(root, "work");
  const state = join(root, "state");
  const cli = join(root, "cli");
  mkdirSync(work, { recursive: true });
  mkdirSync(state, { recursive: true, mode: 0o700 });
  chmodSync(state, 0o700);
  mkdirSync(cli, { recursive: true });
  const tokenFile = join(root, "token");
  writeFileSync(tokenFile, `${opts.token}\n`, { mode: 0o600 });
  chmodSync(tokenFile, 0o600);
  const fakeCli = join(E2E_DIR, "harness", "fake-cli.mjs");
  writeFileSync(join(root, "runner.toml"), runnerToml(opts, { token: tokenFile, state, work, fakeCli }, kithUrl), { mode: 0o600 });

  const logFile = join(runDir(), "files", `runner-${opts.name}-${rand}.log`);
  mkdirSync(join(runDir(), "files"), { recursive: true });
  writeFileSync(logFile, "");

  const child = spawn(process.execPath, [join(KITH_DIR, "runner", "main.ts"), "--config", join(root, "runner.toml")], {
    cwd: KITH_DIR,
    env: { ...process.env, KITH_FAKE_CLI_DIR: cli },
    detached: true,
    stdio: ["ignore", "pipe", "pipe"],
  });
  live.add(child);
  hookExit();

  let pending = "";
  child.stderr?.on("data", (chunk: Buffer) => {
    pending += chunk.toString("utf8");
    const lines = pending.split("\n");
    pending = lines.pop() ?? "";
    for (const line of lines) appendFileSync(logFile, redactText(line) + "\n");
  });
  child.stdout?.on("data", () => {
    // Drain so a quiet stdout cannot fill the pipe and stall the runner.
  });

  let done = false;
  let settle!: (code: number | null) => void;
  const exited = new Promise<number | null>((resolve) => {
    settle = resolve;
  });
  const finish = (code: number | null): void => {
    if (done) return;
    done = true;
    if (pending !== "") appendFileSync(logFile, redactText(pending) + "\n");
    pending = "";
    live.delete(child);
    settle(code);
  };
  child.once("error", () => finish(null));
  child.once("close", (code) => finish(code));
  track(child, join(runDir(), "state"));

  return {
    root,
    logFile,
    invocations(): RunnerInvocation[] {
      const file = join(cli, "invocations.jsonl");
      if (!existsSync(file)) return [];
      return readFileSync(file, "utf8")
        .split("\n")
        .filter((line) => line !== "")
        .map((line) => JSON.parse(line) as RunnerInvocation);
    },
    async stop(): Promise<number | null> {
      if (!done && child.pid !== undefined) {
        signalGroup(child.pid, "SIGTERM");
        const deadline = Date.now() + 10_000;
        while (!done && Date.now() < deadline) await new Promise((r) => setTimeout(r, 100));
        if (!done) signalGroup(child.pid, "SIGKILL");
      }
      return exited;
    },
    exited,
  };
}

/** Poll GET /api/agents/:id until `.agent.runtime_status` is `ok` (at most 15s). */
export async function waitForRunnerOnline(api: ApiClient, agentId: string): Promise<void> {
  const deadline = Date.now() + 15_000;
  let last = "missing";
  while (Date.now() < deadline) {
    const { json } = await api.call("GET", `/api/agents/${encodeURIComponent(agentId)}`);
    const agent = json && typeof json === "object" && json !== null && "agent" in json ? (json as { agent?: { runtime_status?: unknown } }).agent : undefined;
    if (agent?.runtime_status === "ok") return;
    last = typeof agent?.runtime_status === "string" ? agent.runtime_status : "missing";
    await new Promise((r) => setTimeout(r, 250));
  }
  throw new Error(`runner ${agentId} not online within 15s (last runtime_status: ${last})`);
}
