import { Box, Code2, Database, RefreshCw } from 'lucide-react'
import type { DashboardView } from '../../domain/schemas'
import { Button } from '../../components/ui/button'

export function InventorySummary({ data, refresh, refreshing }: { data: DashboardView; refresh: () => void; refreshing: boolean }) {
  const providers = { aws: { label: 'AWS', caption: 'Amazon Web Services' }, aliyun: { label: 'Aliyun', caption: '阿里雲' }, onprem: { label: 'On-premises', caption: '自建機房' } }
  return <section className="inventory-section" aria-label="可見資源摘要">
    <div className="section-heading"><h2>可見資源</h2><Button variant="ghost" size="sm" disabled={refreshing} onClick={refresh} aria-label="重新整理資源摘要"><RefreshCw size={14} className={refreshing ? 'spin' : ''} aria-hidden="true" />重新整理</Button></div>
    <dl className="stats-strip"><div><dt><Code2 size={16} aria-hidden="true" />應用</dt><dd>{data.applicationCount.toLocaleString()}<span>個</span></dd></div><div><dt><Box size={16} aria-hidden="true" />環境</dt><dd>{data.environmentCount.toLocaleString()}<span>個</span></dd></div><div><dt><Database size={16} aria-hidden="true" />配置項 CI</dt><dd>{data.ciCount.toLocaleString()}<span>筆</span></dd></div></dl>
    <div className="panel provider-panel"><div className="panel-title"><h3>資源來源</h3><span className="tag">最小示範資料集</span></div><table className="provider-table"><caption className="sr-only">目前授權範圍內的示範配置項，按來源統計</caption><thead><tr><th scope="col">Provider</th><th scope="col">可見配置項</th><th scope="col" className="distribution-heading">佔可見總數</th></tr></thead><tbody>{data.providers.map((entry) => <tr key={entry.provider}><th scope="row"><span className={`provider-monogram provider-${entry.provider}`} aria-hidden="true">{entry.provider === 'aws' ? 'A' : entry.provider === 'aliyun' ? '阿' : 'P'}</span><span>{providers[entry.provider].label}<small>{providers[entry.provider].caption}</small></span></th><td>{entry.count}<span className="muted"> 筆</span></td><td className="distribution-cell"><span className="distribution-track" aria-hidden="true"><span style={{ width: `${data.ciCount ? entry.count / data.ciCount * 100 : 0}%` }} /></span><span>{data.ciCount ? Math.round(entry.count / data.ciCount * 100) : 0}%</span></td></tr>)}</tbody></table><div className="data-caption">{data.ciCount === 0 ? '目前授權範圍沒有可見配置項。可切換示範身分探索其他工作區。' : '此摘要只包含目前身分可見的配置項，不代表真實基礎設施健康度。'}<span>資料時間：<time dateTime={data.dataAsOf}>{new Intl.DateTimeFormat('zh-TW', { year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', second: '2-digit', timeZone: 'UTC', hour12: false }).format(new Date(data.dataAsOf))} UTC</time></span></div></div>
  </section>
}
