// User-visible strings of web-front (zh-Hant). Key rule: docs/v2/waves/W0.md §4.6; W3 table: waves/W3.md §5.6.
export const copy = {
  "site.album": "相簿",
  "site.clinic": "診所",
  "site.projects": "專案",
  "skipLink": "跳到主要內容",
  "nav.label": "網站導覽",
  "nav.open": "開啟選單",
  "nav.menu": "選單",
  "nav.home": "首頁",
  "nav.albums": "相簿",
  "nav.vets": "獸醫",
  "nav.projects": "專案",
  "breadcrumb.label": "頁面路徑",
  "footer.name": "CMS Scaffold",
  "footer.selector": "回到選擇器",
  "selector.title": "CMS Scaffold",
  "selector.lead": "同一套內容核心，三個示範網站。",
  "selector.enter": "進入網站",
  "selector.footer": "示範用的公開網站，內容由作業台發布。",
  "selector.album.title": "個人相簿",
  "selector.album.body": "公開相簿與相片。",
  "selector.clinic.title": "寵物診所",
  "selector.clinic.body": "診所介紹與獸醫團隊。",
  "selector.projects.title": "專案",
  "selector.projects.body": "公開專案說明與里程碑。",
  "login.title": "會員登入",
  "logout.title": "正在登出…",
  "album.hero.title": "相簿",
  "album.hero.lead": "公開的相簿與相片。",
  "album.section": "相簿",
  "album.all": "全部相簿",
  "album.list.title": "全部相簿",
  "photo.fallbackTitle": "相片",
  "photo.noImage": "這張相片沒有公開的圖片。",
  "photo.inAlbum": "收錄於",
  "photo.takenAt": "拍攝日期",
  "photo.previous": "上一張",
  "photo.next": "下一張",
  "lightbox.close": "關閉",
  "lightbox.previous": "上一張",
  "lightbox.next": "下一張",
  "lightbox.counter": "{index} / {total}",
  "lightbox.openPage": "開啟單張頁面",
  "clinic.fallbackTitle": "寵物診所",
  "clinic.address": "地址",
  "clinic.telephone": "電話",
  "clinic.hours": "門診時間",
  "clinic.vets": "我們的獸醫",
  "clinic.vets.all": "全部獸醫",
  "vets.title": "我們的獸醫",
  "projects.hero.title": "專案",
  "projects.hero.lead": "公開專案的說明與里程碑。",
  "projects.section": "公開專案",
  "project.milestones": "里程碑",
  "project.milestones.all": "全部里程碑",
  "milestones.title": "{project} 的里程碑",
  "milestone.due": "預計完成",
  "enum.vet.specialty.general": "一般",
  "enum.vet.specialty.radiology": "放射科",
  "enum.vet.specialty.surgery": "外科",
  "enum.vet.specialty.dentistry": "牙科",
  "enum.project.lifecycle.active": "進行中",
  "enum.project.lifecycle.completed": "已完成",
  "enum.milestone.status.planned": "已規劃",
  "enum.milestone.status.reached": "已達成",
  "enum.milestone.status.missed": "未達成",
  "notfound": "找不到這個頁面",
  "notfound.body": "可能不存在，或尚未公開。",
  "notfound.home": "回到{site}首頁",
  "notfound.selector": "回到選擇器",
  "error.title": "暫時無法載入",
  "error.body": "請檢查網路連線後再試一次。",
  "error.retry": "重試",
  "loading": "載入中",
  "pager.label": "分頁",
  "pager.page": "第 {page} / {pages} 頁",
  "pager.previous": "上一頁",
  "pager.next": "下一頁",
  "empty.albums": "還沒有公開相簿",
  "empty.albums.body": "發布後會出現在這裡。",
  "empty.photos": "這本相簿還沒有照片",
  "empty.vets": "目前沒有可顯示的獸醫",
  "empty.projects": "還沒有公開專案",
  "empty.milestones": "這個專案還沒有公開里程碑",
} as const;

export type CopyKey = keyof typeof copy;
