// User-visible strings of web-front (zh-Hant). Key rule: docs/v2/waves/W0.md §4.6.
export const copy = {
  "site.cms": "CMS",
  "site.album": "相簿",
  "site.clinic": "診所",
  "site.projects": "專案",
  "nav.label": "網站導覽",
  "nav.login": "登入",
  "footer.name": "CMS Scaffold",
  "footer.selector": "回到選擇器",
  "selector.title": "CMS Scaffold",
  "selector.lead": "同一套公開面骨架，三個視圖包。",
  "selector.album.title": "個人相簿",
  "selector.album.body": "公開相簿與相片。",
  "selector.clinic.title": "寵物診所",
  "selector.clinic.body": "診所介紹與已發布獸醫。",
  "selector.projects.title": "專案",
  "selector.projects.body": "公開專案說明與里程碑。",
  "login.title": "會員登入",
  "album.title": "相簿",
  "album.all": "全部相簿",
  "album.notFound.title": "找不到相簿",
  "album.notFound.body": "這本相簿不存在或尚未發布。",
  "photo.fallbackTitle": "相片",
  "photo.noImage": "沒有公開圖片。",
  "photo.notFound.title": "找不到相片",
  "photo.notFound.body": "這張相片不存在或尚未發布。",
  "clinic.fallbackTitle": "寵物診所",
  "clinic.noProfile": "還沒有公開的診所介紹。",
  "clinic.vets": "獸醫",
  "projects.title": "專案",
  "project.milestones": "里程碑",
  "project.notFound.title": "找不到專案",
  "project.notFound.body": "這份專案不存在、未發布，或未公開。",
  "empty.albums": "還沒有公開相簿",
  "empty.albums.body": "發布後會出現在這裡。",
  "empty.photos": "這本相簿還沒有照片",
  "empty.vets": "目前沒有可顯示的獸醫",
  "empty.projects": "還沒有公開專案",
  "empty.milestones": "這個專案還沒有公開里程碑",
} as const;
