// User-visible strings of web-admin (zh-Hant). Key rule: docs/v2/waves/W0.md §4.6. Table: docs/v2/waves/W4.md §5.6.
export const copy = {
  "app.name": "Admin center",
  "login.title": "登入 Admin center",
  "forbidden.title": "沒有權限",
  "forbidden.body": "Admin center 只給平台治理。日常編輯請用 Back office。",

  "nav.overview": "總覽",
  "nav.types": "內容類型",
  "nav.roles": "角色與權限",
  "nav.principals": "使用者",
  "nav.audit": "審計",
  "nav.media": "媒體與儲存",
  "nav.settings": "設定",

  "common.yes": "是",
  "common.no": "否",
  "common.none": "—",
  "common.all": "全部",
  "common.cancel": "取消",
  "common.working": "處理中…",
  "common.clearFilters": "清除篩選",

  "status.forbidden.title": "沒有權限",
  "status.forbidden.body": "你的帳號沒有這個治理項目的權限。",
  "status.notFound.title": "找不到頁面",
  "status.notFound.body": "這個頁面或項目不存在。",
  "status.home": "回到總覽",

  "error.failed": "操作沒有完成，請再試一次。",
  "error.forbidden": "你沒有執行這個操作的權限。",
  "error.lastAdmin": "這個變更會讓系統沒有任何可用的管理員，已取消。",

  "confirm.phraseLabel": "請輸入「{phrase}」以確認",
  "password.body": "這是臨時密碼，只會顯示這一次。請用安全的方式交給對方；對方登入後要自行更改。",
  "password.copy": "複製密碼",
  "password.copied": "已複製",
  "password.done": "完成",

  "role.admin": "管理員",
  "role.operator": "營運",
  "role.editor": "編輯",
  "role.member": "會員",
  "role.anonymous": "訪客",

  "principal.status.active": "啟用中",
  "principal.status.disabled": "已停用",
  "principal.status.locked": "已鎖定",

  "surface.front": "公開網站",
  "surface.back": "Back office",
  "surface.admin": "Admin center",

  "overview.title": "總覽",
  "overview.lead": "類型啟停、角色與使用者、審計與儲存。日常編輯請用 Back office。",
  "overview.types": "內容類型",
  "overview.types.count": "{total} 個，{disabled} 個停用",
  "overview.types.link": "管理內容類型",
  "overview.principals": "使用者",
  "overview.principals.count": "{total} 位，{inactive} 位停用或鎖定",
  "overview.principals.link": "管理使用者",
  "overview.media": "媒體用量",
  "overview.media.usage": "{used} / {max}",
  "overview.media.link": "查看媒體與儲存",
  "overview.audit": "最近的治理事件",
  "overview.audit.link": "全部審計",
  "overview.audit.empty": "還沒有審計事件。",
  "overview.nothing": "你的帳號目前沒有任何治理項目的權限。",

  "types.title": "內容類型",
  "types.lead": "類型與欄位由種子定義；這裡只能檢視與啟用、停用。",
  "types.search": "搜尋類型",
  "types.tab.all": "全部",
  "types.tab.enabled": "啟用中",
  "types.tab.disabled": "已停用",
  "types.col.name": "名稱",
  "types.col.key": "代碼",
  "types.col.status": "狀態",
  "types.col.fields": "欄位數",
  "types.col.action": "操作",
  "types.enabled": "啟用中",
  "types.disabled": "已停用",
  "types.enable": "啟用",
  "types.disable": "停用",
  "types.noMatch": "沒有符合的類型",
  "types.none.title": "尚未載入 demo pack 種子",
  "types.none.body": "治理台可以使用，但 Front 與 Back 不會出現內容。",
  "types.disable.title": "停用「{name}」？",
  "types.disable.body": "停用後，公開網站會隱藏這個類型的內容，Back 也不能再新增或修改；資料不會刪除，之後可以再啟用。",
  "types.disable.confirm": "停用類型",
  "types.enable.title": "啟用「{name}」？",
  "types.enable.body": "啟用後，這個類型會回到 Back 與公開網站。",
  "types.enable.confirm": "啟用類型",
  "types.disabledToast": "已停用「{name}」",
  "types.enabledToast": "已啟用「{name}」",
  "type.settings": "類型設定",
  "type.plural": "複數名稱",
  "type.titleField": "標題欄位",
  "type.slugPolicy": "網址代稱",
  "type.slugPolicy.required": "必填",
  "type.slugPolicy.optional": "選填",
  "type.slugPolicy.none": "不使用",
  "type.singleton": "只有一筆",
  "type.previewable": "可以預覽",
  "type.fields": "欄位",
  "type.fields.lead": "欄位由種子定義，治理台只能檢視。",
  "field.col.name": "名稱",
  "field.col.type": "資料型別",
  "field.col.required": "必填",
  "field.col.listable": "列表顯示",
  "field.col.filterable": "可篩選",
  "field.col.visibility": "可見範圍",
  "field.col.options": "選項或關聯",
  "field.disabled": "（已停用）",
  "field.refTarget": "連到「{target}」",
  "field.type.string": "文字",
  "field.type.markdown": "長文",
  "field.type.int": "整數",
  "field.type.boolean": "是或否",
  "field.type.datetime": "日期時間",
  "field.type.enum": "選項",
  "field.type.ref": "關聯條目",
  "field.type.principal-ref": "會員帳號",
  "field.type.media-ref": "媒體",
  "field.visibility.public": "公開",
  "field.visibility.back": "作業面",
  "field.visibility.internal": "內部",

  "roles.title": "角色與權限",
  "roles.lead": "角色由系統定義；這裡可以調整每個角色能做什麼。帳號實際能碰哪些類型，另外在使用者頁指派。",
  "roles.col.name": "名稱",
  "roles.col.code": "代碼",
  "roles.col.kind": "種類",
  "roles.system": "系統角色",
  "roles.custom": "自訂",
  "roles.empty": "沒有角色",
  "roles.matrix": "內容權限",
  "roles.matrix.lead": "「所有類型」一列適用於帳號被指派的每個類型；其他列只適用於該類型。",
  "roles.col.type": "類型",
  "roles.allTypes": "所有類型",
  "roles.typeDisabled": "（已停用）",
  "roles.scoped": "限本人",
  "roles.global": "治理權限",
  "roles.locked": "管理員角色的權限固定為全部，不能在這裡修改，以免所有人失去治理台的存取權。",
  "roles.confirm.title": "儲存權限變更？",
  "roles.confirm.body": "新增 {added} 項、移除 {removed} 項。儲存後會立即套用到擁有這個角色的所有帳號。",
  "roles.confirm.submit": "儲存變更",
  "roles.saved": "已儲存權限",
  "roles.invalid": "權限設定不正確，變更沒有儲存。",
  "permission.read_published": "讀已發布",
  "permission.read_draft": "讀草稿",
  "permission.create": "建立",
  "permission.update": "更新",
  "permission.publish": "發布",
  "permission.unpublish": "下架",
  "permission.delete": "刪除",
  "permission.archive": "封存",
  "permission.manage_media": "管理媒體",
  "permission.manage_types": "管理內容類型",
  "permission.manage_principals": "管理使用者與角色",
  "permission.manage_settings": "管理系統設定",
  "permission.read_audit": "查看審計",

  "principals.title": "使用者",
  "principals.new": "新增使用者",
  "principals.search": "搜尋帳號或名稱",
  "principals.tab.all": "全部",
  "principals.tab.active": "啟用中",
  "principals.tab.disabled": "已停用",
  "principals.tab.locked": "已鎖定",
  "principals.col.username": "帳號",
  "principals.col.name": "顯示名稱",
  "principals.col.email": "電子郵件",
  "principals.col.status": "狀態",
  "principals.noMatch": "沒有符合的使用者",
  "principals.new.title": "新增使用者",
  "principals.new.submit": "建立使用者",
  "principals.new.rejected": "無法建立帳號：帳號或電子郵件已被使用，或格式不正確。",
  "principals.new.rolesFailed": "帳號已建立，但角色沒有儲存，請在帳號頁重新指派。",
  "principals.new.created": "帳號已建立",
  "principals.username.hint": "3 到 32 個字元，只能用小寫英文字母、數字、點、底線或連字號。",
  "principals.profile": "基本資料",
  "principals.profile.save": "儲存資料",
  "principals.profile.saved": "已儲存基本資料",
  "principals.profile.invalid": "資料不正確：名稱太長，或電子郵件已被使用。",
  "principals.email.cannotClear": "目前無法清除電子郵件；留空的話不會變更。",
  "principals.roles": "角色",
  "principals.role.member.hint": "可以登入公開網站的會員區。",
  "principals.role.editor.hint": "可以在 Back 建立與修改指定類型的內容，不能發布。",
  "principals.role.operator.hint": "可以在 Back 建立、修改、發布與下架指定類型的內容。",
  "principals.role.admin.hint": "可以使用 Admin center 的所有治理功能。",
  "principals.role.types": "{role}可以處理的類型",
  "principals.role.needTypes": "請至少選一個類型。",
  "principals.roles.save": "儲存角色",
  "principals.roles.saved": "已儲存角色",
  "principals.roles.invalid": "角色設定不正確，沒有儲存。",
  "principals.status": "帳號狀態",
  "principals.status.active.hint": "可以登入。",
  "principals.status.disabled.hint": "不能登入；資料仍保留。",
  "principals.status.locked.hint": "登入失敗太多次，暫時不能登入。",
  "principals.self": "這是你自己的帳號：不能停用，也不能移除自己的管理員角色。",
  "principals.unlock": "解除鎖定",
  "principals.unlocked": "已解除鎖定",
  "principals.enable": "重新啟用",
  "principals.enabled": "已重新啟用",
  "principals.disable": "停用帳號",
  "principals.disable.title": "停用「{name}」？",
  "principals.disable.body": "停用後，這個帳號會立即登出，而且不能再登入；資料不會刪除，之後可以重新啟用。",
  "principals.disabled": "已停用帳號",
  "principals.reset": "重設密碼",
  "principals.reset.title": "重設「{name}」的密碼？",
  "principals.reset.body": "會產生新的臨時密碼，並讓這個帳號在所有裝置登出。",
  "principals.reset.done": "已重設密碼",

  "audit.title": "審計",
  "audit.lead": "治理與發布的紀錄。紀錄不能修改或刪除。",
  "audit.tab.all": "全部",
  "audit.tab.ok": "成功",
  "audit.tab.denied": "被拒",
  "audit.from": "開始日期",
  "audit.to": "結束日期",
  "audit.actor": "操作者帳號",
  "audit.action": "動作",
  "audit.category": "類別",
  "audit.apply": "套用篩選",
  "audit.targetFilter": "只顯示同一個對象的事件。",
  "audit.targetFilter.clear": "顯示全部對象",
  "audit.col.at": "時間",
  "audit.col.actor": "操作者",
  "audit.col.action": "動作",
  "audit.col.target": "對象",
  "audit.col.outcome": "結果",
  "audit.empty": "這個時間窗沒有事件。",
  "audit.openEntry": "開啟條目",
  "audit.actor.system": "系統",
  "audit.actor.deleted": "已刪除的帳號",
  "audit.outcome.ok": "成功",
  "audit.outcome.denied": "被拒",
  "audit.category.AUTH": "帳號與登入",
  "audit.category.CONTENT": "內容",
  "audit.category.SCHEMA": "內容類型",
  "audit.category.SETTINGS": "設定",
  "audit.category.MEDIA": "媒體",
  "audit.category.GOVERNANCE": "治理存取",
  "audit.target.none": "—",
  "audit.target.entry": "條目",
  "audit.target.content_type": "內容類型",
  "audit.target.principal": "使用者",
  "audit.target.role": "角色",
  "audit.target.media": "媒體",
  "audit.target.settings": "設定",
  "audit.target.navigation": "導覽選單",
  "audit.action.entry.": "所有內容動作",
  "audit.action.entry.create": "建立條目",
  "audit.action.entry.publish": "發布條目",
  "audit.action.entry.unpublish": "下架條目",
  "audit.action.entry.archive": "封存條目",
  "audit.action.entry.restore": "還原條目",
  "audit.action.entry.soft_delete": "把條目移到回收",
  "audit.action.entry.purge": "永久刪除條目",
  "audit.action.entry.revert": "還原到舊版本",
  "audit.action.entry.publish_request": "請求發布",
  "audit.action.entry.publish_request_cancel": "撤回發布請求",
  "audit.action.type.create": "建立內容類型",
  "audit.action.type.enable": "啟用內容類型",
  "audit.action.type.disable": "停用內容類型",
  "audit.action.navigation.publish": "發布導覽選單",
  "audit.action.media.delete": "把媒體移到回收",
  "audit.action.role.permissions_update": "修改角色權限",
  "audit.action.settings.retention_updated": "修改審計保留期限",
  "audit.action.manage_types": "嘗試管理內容類型",
  "audit.action.manage_principals": "嘗試管理使用者",
  "audit.action.manage_settings": "嘗試修改系統設定",
  "audit.action.read_audit": "嘗試查看審計",
  "audit.action.PRINCIPAL_CREATED": "建立帳號",
  "audit.action.PRINCIPAL_DISABLED": "停用帳號",
  "audit.action.ROLE_ASSIGNED": "指派角色",
  "audit.action.PASSWORD_SET_BY_ADMIN": "重設密碼",
  "audit.action.PASSWORD_CHANGED": "自行更改密碼",
  "audit.action.PERMISSION_CHANGED": "修改角色權限（舊紀錄）",
  "audit.action.LOGIN_SUCCESS": "登入成功",
  "audit.action.LOGIN_FAILURE": "登入失敗",
  "audit.action.LOGOUT": "登出",
  "audit.detail.summary": "事件摘要",
  "audit.detail.code": "動作代碼",
  "audit.detail.surface": "操作面",
  "audit.detail.json": "事件內容",
  "audit.detail.readOnly": "唯讀；審計紀錄不能修改或刪除。",
  "audit.detail.none": "這筆事件沒有其他內容。",

  "media.title": "媒體與儲存",
  "media.lead": "整個媒體庫的用量。依帳號的用量、調整配額與永久刪除媒體，目前還沒有提供。",
  "media.usage": "媒體庫用量",
  "media.bytes": "已使用 {used}，上限 {max}（{percent}%）",
  "media.files": "{used} / {max} 個檔案",
  "media.maxFile": "單一檔案上限 {max}",
  "media.warning": "用量已超過 80%，新的上傳可能會被拒絕。",
  "media.backend": "儲存位置",
  "media.backend.local": "本機儲存（唯讀設定）",
  "media.backend.s3": "S3：介面保留，這一版沒有啟用。",

  "settings.title": "設定",
  "settings.audit": "審計保留期限",
  "settings.audit.lead": "審計事件保留多久：30、90 或 365 天。",
  "settings.media.lead": "媒體庫的用量與上限。",
  "settings.entries.lead": "依類型與標題找出條目，強制下架、封存或永久刪除，或連結會員帳號。",
  "retention.lead": "縮短期限不會立即刪除；下一次清理時才生效。",
  "retention.option": "{days} 天",
  "retention.defaultOption": "{days} 天（預設）",
  "retention.updated": "上次變更：{at}",
  "retention.default": "目前是預設值。",
  "retention.saved": "已更新保留期限",
  "retention.invalid": "只能選 30、90 或 365 天。",

  "entries.title": "緊急條目查詢",
  "entries.lead": "這裡不能編輯內容，只能查看狀態與發布紀錄，並做緊急處理。日常編輯請用 Back office。",
  "entries.type": "類型",
  "entries.type.placeholder": "選擇類型",
  "entries.search": "標題包含",
  "entries.submit": "搜尋",
  "entries.pickType": "先選擇類型",
  "entries.empty": "沒有符合的條目",
  "entries.untitled": "未命名",
  "entries.col.title": "標題",
  "entries.col.slug": "網址代稱",
  "entries.col.state": "狀態",
  "entries.col.updated": "最後更新",
  "entries.meta": "中繼資料",
  "entries.version": "版本",
  "entries.published": "最後發布",
  "entries.neverPublished": "尚未發布",
  "entries.requested": "等待發布",
  "entries.history": "發布紀錄",
  "entries.history.all": "在審計中查看全部",
  "entries.history.empty": "沒有發布紀錄。",
  "entries.help.title": "緊急處理",
  "entries.help.body": "強制下架或封存會寫入審計。永久刪除無法復原；審計紀錄會保留。",
  "entries.unpublish": "強制下架",
  "entries.unpublish.title": "下架「{name}」？",
  "entries.unpublish.body": "公開網站會立即找不到它；內容仍保留，可以在 Back 重新發布。",
  "entries.unpublished": "已下架",
  "entries.archive": "封存",
  "entries.archive.title": "封存「{name}」？",
  "entries.archive.body": "封存後不能再編輯，公開網站也找不到它；可以在 Back 還原。",
  "entries.archived": "已封存",
  "entries.purge": "永久刪除",
  "entries.purge.title": "永久刪除「{name}」？",
  "entries.purge.body": "永久刪除後無法復原，公開網站會立即找不到它。審計紀錄會保留。",
  "entries.purged": "已永久刪除",
  "entries.referenced": "還有其他條目連到它，請先在 Back 移除這些連結。",
  "entries.stateChanged": "狀態已經改變，已重新載入。",

  "member.card": "會員帳號連結",
  "member.none": "未連結",
  "member.unknown": "找不到這個帳號",
  "member.name": "{name}（{username}）",
  "member.edit": "變更連結",
  "member.title": "連結會員帳號：{field}",
  "member.lead": "只連結會員帳號。清單列出所有啟用中的帳號。",
  "member.search": "搜尋帳號或名稱",
  "member.save": "儲存連結",
  "member.saved": "已更新會員帳號連結",
  "member.conflict": "這筆資料已被其他人更新，已重新載入，請再試一次。",
  "member.invalid": "無法連結這個帳號。",
} as const;

export type CopyKey = keyof typeof copy;
