#!/usr/bin/env bash
# Simulates what Pi would do after reading the platform-bootstrap skill:
# probe host → generate a composable baseline platform under ./platform
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/platform"

DOMAIN="${DOMAIN:-apps.local}"
ENABLE_APM="${ENABLE_APM:-0}"
ENABLE_LLM_GATEWAY="${ENABLE_LLM_GATEWAY:-1}"
# Bind LLM gateway to loopback by default (safer on public VPS). Use 0.0.0.0 only behind firewall/VPN.
NINE_ROUTER_BIND="${NINE_ROUTER_BIND:-127.0.0.1}"
GRAFANA_ADMIN_PASSWORD="${GRAFANA_ADMIN_PASSWORD:-changeme}"
COMPOSE_PROJECT="${COMPOSE_PROJECT:-platform}"

echo "==> [probe] host"
uname -a || true
echo "disk:"
df -h / | tail -1 || true
echo "memory:"
free -h 2>/dev/null | sed -n '1,2p' || true
echo "docker:"
docker version --format '{{.Server.Version}}' 2>/dev/null || echo "(docker not reachable)"
docker compose version 2>/dev/null || true
echo "ports of interest (ss if available):"
if command -v ss >/dev/null 2>&1; then
  ss -lnt | grep -E ':(80|443|3000|9090|3100|8080|11800|12800|20128)\s' || echo "(none of 80/3000/9090/3100/20128/... listening)"
else
  echo "(ss not available)"
fi

echo "==> [generate] platform into $OUT"
mkdir -p \
  "$OUT/nginx/conf.d" \
  "$OUT/prometheus" \
  "$OUT/grafana/provisioning/datasources" \
  "$OUT/grafana/provisioning/dashboards" \
  "$OUT/loki" \
  "$OUT/promtail" \
  "$OUT/skywalking" \
  "$OUT/ci" \
  "$OUT/clients"

# --- docker network note is embedded in compose ---
cat > "$OUT/docker-compose.yml" <<EOF
# Generated by platform-bootstrap (Pi skill demo)
# Project: ${COMPOSE_PROJECT}
name: ${COMPOSE_PROJECT}

networks:
  edge:
    name: platform_edge

volumes:
  grafana_data:
  prometheus_data:
  loki_data:
  skywalking_es: {}
  nine_router_data: {}

services:
  nginx:
    image: nginx:1.27-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    networks: [edge]
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.55.1
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks: [edge]
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.3.1
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: "${GRAFANA_ADMIN_PASSWORD}"
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    ports:
      - "3000:3000"
    networks: [edge]
    depends_on: [prometheus, loki]
    restart: unless-stopped

  loki:
    image: grafana/loki:3.2.1
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/local-config.yaml:/etc/loki/local-config.yaml:ro
      - loki_data:/loki
    ports:
      - "3100:3100"
    networks: [edge]
    restart: unless-stopped

  promtail:
    image: grafana/promtail:3.2.1
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./promtail/config.yml:/etc/promtail/config.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks: [edge]
    depends_on: [loki]
    restart: unless-stopped
EOF

if [[ "$ENABLE_LLM_GATEWAY" == "1" ]]; then
  cat >> "$OUT/docker-compose.yml" <<EOF

  # LLM gateway — official 9router (OpenAI-compatible /v1)
  # Dashboard: http://127.0.0.1:20128/dashboard
  # Clients (Pi / OpenCode / etc.): http://127.0.0.1:20128/v1
  # Configure upstream providers in the dashboard — do not commit API keys.
  nine_router:
    image: decolua/9router:latest
    ports:
      - "${NINE_ROUTER_BIND}:20128:20128"
    volumes:
      - nine_router_data:/app/data
    environment:
      DATA_DIR: /app/data
      PORT: "20128"
      HOSTNAME: "0.0.0.0"
    networks: [edge]
    restart: unless-stopped
EOF
fi

if [[ "$ENABLE_APM" == "1" ]]; then
  cat >> "$OUT/docker-compose.yml" <<'EOF'

  # Optional APM — enable with ENABLE_APM=1
  # UI intentionally bound to localhost-style private use; put behind nginx+auth in real life.
  elasticsearch:
    profiles: ["apm"]
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    volumes:
      - skywalking_es:/usr/share/elasticsearch/data
    networks: [edge]
    restart: unless-stopped

  skywalking-oap:
    profiles: ["apm"]
    image: apache/skywalking-oap-server:10.1.0
    environment:
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200
    ports:
      - "11800:11800"
      - "12800:12800"
    networks: [edge]
    depends_on: [elasticsearch]
    restart: unless-stopped

  skywalking-ui:
    profiles: ["apm"]
    image: apache/skywalking-ui:10.1.0
    environment:
      SW_OAP_ADDRESS: http://skywalking-oap:12800
    ports:
      - "8080:8080"
    networks: [edge]
    depends_on: [skywalking-oap]
    restart: unless-stopped
EOF
fi

cat > "$OUT/nginx/nginx.conf" <<'EOF'
worker_processes auto;
events { worker_connections 1024; }
http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;
  sendfile      on;
  keepalive_timeout 65;
  include /etc/nginx/conf.d/*.conf;
}
EOF

cat > "$OUT/nginx/conf.d/default.conf" <<EOF
# Edge router for business apps on domain: ${DOMAIN}
# Pi / you can add one server or location block per app.

upstream grafana_upstream {
  server grafana:3000;
}

# Optional: uncomment to expose LLM gateway via nginx (prefer auth / IP allowlist first).
# upstream nine_router_upstream {
#   server nine_router:20128;
# }

server {
  listen 80;
  server_name ${DOMAIN};

  location /grafana/ {
    proxy_pass http://grafana_upstream/;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
  }

  # location /llm/ {
  #   proxy_pass http://nine_router_upstream/;
  #   proxy_set_header Host \$host;
  #   proxy_set_header X-Real-IP \$remote_addr;
  #   proxy_http_version 1.1;
  #   proxy_buffering off;
  #   proxy_read_timeout 3600s;
  # }

  # Example business app slots — point these at your compose services
  # after joining network platform_edge:
  #
  # location /app-a/ {
  #   proxy_pass http://app_a:8080/;
  # }
  # location /app-b/ {
  #   proxy_pass http://app_b:8080/;
  # }

  location / {
    return 200 'platform edge ok — add app routes in nginx/conf.d\n';
    add_header Content-Type text/plain;
  }
}
EOF

cat > "$OUT/prometheus/prometheus.yml" <<'EOF'
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  # Add one job per business system (prefer /metrics on each app)
  # - job_name: app-a
  #   static_configs:
  #     - targets: ["app_a:8080"]
EOF

cat > "$OUT/grafana/provisioning/datasources/datasources.yml" <<'EOF'
apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false
EOF

cat > "$OUT/grafana/provisioning/dashboards/dashboards.yml" <<'EOF'
apiVersion: 1
providers:
  - name: default
    orgId: 1
    folder: Platform
    type: file
    disableDeletion: false
    updateIntervalSeconds: 30
    options:
      path: /etc/grafana/provisioning/dashboards
EOF

cat > "$OUT/loki/local-config.yaml" <<'EOF'
auth_enabled: false
server:
  http_listen_port: 3100
common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory
schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h
limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
EOF

cat > "$OUT/promtail/config.yml" <<'EOF'
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: container
EOF

cat > "$OUT/ci/deploy-app.sh" <<'EOF'
#!/usr/bin/env bash
# Minimal Docker-flow CI/CD skeleton for business apps on this VPS.
# Intended usage from CI:
#   IMAGE=ghcr.io/you/app-a:sha ./ci/deploy-app.sh
set -euo pipefail

IMAGE="${IMAGE:?IMAGE required, e.g. ghcr.io/org/app:tag}"
SERVICE_NAME="${SERVICE_NAME:-app}"
NETWORK="${NETWORK:-platform_edge}"
HOST_PORT="${HOST_PORT:-}"

echo "Pulling $IMAGE"
docker pull "$IMAGE"

if docker network inspect "$NETWORK" >/dev/null 2>&1; then
  :
else
  echo "Network $NETWORK missing. Start platform stack first." >&2
  exit 1
fi

EXISTING="$(docker ps -aq -f name=^/${SERVICE_NAME}$ || true)"
if [[ -n "$EXISTING" ]]; then
  docker rm -f "$SERVICE_NAME"
fi

PORT_ARGS=()
if [[ -n "$HOST_PORT" ]]; then
  PORT_ARGS=(-p "${HOST_PORT}:8080")
fi

docker run -d --name "$SERVICE_NAME" --network "$NETWORK" --restart unless-stopped \
  "${PORT_ARGS[@]}" \
  "$IMAGE"

echo "Deployed $SERVICE_NAME from $IMAGE on network $NETWORK"
echo "Next: add Nginx location + Prometheus scrape for this service."
EOF
chmod +x "$OUT/ci/deploy-app.sh"

cat > "$OUT/ci/README.md" <<'EOF'
# Docker-flow CI skeleton

Idea:

1. CI builds image and pushes to registry
2. Deploy job SSHes to VPS (or runs self-hosted runner on VPS)
3. Calls `./ci/deploy-app.sh` with `IMAGE=... SERVICE_NAME=...`
4. App joins `platform_edge` network → Nginx can route → Promtail collects logs

This is intentionally tiny. Expand with health checks, blue/green, and secrets as needed.
EOF

# --- LLM client templates (Pi / OpenCode) ---
cat > "$OUT/clients/README.md" <<'EOF'
# Client wiring for 9router (LLM gateway)

9router exposes an OpenAI-compatible API at `http://127.0.0.1:20128/v1`.

Do not confuse:

| Name | Role |
|------|------|
| **OpenCode CLI** | Client tool — point its provider base URL at 9router `/v1` |
| **OpenCode Free** | A free *upstream provider inside* 9router (passthrough to opencode.ai) |

## First-time 9router setup

1. `docker compose up -d nine_router`
2. Open `http://127.0.0.1:20128/dashboard`
3. Set dashboard password / copy the gateway API key
4. Connect providers (OpenRouter, Anthropic, OpenAI, OpenCode Free, …)
5. Wire Pi / OpenCode using the templates in this folder

Compliance note: subscription and free-tier channels must follow each provider's terms; this stack does not bypass ToS.
EOF

cat > "$OUT/clients/pi-models.json.example" <<'EOF'
{
  "providers": {
    "nine": {
      "baseUrl": "http://127.0.0.1:20128/v1",
      "api": "openai-completions",
      "apiKey": "NINE_ROUTER_API_KEY"
    }
  }
}
EOF

cat > "$OUT/clients/opencode.jsonc.example" <<'EOF'
{
  // Merge into your OpenCode config. Replace the API key from 9router dashboard.
  // Optional: community plugin opencode-9router-plugin for dynamic model discovery.
  "$schema": "https://opencode.ai/config.json",
  "provider": {
    "nine": {
      "npm": "@ai-sdk/openai-compatible",
      "name": "9router",
      "options": {
        "baseURL": "http://127.0.0.1:20128/v1",
        "apiKey": "{env:NINE_ROUTER_API_KEY}"
      },
      "models": {
        "auto": {
          "name": "9router default / combo model — rename after dashboard setup"
        }
      }
    }
  }
}
EOF

cat > "$OUT/.env.example" <<'EOF'
# Local secrets for platform compose — copy to .env and keep out of git.
# Most LLM keys are configured inside 9router dashboard (persisted in volume).
# Optional: export for client tools on the same host.
NINE_ROUTER_API_KEY=replace-me-from-dashboard
EOF

{
  echo "# Platform inventory"
  echo
  echo "Generated at: $(date -Iseconds)"
  echo "Domain: \`${DOMAIN}\`"
  echo "APM enabled in compose file: \`${ENABLE_APM}\`"
  echo "LLM gateway (9router) enabled: \`${ENABLE_LLM_GATEWAY}\`"
  if [[ "$ENABLE_LLM_GATEWAY" == "1" ]]; then
    echo "9router bind: \`${NINE_ROUTER_BIND}:20128\`"
  fi
  echo
  echo "| Service | Port | Role |"
  echo "|---------|------|------|"
  echo "| nginx | 80 | edge router for business apps |"
  echo "| prometheus | 9090 | metrics |"
  echo "| grafana | 3000 | dashboards (admin / ${GRAFANA_ADMIN_PASSWORD}) |"
  echo "| loki | 3100 | log store |"
  echo "| promtail | (internal) | ship container logs to Loki |"
  if [[ "$ENABLE_LLM_GATEWAY" == "1" ]]; then
    echo "| nine_router | ${NINE_ROUTER_BIND}:20128 | LLM gateway — OpenAI-compatible \`/v1\` + dashboard |"
  fi
  if [[ "$ENABLE_APM" == "1" ]]; then
    echo "| skywalking-oap | 11800 / 12800 | APM backend (compose profile \`apm\`) |"
    echo "| skywalking-ui | 8080 | APM UI (compose profile \`apm\`) |"
  fi
  echo
  echo "## Start"
  echo
  echo '```bash'
  echo 'cd platform'
  echo 'docker compose up -d'
  if [[ "$ENABLE_LLM_GATEWAY" == "1" ]]; then
    echo '# LLM gateway: http://127.0.0.1:20128/dashboard'
    echo '# Wire clients: see clients/README.md'
  fi
  if [[ "$ENABLE_APM" == "1" ]]; then
    echo 'docker compose --profile apm up -d   # optional APM'
  fi
  echo '```'
  echo
  echo "## Attach a business app"
  echo
  echo "1. Put the app container on network \`platform_edge\`"
  echo "2. Add Nginx upstream/location in \`nginx/conf.d/\`"
  echo "3. Add Prometheus scrape job if the app exposes \`/metrics\`"
  echo "4. Reload nginx: \`docker compose exec nginx nginx -s reload\`"
  if [[ "$ENABLE_LLM_GATEWAY" == "1" ]]; then
    echo
    echo "## LLM clients (Pi / OpenCode)"
    echo
    echo "1. Start \`nine_router\` and open the dashboard"
    echo "2. Connect upstream providers (API keys stay in 9router data volume)"
    echo "3. Copy templates from \`clients/\` into Pi / OpenCode config"
    echo "4. Prefer bind \`127.0.0.1\` — do not expose 20128 on the public internet without auth"
  fi
} > "$OUT/INVENTORY.md"

{
  echo "## $(date -Iseconds) bootstrap"
  echo
  echo "- domain: ${DOMAIN}"
  echo "- enable_apm: ${ENABLE_APM}"
  echo "- enable_llm_gateway: ${ENABLE_LLM_GATEWAY}"
  echo "- nine_router_bind: ${NINE_ROUTER_BIND}"
  echo "- generator: scripts/bootstrap-platform.sh"
  echo
} >> "$OUT/CHANGELOG.md"

echo "==> done"
echo "Read: $OUT/INVENTORY.md"
echo "Validate: cd platform && docker compose config"
if [[ "$ENABLE_LLM_GATEWAY" == "1" ]]; then
  echo "LLM gateway: docker compose up -d nine_router"
  echo "Dashboard: http://127.0.0.1:20128/dashboard"
  echo "Client templates: $OUT/clients/"
fi
if [[ "$ENABLE_APM" == "1" ]]; then
  echo "APM services use profile 'apm': docker compose --profile apm up -d"
fi
