{{- if or .Values.config.apiKey .Values.config.jwtHSSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clarkq.fullname" . }}
  labels:
    {{- include "clarkq.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.config.apiKey }}
  api-key: {{ .Values.config.apiKey | quote }}
  {{- end }}
  {{- if .Values.config.jwtHSSecret }}
  jwt-hs-secret: {{ .Values.config.jwtHSSecret | quote }}
  {{- end }}
{{- end }}
