import { test, expect, type Page } from '@playwright/test';
test('AC-WS-02: non-empty home cards follow canonical request, failed execution, draft and audit data', async ({ page }, info) => {
    test.setTimeout(60000);
    const errors: string[] = [], steps: string[] = [];
    page.on('pageerror', e => errors.push(e.message));
    const role = (kind: Parameters<Page['getByRole']>[0], name: string) => page.getByRole(kind, { name, exact: true });
    const become = async (id: string) => { await role('combobox', '示範身分').selectOption(id); await expect(role('combobox', '示範身分')).toHaveValue(id); await expect(role('region', `${id === 'user-ops' ? 'ops' : id === 'user-admin' ? 'admin' : 'rd'} 工作首頁`)).toBeVisible(); };
    const home = async (center: string) => { await page.goto(`${center}?projectId=project-store`); await expect(role('region', `${center} 工作首頁`)).toBeVisible(); };
    await page.goto('rd/catalog');
    await role('link', '開始申請').click();
    await role('combobox', '應用').selectOption('app-checkout');
    await role('textbox', '環境名稱').fill('w1-home-pending');
    await role('textbox', '用途').fill('W1 canonical pending and failed home projections');
    await role('button', '確認並提交申請').click();
    await expect(page.getByRole('heading', { name: /w1-home-pending · 待審核/ })).toBeVisible();
    const requestId = new URL(page.url()).pathname.split('/').at(-1)!;
    await home('rd');
    const rdWork = role('region', '待處理申請與發布');
    await expect(rdWork).toContainText(requestId);
    await rdWork.getByRole('link', { name: /w1-home-pending/ }).click();
    await expect(page).toHaveURL(new RegExp(`/rd/requests/${requestId}$`));
    await page.goBack();
    await expect(role('combobox', '首頁專案')).toHaveValue('project-store');
    steps.push('RD pending canonical request and Back preserve project');
    await become('user-ops');
    await home('ops');
    await role('combobox', '首頁資源池').selectOption('pool-aws-sg');
    const approvals = role('region', '待審批與交付');
    await expect(approvals).toContainText(requestId);
    await approvals.getByRole('link', { name: /w1-home-pending/ }).click();
    await expect(page).toHaveURL(new RegExp(`/ops/requests/${requestId}$`));
    await role('button', '核准並保留容量').click();
    await expect(page.getByRole('heading', { name: /w1-home-pending · 已核准/ })).toBeVisible();
    await home('ops');
    await expect(approvals).toContainText('待交付');
    await approvals.getByRole('link', { name: /w1-home-pending/ }).click();
    await role('button', '啟動交付').click();
    await expect(page.getByRole('heading', { name: /w1-home-pending · 交付中/ })).toBeVisible();
    const jobLink = page.getByRole('link', { name: /job-/ }).last(), jobId = (await jobLink.textContent())!;
    await jobLink.click();
    await role('button', '在 configure 階段注入失敗').click();
    await expect(page.locator('.command-notice')).toContainText('已為這次 job 設定 configure 階段失敗');
    await page.goto('guide');
    await page.getByLabel('前進幅度').selectOption('5');
    await role('button', '前進演示時鐘').click();
    await expect(page.locator('.command-notice')).toContainText('演示時鐘已前進 5 個 tick');
    await home('ops');
    const failures = role('region', '失敗作業與發布');
    await expect(failures).toContainText(jobId);
    await page.screenshot({ path: info.outputPath('nonempty-ops.png'), fullPage: true });
    await failures.getByRole('link', { name: /w1-home-pending/ }).click();
    await expect(page).toHaveURL(new RegExp(`/ops/jobs/${jobId}$`));
    steps.push('Ops same request approval/execution and actual failed job drilldown');
    await become('user-rd-commerce');
    await home('rd');
    await expect(rdWork).toContainText(requestId);
    await expect(rdWork).toContainText('失敗');
    steps.push('RD sees same failed request after Ops execution');
    await become('user-admin');
    await page.goto('admin/catalog');
    await role('button', '建立下一版草稿').click();
    await expect(page.getByText('rev 2 · 草稿')).toBeVisible();
    await home('admin');
    const drafts = role('region', '待發布目錄草稿');
    await expect(drafts).toContainText('catalog-web');
    await drafts.getByRole('link').click();
    await expect(page).toHaveURL(/admin\/catalog\?itemId=catalog-web&revision=2$/);
    await expect(page.getByText('rev 2 · 草稿')).toBeVisible();
    await page.goBack();
    await expect(role('combobox', '首頁專案')).toHaveValue('project-store');
    steps.push('Admin actual draft canonical revision and Back preserve project');
    await page.goto('admin/access');
    await role('combobox', '使用者').selectOption('user-rd-data');
    await role('combobox', '角色').selectOption('ops');
    await page.getByLabel('Scope ID', { exact: true }).fill('project-store');
    await role('button', '新增授權').click();
    await expect(page.getByRole('row', { name: /user-rd-data.*Ops.*project-store/ })).toBeVisible();
    await home('admin');
    const access = role('region', '近期權限變更');
    await expect(access.getByRole('link')).toHaveCount(1);
    await access.getByRole('link').click();
    await expect(page.getByRole('table')).toContainText('access.write');
    await expect(page.getByLabel('Entity ID', { exact: true })).not.toHaveValue('');
    steps.push('Admin scoped grant audit drilldown filters target entity');
    expect(errors).toEqual([]);
    await info.attach('nonempty-home.json', { contentType: 'application/json', body: JSON.stringify({ steps, requestId, jobId, errors }) });
});
