import { test, expect, type Page, type TestInfo } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { apiErrorSchema, type Snapshot } from '../src/domain/schemas'
import { captureBrowserHealth, verifyBrowserHealth } from './browser-health'
import { become, visitChange, act, ticks, createResource, readSnapshot, raw } from './w2-resource-helpers'

const snapshot = async (page: Page): Promise<Snapshot> => readSnapshot(page)
const changeById = (saved: Snapshot, id: string) => saved.entities.changes.find(item => item.id === id)!
const businessResources = (saved: Snapshot) => ({ objects: saved.entities.resourceObjects, bindings: saved.entities.resourceBindings, quotas: saved.entities.resourceQuotas })

async function accessibleAtSizes(page: Page, info: TestInfo, label: string) {
  for (const theme of ['light', 'dark']) {
    if (await page.locator('html').getAttribute('data-theme') !== theme) await page.getByRole('button', { name: theme === 'dark' ? '切換深色主題' : '切換淺色主題' }).click()
    for (const width of [1440, 768, 390]) {
      await page.setViewportSize({ width, height: 1000 })
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `${label}: ${theme} ${width}`).toBe(true)
      const violations = (await new AxeBuilder({ page }).analyze()).violations.filter(item => ['serious', 'critical'].includes(item.impact ?? ''))
      expect(violations, `${label}: ${theme} ${width}`).toEqual([])
      await info.attach(`${label}-${theme}-${width}`, { body: await page.screenshot({ fullPage: true }), contentType: 'image/png' })
    }
  }
  await page.setViewportSize({ width: 1440, height: 1000 })
}

async function refuseAction(page: Page, name: string, code: string) {
  await page.getByRole('button', { name, exact: true }).click()
  const dialog = page.getByRole('dialog', { name, exact: true })
  await expect(dialog).toBeVisible()
  const reason = dialog.getByRole('textbox', { name: '決策／操作理由' })
  if (await reason.count()) await reason.fill('Verify current template policy refuses this old request')
  await dialog.getByRole('button', { name: '確認操作', exact: true }).click()
  await expect(dialog.getByRole('alert')).toContainText(code)
  await dialog.getByRole('button', { name: '取消', exact: true }).click()
  await expect(dialog).toHaveCount(0)
}

async function deliver(page: Page, id: string) {
  await become(page, 'user-ops')
  await visitChange(page, 'ops', id)
  await act(page, '核准並保留配額')
  await expect(page.locator('.page-heading')).toContainText('已核准，待執行')
  await act(page, '啟動資源執行')
  await ticks(page)
  await expect(page.locator('.page-heading')).toContainText('已成功')
}

test('W2 AC-04/07/09: Ops shared Redis resize needs independent approval and updates both consumers after execution', async ({ page }, info) => {
  test.setTimeout(180_000)
  const health = captureBrowserHealth(page)
  health.expectedStatuses.add(403)
  try {
    await page.goto('rd')
    await become(page, 'user-ops')
    await page.goto('ops/caches/ci-idc-redis-01')
    const initial = await snapshot(page)
    const article = page.locator('article#w2-object-redis-commerce')
    const trigger = article.getByRole('button', { name: '提出共享配額維護', exact: true })
    for (let index = 0; index < 80 && !await trigger.evaluate(el => el === document.activeElement); index++) await page.keyboard.press('Tab')
    await expect(trigger).toBeFocused()
    await page.keyboard.press('Enter')
    const dialog = page.getByRole('dialog', { name: 'Redis allocation 配額維護', exact: true })
    await expect(dialog).toBeVisible()
    expect(await dialog.evaluate(el => el.contains(document.activeElement))).toBe(true)
    await page.keyboard.press('Escape')
    await expect(dialog).toHaveCount(0)
    await expect(trigger).toBeFocused()
    await page.keyboard.press('Enter')
    await dialog.getByRole('spinbutton', { name: '期望配額 MiB', exact: true }).fill('2048')
    await dialog.getByRole('textbox', { name: '維護理由', exact: true }).fill('Shared Commerce allocation needs 2048 MiB for both consumers')
    await expect(dialog).toContainText('checkout')
    await expect(dialog).toContainText('storefront')
    expect((await new AxeBuilder({ page }).analyze()).violations.filter(item => ['serious', 'critical'].includes(item.impact ?? ''))).toEqual([])
    await dialog.getByRole('button', { name: '建立維護草稿', exact: true }).click()
    await expect(page.getByRole('heading', { name: '資源變更詳情', exact: true })).toBeVisible()
    const id = new URL(page.url()).pathname.split('/').at(-1)!
    await act(page, '提交審核')
    await expect(page.locator('.page-heading')).toContainText('待審核')
    await expect(page.getByRole('button', { name: '核准並保留配額', exact: true })).toHaveCount(0)
    const submitted = changeById(await snapshot(page), id)
    expect(submitted.requesterId).toBe('user-ops')
    expect(submitted.spec.applicationId).toBeUndefined()
    const selfApproval = await raw(page, `/changes/${id}/approve`, 'POST', { expectedVersion: submitted.version, reason: 'Direct self approval must fail' }, 'w2-browser-self-approval')
    expect(selfApproval.status).toBe(403)
    expect(selfApproval.payload.error.code).toBe('SELF_APPROVAL_DENIED')
    expect(changeById(await snapshot(page), id)).toEqual(submitted)
    await become(page, 'w2-user-ops-secondary')
    await visitChange(page, 'ops', id)
    await act(page, '核准並保留配額')
    await expect(page.locator('.page-heading')).toContainText('已核准，待執行')
    expect((await snapshot(page)).entities.resourceObjects).toEqual(initial.entities.resourceObjects)
    await become(page, 'user-ops')
    await visitChange(page, 'ops', id)
    await act(page, '啟動資源執行')
    await ticks(page, 2)
    await page.reload()
    await expect(page.locator('.page-heading')).toContainText('執行中')
    await ticks(page, 3)
    await expect(page.locator('.page-heading')).toContainText('已成功')
    const completed = await snapshot(page)
    const object = completed.entities.resourceObjects.find(item => item.id === 'w2-object-redis-commerce')!
    expect(object.spec).toEqual({ quotaMiB: 2048 })
    expect(completed.entities.resourceBindings).toEqual(initial.entities.resourceBindings)
    expect(completed.entities.resourceObjects.filter(item => item.id !== object.id)).toEqual(initial.entities.resourceObjects.filter(item => item.id !== object.id))
    expect(changeById(completed, id).decisions[0].actorId).toBe('w2-user-ops-secondary')
    expect(changeById(completed, id).specSnapshot).toEqual(submitted.specSnapshot)
    await become(page, 'user-rd-commerce')
    for (const app of ['checkout', 'storefront']) {
      await page.goto(`rd/apps/app-${app}/resources?environmentId=env-${app}-dev`)
      await expect(page.getByText('w2-object-redis-commerce', { exact: true })).toBeVisible()
      await expect(page.getByText('2048 MiB 配額', { exact: true })).toBeVisible()
    }
    await info.attach('shared-resize-canonical.json', { body: JSON.stringify({ id, object, change: changeById(completed, id), bindings: completed.entities.resourceBindings.filter(item => item.resourceObjectId === object.id) }), contentType: 'application/json' })
  } finally { await verifyBrowserHealth(page, info, health) }
})

test('W2 AC-05/06: Kafka existing binding preserves object and topic identity is unique within each parent', async ({ page }, info) => {
  test.setTimeout(240_000)
  const health = captureBrowserHealth(page)
  health.expectedStatuses.add(409)
  try {
    await page.goto('rd/catalog/w2-catalog-kafka/resource-request')
    await page.getByRole('combobox', { name: '服務', exact: true }).selectOption('app-checkout')
    await page.getByRole('combobox', { name: '服務環境', exact: true }).selectOption('env-checkout-dev')
    await page.getByRole('combobox', { name: 'Kafka cluster', exact: true }).selectOption('w2-ci-kafka-idc')
    await page.getByRole('combobox', { name: '需求類型', exact: true }).selectOption('existing')
    await page.getByRole('combobox', { name: '已有子資源', exact: true }).selectOption('w2-object-kafka-idc-orders')
    await page.getByRole('combobox', { name: '綁定用途', exact: true }).selectOption('consumer')
    await expect(page.getByRole('combobox', { name: '安全存取 profile', exact: true })).toHaveValue('w2-profile-kafka-consumer')
    await page.getByRole('textbox', { name: '申請理由', exact: true }).fill('Checkout consumes the existing canonical orders topic')
    const initial = await snapshot(page)
    await page.getByRole('button', { name: '建立資源草稿', exact: true }).click()
    await expect(page.getByRole('heading', { name: '資源變更詳情', exact: true })).toBeVisible()
    const bindingChangeId = new URL(page.url()).pathname.split('/').at(-1)!
    await act(page, '提交審核')
    await deliver(page, bindingChangeId)
    const bound = await snapshot(page)
    expect(bound.entities.resourceObjects).toEqual(initial.entities.resourceObjects)
    expect(bound.entities.resourceBindings).toHaveLength(initial.entities.resourceBindings.length + 1)
    const binding = bound.entities.resourceBindings.find(item => item.requestRef.sourceId === bindingChangeId)!
    expect(binding).toMatchObject({ resourceObjectId: 'w2-object-kafka-idc-orders', environmentId: 'env-checkout-dev', purpose: 'consumer', accessProfileRef: 'w2-profile-kafka-consumer', state: 'active' })
    await become(page, 'user-rd-commerce')
    await page.goto('rd/apps/app-checkout/resources?environmentId=env-checkout-dev')
    await expect(page.getByText(binding.id, { exact: true })).toBeVisible()
    const topic = 'w2-browser-shared-name'
    const idcId = await createResource(page, 'kafka', { ciId: 'w2-ci-kafka-idc', topic })
    await act(page, '提交審核')
    await deliver(page, idcId)
    await become(page, 'user-rd-commerce')
    await page.goto('rd/catalog/w2-catalog-kafka/resource-request')
    await page.getByRole('combobox', { name: '服務', exact: true }).selectOption('app-checkout')
    await page.getByRole('combobox', { name: '服務環境', exact: true }).selectOption('env-checkout-dev')
    await page.getByRole('combobox', { name: 'Kafka cluster', exact: true }).selectOption('w2-ci-kafka-idc')
    await page.getByRole('textbox', { name: 'Topic 名稱', exact: true }).fill(topic.toUpperCase())
    await page.getByRole('textbox', { name: '申請理由', exact: true }).fill('Verify normalized topic identity on the same parent')
    const beforeDuplicate = await snapshot(page)
    const duplicateResponse = page.waitForResponse(response => response.request().method() === 'POST' && response.url().endsWith('/api/v1/changes'))
    await page.getByRole('button', { name: '建立資源草稿', exact: true }).click()
    expect((await duplicateResponse).status()).toBe(409)
    await expect(page.getByRole('alert')).toContainText('DUPLICATE_RESOURCE')
    const afterDuplicate = await snapshot(page)
    expect(afterDuplicate.entities.changes).toEqual(beforeDuplicate.entities.changes)
    expect(businessResources(afterDuplicate)).toEqual(businessResources(beforeDuplicate))
    await page.getByRole('combobox', { name: 'Kafka cluster', exact: true }).selectOption('w2-ci-kafka-aws')
    await page.getByRole('textbox', { name: 'Topic 名稱', exact: true }).fill(topic)
    await page.getByRole('textbox', { name: '申請理由', exact: true }).fill('The same topic name is valid on a different canonical parent')
    await page.getByRole('button', { name: '建立資源草稿', exact: true }).click()
    await expect(page.getByRole('heading', { name: '資源變更詳情', exact: true })).toBeVisible()
    const awsId = new URL(page.url()).pathname.split('/').at(-1)!
    await act(page, '提交審核')
    await deliver(page, awsId)
    const final = await snapshot(page)
    const twins = final.entities.resourceObjects.filter(item => item.externalRef === topic)
    expect(twins).toHaveLength(2)
    expect(new Set(twins.map(item => item.parentCiId))).toEqual(new Set(['w2-ci-kafka-idc', 'w2-ci-kafka-aws']))
    expect(new Set(twins.map(item => item.id)).size).toBe(2)
    await page.reload()
    await expect(page.locator('.page-heading')).toContainText('已成功')
    await become(page, 'user-rd-commerce')
    await page.goto('rd/apps/app-checkout/resources?environmentId=env-checkout-dev')
    for (const object of twins) await expect(page.getByText(object.id, { exact: true })).toBeVisible()
    await info.attach('kafka-parent-identity.json', { body: JSON.stringify({ bindingChangeId, binding, idcId, awsId, twins }), contentType: 'application/json' })
  } finally { await verifyBrowserHealth(page, info, health) }
})

for (const kind of ['redis', 'kafka'] as const) {
  test(`W2 AC-06/09/15/17: Admin ${kind} typed revision and disable refuse old changes without rewriting frozen snapshots`, async ({ page }, info) => {
    test.setTimeout(240_000)
    const health = captureBrowserHealth(page)
    health.expectedStatuses.add(409)
    try {
      await page.goto('rd')
      const originalResources = businessResources(await snapshot(page))
      const oldDraftId = await createResource(page, kind, { topic: 'w2-catalog-old-draft' })
      const oldSubmittedId = await createResource(page, kind, { topic: 'w2-catalog-old-submitted' })
      await act(page, '提交審核')
      const oldSnapshot = await snapshot(page)
      const oldDraft = changeById(oldSnapshot, oldDraftId)
      const oldSubmitted = changeById(oldSnapshot, oldSubmittedId)
      expect(oldSubmitted.catalogSnapshot?.revision).toBe(1)
      await become(page, 'user-admin')
      await page.goto(`admin/catalog?itemId=w2-catalog-${kind}`)
      await page.getByRole('textbox', { name: '變更理由', exact: true }).fill(`Govern ${kind} limits through visible typed editor`)
      await page.getByRole('button', { name: '建立下一版草稿', exact: true }).click()
      await expect(page.getByRole('heading', { name: kind === 'redis' ? 'Redis allocation 型別化草稿' : 'Kafka topic 型別化草稿', exact: true })).toBeVisible()
      const defaultLabel = kind === 'redis' ? '預設 · 配額 MiB' : '預設 · Partitions'
      const newDefault = kind === 'redis' ? '768' : '4'
      await page.getByRole('spinbutton', { name: defaultLabel, exact: true }).fill(newDefault)
      await page.getByRole('button', { name: '儲存草稿內容', exact: true }).click()
      await expect(page.getByRole('spinbutton', { name: defaultLabel, exact: true })).toHaveValue(newDefault)
      await expect.poll(async () => (await snapshot(page)).entities.catalogs.find(item => item.id === `w2-catalog-${kind}`)!.template.defaults).toEqual(kind === 'redis' ? { quotaMiB: 768 } : { partitions: 4, retentionHours: 72, throughputKiBPerSecond: 512 })
      await accessibleAtSizes(page, info, `${kind}-typed-editor`)
      await page.getByRole('button', { name: '發布 revision', exact: true }).click()
      await expect(page.locator('article')).toContainText('rev 2 · 已發布')
      expect(changeById(await snapshot(page), oldSubmittedId)).toEqual(oldSubmitted)
      await become(page, 'user-rd-commerce')
      await visitChange(page, 'rd', oldDraftId)
      await refuseAction(page, '提交審核', 'CATALOG_CHANGED')
      expect(changeById(await snapshot(page), oldDraftId)).toEqual(oldDraft)
      await become(page, 'user-ops')
      await visitChange(page, 'ops', oldSubmittedId)
      await refuseAction(page, '核准並保留配額', 'CATALOG_CHANGED')
      expect(changeById(await snapshot(page), oldSubmittedId)).toEqual(oldSubmitted)
      await become(page, 'user-rd-commerce')
      const disabledId = await createResource(page, kind, { topic: 'w2-catalog-disabled-pending' })
      await act(page, '提交審核')
      const beforeDisable = changeById(await snapshot(page), disabledId)
      expect(beforeDisable.catalogSnapshot?.revision).toBe(2)
      expect(beforeDisable.catalogSnapshot?.template.defaults).toEqual(kind === 'redis' ? { quotaMiB: 768 } : { partitions: 4, retentionHours: 72, throughputKiBPerSecond: 512 })
      await become(page, 'user-admin')
      await page.goto(`admin/catalog?itemId=w2-catalog-${kind}`)
      await page.getByRole('textbox', { name: '變更理由', exact: true }).fill('Stop new approvals while retaining immutable submitted history')
      await page.getByRole('button', { name: '停用新申請', exact: true }).click()
      await expect(page.locator('article')).toContainText('已停用')
      await become(page, 'user-ops')
      await visitChange(page, 'ops', disabledId)
      await refuseAction(page, '核准並保留配額', 'CATALOG_DISABLED')
      await page.reload()
      await expect(page.locator('.page-heading')).toContainText('待審核')
      await become(page, 'user-rd-commerce')
      await visitChange(page, 'rd', oldDraftId)
      await refuseAction(page, '提交審核', 'CATALOG_DISABLED')
      const final = await snapshot(page)
      expect(changeById(final, oldDraftId)).toEqual(oldDraft)
      expect(changeById(final, disabledId)).toEqual(beforeDisable)
      expect(changeById(final, oldSubmittedId)).toEqual(oldSubmitted)
      expect(businessResources(final)).toEqual(originalResources)
      await info.attach(`${kind}-governance-history.json`, { body: JSON.stringify({ oldDraft, oldSubmitted, beforeDisable, finalChanges: final.entities.changes, catalogs: final.entities.catalogs.filter(item => item.id === `w2-catalog-${kind}`) }), contentType: 'application/json' })
    } finally { await verifyBrowserHealth(page, info, health) }
  })
}

test('W2 AC-09/15: Admin UI grant revocation redacts objects then removes physical resource visibility after reload', async ({ page }, info) => {
  test.setTimeout(120_000)
  const health = captureBrowserHealth(page)
  health.expectedStatuses.add(404)
  try {
    await page.goto('rd')
    await become(page, 'user-ops')
    await page.goto('ops/caches/ci-idc-redis-01')
    await expect(page.getByText('w2-object-redis-data', { exact: true })).toBeVisible()
    const initial = await snapshot(page)
    await become(page, 'user-admin')
    await page.goto('admin/access')
    await page.getByRole('textbox', { name: '理由', exact: true }).fill('Revoke IDC resource management scope through Admin UI')
    const row = page.getByRole('row').filter({ has: page.getByText('grant-ops-idc', { exact: true }) })
    await expect(row).toContainText('user-ops')
    await row.getByRole('button', { name: '撤銷', exact: true }).click()
    await expect(row).toHaveCount(0)
    const revoked = await snapshot(page)
    expect(revoked.policyVersion).toBe(initial.policyVersion + 1)
    expect(businessResources(revoked)).toEqual(businessResources(initial))
    await become(page, 'user-ops')
    await page.goto('ops/caches/ci-idc-redis-01')
    // Project grants still authorize the physical CI, while the removed pool grant
    // immediately prevents access to explicit resource objects and bindings.
    await expect(page.getByRole('heading', { name: '影響範圍未完整授權', exact: true })).toBeVisible()
    await expect(page.locator('main')).not.toContainText('w2-object-redis-data')
    await expect(page.locator('main')).not.toContainText('w2-object-redis-commerce')
    for (const objectId of ['w2-object-redis-data', 'w2-object-redis-commerce']) {
      const denied = await raw(page, `/resource-objects/${objectId}`)
      expect(denied.status).toBe(404)
      expect(apiErrorSchema.safeParse(denied.payload).success).toBe(true)
      expect(denied.payload.data).toBeUndefined()
      expect(JSON.stringify(denied.payload)).not.toContain(objectId)
    }
    const parentProjects = initial.entities.cis.find(item => item.id === 'ci-idc-redis-01')!.visibilityProjectIds
    const projectGrants = initial.entities.assignments.filter(item => item.userId === 'user-ops' && item.role === 'ops' && item.scopeType === 'project' && parentProjects.includes(item.scopeId))
    expect(projectGrants.length).toBeGreaterThan(0)
    await become(page, 'user-admin')
    await page.goto('admin/access')
    await page.getByRole('textbox', { name: '理由', exact: true }).fill('Remove remaining project visibility to verify union-of-grants deep-read denial')
    for (const grant of projectGrants) {
      const projectRow = page.getByRole('row').filter({ has: page.getByText(grant.id, { exact: true }) })
      await projectRow.getByRole('button', { name: '撤銷', exact: true }).click()
      await expect(projectRow).toHaveCount(0)
    }
    await become(page, 'user-ops')
    await page.goto('ops/caches/ci-idc-redis-01')
    await expect(page.getByRole('heading', { name: '找不到這個資源或工作單', exact: true })).toBeVisible()
    await expect(page.locator('main')).not.toContainText('w2-object-redis-data')
    await expect(page.locator('main')).not.toContainText('w2-binding-data-redis')
    for (const path of ['/resource-inventory/ci-idc-redis-01', '/resource-objects/w2-object-redis-data', '/resource-objects/w2-object-redis-commerce']) {
      const denied = await raw(page, path)
      expect(denied.status).toBe(404)
      expect(apiErrorSchema.safeParse(denied.payload).success).toBe(true)
      expect(denied.payload.data).toBeUndefined()
      expect(JSON.stringify(denied.payload)).not.toMatch(/w2-object|w2-binding|commerce-dev|data-dev/)
    }
    await page.reload()
    await expect(page.getByRole('heading', { name: '找不到這個資源或工作單', exact: true })).toBeVisible()
    await page.goto('ops/caches')
    await expect(page.locator('main h1')).toHaveText('Redis 快取')
    await expect(page.locator('main')).not.toContainText('ci-idc-redis-01')
    const final = await snapshot(page)
    expect(businessResources(final)).toEqual(businessResources(initial))
    await info.attach('revoked-resource-scope.json', { body: JSON.stringify({ oldPolicyVersion: initial.policyVersion, newPolicyVersion: final.policyVersion, assignments: final.entities.assignments.filter(item => item.userId === 'user-ops') }), contentType: 'application/json' })
  } finally { await verifyBrowserHealth(page, info, health) }
})
