import { test, expect, type Page } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { captureBrowserHealth, verifyBrowserHealth, type BrowserHealth } from './browser-health'
import { act, advance, become, createTraffic, denied, publish, save, snapshot, source, visit } from './w3-ui-helpers'

const health = new WeakMap<Page, BrowserHealth>()
test.beforeEach(({ page }) => { health.set(page, captureBrowserHealth(page)); test.setTimeout(180_000) })
test.afterEach(async ({ page }, info) => { await verifyBrowserHealth(page, info, health.get(page)!) })

test('W3 configuration: typed validation, active diff, failed apply and historical restore survive reload', async ({ page }, info) => {
  const id = 'w3-config-checkout-dev-1'
  await visit(page, 'serviceConfig', id)
  await page.getByRole('button', { name: '編輯草稿', exact: true }).click()
  const originalKey = await page.getByRole('textbox', { name: '設定名稱 2', exact: true }).inputValue()
  await page.getByRole('textbox', { name: '設定名稱 2', exact: true }).fill(await page.getByRole('textbox', { name: '設定名稱 1', exact: true }).inputValue())
  await save(page)
  await act(page, '驗證草稿')
  await expect(page.getByRole('list', { name: '驗證欄位錯誤' })).toContainText('spec.entries.1.key')
  expect((await source(page, id)).state).toBe('draft')
  await page.getByRole('button', { name: '編輯草稿', exact: true }).click()
  await page.getByRole('textbox', { name: '設定名稱 2', exact: true }).fill(originalKey)
  await page.getByRole('textbox', { name: '變更理由', exact: true }).fill('Correct typed unique configuration before applying')
  await save(page)
  expect((await source(page, id)).validationResult).toBeNull()
  await act(page, '驗證草稿')
  await act(page, '套用配置')
  await advance(page, 1)
  const inProgress = await snapshot(page)
  await page.reload()
  await expect(page.getByRole('heading', { name: '執行結果與證據', exact: true })).toBeVisible()
  expect(await snapshot(page)).toEqual(inProgress)
  await advance(page, 3)
  expect((await source(page, id)).state).toBe('active')
  await act(page, '建立下一版草稿')
  const next = new URL(page.url()).searchParams.get('revisionId')!
  expect(next).not.toBe(id)
  await page.getByRole('button', { name: '編輯草稿', exact: true }).click()
  await page.getByRole('textbox', { name: '設定值 1', exact: true }).fill('debug')
  await save(page)
  await expect(page.getByRole('region', { name: '配置差異，可水平捲動', exact: true })).toContainText('debug')
  await act(page, '驗證草稿'); await act(page, '套用配置')
  await page.getByRole('button', { name: '模擬配置套用失敗', exact: true }).click()
  await expect(page.getByRole('button', { name: '模擬配置套用失敗', exact: true })).toBeDisabled()
  await advance(page, 3)
  expect((await source(page, next)).state).toBe('failed')
  await expect(page.getByText('SIMULATED_CONFIG_FAILURE', { exact: true })).toBeVisible()
  expect((await source(page, id)).state).toBe('active')
  await visit(page, 'serviceConfig', id)
  await act(page, '以此版本建立回復草稿')
  const restored = new URL(page.url()).searchParams.get('revisionId')!
  expect(await source(page, restored)).toMatchObject({ state: 'draft', revision: 3, restoredFromId: id, validationResult: null })
  await expect(page.getByText('回復內容來源', { exact: true })).toBeVisible()
  await act(page, '驗證草稿'); await act(page, '套用配置'); await advance(page, 3)
  expect((await source(page, id)).state).toBe('superseded')
  expect((await source(page, restored)).state).toBe('active')
  await page.getByRole('combobox', { name: '對照環境', exact: true }).selectOption('env-checkout-prod')
  await expect(page.getByRole('region', { name: '跨環境配置比較，可水平捲動', exact: true })).toContainText('尚無生效配置')
  await info.attach('config-lineage', { body: JSON.stringify({ original: await source(page, id), failed: await source(page, next), restored: await source(page, restored) }), contentType: 'application/json' })
})

test('W3 production config: independent Ops approval, original source work item and Admin isolation', async ({ page }) => {
  await visit(page, 'serviceConfig', undefined, 'env-checkout-prod')
  await page.getByRole('button', { name: '新增服務配置', exact: true }).click()
  await page.getByRole('button', { name: '新增設定項目', exact: true }).click()
  await page.getByRole('textbox', { name: '設定名稱 1', exact: true }).fill('PROD_READY')
  await page.getByRole('combobox', { name: '值型別 1', exact: true }).selectOption('boolean')
  await page.getByRole('combobox', { name: '設定值 1', exact: true }).selectOption('true')
  await page.getByRole('textbox', { name: '變更理由', exact: true }).fill('Production typed configuration with independent approval')
  const id = await save(page)
  await act(page, '驗證草稿'); await act(page, '提交獨立審批')
  expect((await source(page, id)).state).toBe('pending_approval')
  await expect(page.getByRole('button', { name: '套用配置', exact: true })).toHaveCount(0)
  health.get(page)!.expectedStatuses.add(403)
  const before = await snapshot(page)
  expect(await denied(page, `/service-configs/${id}/approve`, { expectedVersion: (await source(page, id)).version, reason: 'Cannot self approve' })).toMatchObject({ status: 403 })
  expect(await snapshot(page)).toEqual(before)
  await become(page, 'user-ops')
  await page.goto('ops/requests')
  await expect(page.getByRole('link', { name: id, exact: true })).toBeVisible()
  await page.getByRole('link', { name: id, exact: true }).click()
  await expect(page).toHaveURL(new RegExp(`/ops/service-changes/serviceConfig/${id}$`))
  await act(page, '核准變更')
  await expect(page.getByRole('button', { name: '套用配置', exact: true })).toHaveCount(0)
  expect((await source(page, id)).state).toBe('approved')
  expect((await snapshot(page)).entities.serviceExecutions).toHaveLength(0)
  await become(page, 'user-rd-commerce'); await visit(page, 'serviceConfig', id, 'env-checkout-prod')
  await act(page, '套用配置'); await advance(page, 3)
  expect(await source(page, id)).toMatchObject({ state: 'active', decisions: [{ actorId: 'user-ops', decision: 'approved' }] })
  await act(page, '建立下一版草稿')
  const rejected = new URL(page.url()).searchParams.get('revisionId')!
  await act(page, '驗證草稿'); await act(page, '提交獨立審批')
  await become(page, 'user-ops'); await visit(page, 'serviceConfig', rejected, 'env-checkout-prod', 'ops')
  await act(page, '拒絕變更', 'Decline the proposed next configuration without executing')
  expect((await source(page, rejected)).state).toBe('rejected')
  expect((await source(page, id)).state).toBe('active')
  await become(page, 'user-rd-commerce'); await visit(page, 'serviceConfig', rejected, 'env-checkout-prod')
  await act(page, '建立下一版草稿')
  const cancelled = new URL(page.url()).searchParams.get('revisionId')!
  await act(page, '取消變更', 'Withdraw the replacement draft before submission')
  expect((await source(page, cancelled)).state).toBe('cancelled')
  await become(page, 'user-admin')
  health.get(page)!.expectedStatuses.add(404)
  const hidden = await denied(page, `/service-configs/${id}`, undefined, 'GET')
  expect(hidden.status).toBe(404); expect(JSON.stringify(hidden.payload)).not.toContain('PROD_READY')
  expect(await denied(page, '/service-configs', { applicationId: 'app-checkout', environmentId: 'env-checkout-prod', environmentVersion: 2, reason: 'Admin has no service write', spec: { entries: [] } })).toMatchObject({ status: 403 })
})

test('W3 traffic: actual releases, missing health timeout, complete checkpoints and persisted evidence', async ({ page }, info) => {
  await page.goto('rd')
  const candidate = await publish(page, 'w3-canary-candidate')
  const baseline = await publish(page, 'w3-current-baseline')
  const id = await createTraffic(page, baseline, candidate)
  await act(page, '驗證草稿'); await act(page, '開始灰度放量')
  const originalActive = (await snapshot(page)).entities.environments.find(item => item.id === 'env-checkout-dev')!.activeReleaseId
  await page.getByRole('button', { name: '模擬流量樣本缺漏', exact: true }).click()
  await advance(page, 60)
  expect((await source(page, id)).state).toBe('rolling_out')
  await expect(page.getByRole('region', { name: '流量健康樣本，可水平捲動', exact: true })).toContainText('未知')
  await page.reload(); await expect(page.getByRole('heading', { name: '目前有效流量', exact: true })).toBeVisible()
  await advance(page, 60)
  expect((await source(page, id)).state).toBe('failed')
  await expect(page.getByText('TRAFFIC_HEALTH_TIMEOUT', { exact: true })).toBeVisible()
  await act(page, '建立下一版草稿')
  const next = new URL(page.url()).searchParams.get('revisionId')!
  await act(page, '驗證草稿'); await act(page, '開始灰度放量')
  health.get(page)!.expectedStatuses.add(409)
  const locked = await snapshot(page), environment = locked.entities.environments.find(item => item.id === 'env-checkout-dev')!
  expect(await denied(page, '/pipelines', { applicationId: 'app-checkout', environmentId: environment.id, environmentVersion: environment.version, revision: 'must-stay-blocked' })).toMatchObject({ status: 409, payload: { error: { code: 'ENVIRONMENT_BUSY' } } })
  expect(await snapshot(page)).toEqual(locked)
  for (const step of [10, 50, 100]) {
    await advance(page, 30)
    const partial = await snapshot(page), execution = partial.entities.serviceExecutions.find(item => item.sourceId === next)!
    expect(execution.kind).toBe('traffic')
    if (execution.kind === 'traffic') expect(execution.checkpoints.some(checkpoint => checkpoint.step === step)).toBe(false)
    await advance(page, 30)
    await expect(page.getByRole('heading', { name: `候選 ${step}% · 已驗證`, exact: true })).toBeVisible()
    await page.reload(); await expect(page.getByRole('heading', { name: `候選 ${step}% · 已驗證`, exact: true })).toBeVisible()
  }
  expect((await source(page, next)).state).toBe('active')
  const completed = await snapshot(page)
  expect(completed.entities.environments.find(item => item.id === 'env-checkout-dev')!.activeReleaseId).toBe(originalActive)
  const execution = completed.entities.serviceExecutions.find(item => item.sourceId === next)!
  if (execution.kind !== 'traffic') throw new Error('Expected traffic execution')
  expect(execution.samples).toHaveLength(6); expect(execution.checkpoints.map(item => item.step)).toEqual([10, 50, 100])
  await info.attach('traffic-proof', { body: JSON.stringify(execution), contentType: 'application/json' })
})

test('W3 traffic: abnormal 50 retains verified10 and all themes/viewports show readable evidence', async ({ page }, info) => {
  await page.goto('rd')
  const candidate = await publish(page, 'w3-abnormal-candidate'), baseline = await publish(page, 'w3-abnormal-baseline')
  const id = await createTraffic(page, baseline, candidate)
  await act(page, '驗證草稿'); await act(page, '開始灰度放量'); await advance(page, 60)
  await page.getByRole('button', { name: '模擬流量健康異常', exact: true }).click(); await advance(page, 30)
  expect((await source(page, id)).state).toBe('failed')
  const execution = (await snapshot(page)).entities.serviceExecutions.find(item => item.sourceId === id)!
  if (execution.kind !== 'traffic') throw new Error('Expected traffic execution')
  expect(execution.checkpoints.map(item => item.step)).toEqual([10]); expect(execution.samples.at(-1)).toMatchObject({ p95LatencyMs: 900, errorRate: 0.08 })
  await expect(page.locator('section').filter({ has: page.getByRole('heading', { name: '目前有效流量', exact: true }) }).last()).toContainText('90%')
  for (const theme of ['light', 'dark'] as const) {
    if (await page.locator('html').getAttribute('data-theme') !== theme) await page.getByRole('button', { name: theme === 'dark' ? '切換深色主題' : '切換淺色主題', exact: true }).click()
    for (const width of [1440, 768, 390]) {
      await page.setViewportSize({ width, height: 1000 })
      await expect(page.getByRole('heading', { name: '目前有效流量', exact: true })).toBeVisible()
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
      const result = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()
      expect(result.violations.filter(item => item.impact === 'serious' || item.impact === 'critical')).toEqual([])
      await info.attach(`traffic-${theme}-${width}`, { body: await page.screenshot({ fullPage: true }), contentType: 'image/png' })
    }
  }
})
