import type { zhTW } from "./zh-TW";

export const en = {
  "app.loading": "Loading…",
  "app.name": "Kith",
  "app.shell.logout": "Sign out",
  "auth.login.handle": "Handle",
  "auth.login.invalidCredentials": "Incorrect handle or password.",
  "auth.login.password": "Password",
  "auth.login.submit": "Sign in",
  "auth.login.submitting": "Signing in…",
  "auth.login.subtitle": "Sign in to continue to Kith",
  "auth.login.title": "Welcome back",
  "composer.label": "Message",
  "composer.offline": "Offline — you can send once reconnected",
  "composer.placeholder": "Message # {room}",
  "composer.send": "Send",
  "composer.tooLong": "Message too long (8 KiB max)",
  "error.boundary.reload": "Reload",
  "error.boundary.title": "Something went wrong on this screen",
  "error.code.forbidden": "You're not a member of this room",
  "error.code.invalid_request": "The message format is invalid",
  "error.code.network_error": "Can't reach the server. Try again shortly.",
  "error.code.payload_too_large": "The message is too long",
  "error.code.unauthorized": "Your session has expired. Sign in again.",
  "error.code.unknown": "Something went wrong. Try again.",
  "error.retry": "Retry",
  "home.greeting": "Hi, {name}",
  "md.code.copied": "Copied",
  "md.code.copy": "Copy code",
  "notFound.home": "Back to home",
  "notFound.title": "Page not found",
  "room.back": "Back to rooms",
  "room.status.connecting": "Connecting…",
  "room.status.offline": "You're offline",
  "room.status.reconnecting": "Connection lost, reconnecting…",
  "rooms.home.body": "Your rooms are on the left. Pick one to start.",
  "rooms.list.empty": "No rooms yet",
  "rooms.list.error": "Couldn't load your rooms",
  "rooms.list.title": "Rooms",
  "rooms.notFound.back": "Back to rooms",
  "rooms.notFound.title": "This room doesn't exist, or you're not a member",
  "timeline.dismiss": "Got it",
  "timeline.empty": "Say hello",
  "timeline.jumpLatest": "{count} new messages",
  "timeline.jumped": "Jumped to the latest; scroll up for earlier messages",
  "timeline.label": "Messages in {room}",
  "timeline.loadingOlder": "Loading earlier messages…",
  "timeline.olderFailed": "Couldn't load earlier messages",
  "timeline.pending.discard": "Discard",
  "timeline.pending.failed": "Failed to send: {reason}",
  "timeline.pending.retry": "Retry",
  "timeline.pending.sending": "Sending…",
  "timeline.pending.unknown": "Resending…",
  "timeline.start.created": "Created {date}",
  "timeline.start.title": "This is the beginning of # {room}",
  "timeline.today": "Today",
  "timeline.unknownSender": "Former member",
  "timeline.yesterday": "Yesterday",
  "timeline.you": "You",
} satisfies Record<keyof typeof zhTW, string>;
