import type { zhTW } from "./zh-TW";

export const en = {
  "app.loading": "Loading…",
  "app.name": "Kith",
  "app.shell.logout": "Sign out",
  "auth.login.handle": "Handle",
  "auth.login.invalidCredentials": "Incorrect handle or password.",
  "auth.login.password": "Password",
  "auth.login.submit": "Sign in",
  "auth.login.submitting": "Signing in…",
  "auth.login.subtitle": "Sign in to continue to Kith",
  "auth.login.title": "Welcome back",
  "composer.archived": "This room is archived; you can't send messages",
  "composer.archivedPlaceholder": "Archived",
  "composer.label": "Message",
  "composer.offline": "Offline — you can send once reconnected",
  "composer.placeholder": "Message # {room}",
  "composer.send": "Send",
  "composer.tooLong": "Message too long (8 KiB max)",
  "console.forbidden.back": "Back to home",
  "console.forbidden.title": "Only the operator can open this page",
  "console.invite.done": "Invited",
  "console.invite.query": "Search by handle or name",
  "console.invite.submit": "Invite {name}",
  "console.invite.title": "Invite to # {room}",
  "console.nav.label": "Console",
  "console.nav.people": "People",
  "console.nav.rooms": "Rooms",
  "console.open": "Console",
  "console.people.add": "Add person",
  "console.people.copied": "Copied",
  "console.people.copy": "Copy handle and password",
  "console.people.createTitle": "Add a person",
  "console.people.createdHelp": "This password is shown only once. They must change it at first sign-in.",
  "console.people.disable": "Disable",
  "console.people.disabled": "Disabled",
  "console.people.displayName": "Display name",
  "console.people.done": "Done",
  "console.people.enable": "Enable",
  "console.people.handle": "Handle",
  "console.people.handleInvalid": "Use 2–32 lowercase letters, digits or underscores",
  "console.people.handleTaken": "That handle is taken",
  "console.people.initialPassword": "Initial password",
  "console.people.mustChange": "Must change password",
  "console.people.operator": "Operator",
  "console.people.passwordInvalid": "Passwords need 12–128 characters",
  "console.people.regenerate": "Regenerate",
  "console.people.reset": "Reset password",
  "console.people.resetTitle": "Reset {name}'s password",
  "console.people.submit": "Create",
  "console.people.title": "People",
  "console.rooms.archive": "Archive",
  "console.rooms.archiveConfirm": "Archive",
  "console.rooms.archiveHelp": "Everyone can still read, nobody can post, and agents won't wake. You can unarchive at any time.",
  "console.rooms.archiveTitle": "Archive # {room}?",
  "console.rooms.archived": "Archived",
  "console.rooms.cancel": "Cancel",
  "console.rooms.invite": "Invite",
  "console.rooms.members": "{n} members",
  "console.rooms.rename": "Rename",
  "console.rooms.renameSubmit": "Save",
  "console.rooms.renameTitle": "Rename room",
  "console.rooms.title": "Rooms",
  "console.rooms.unarchive": "Unarchive",
  "error.boundary.reload": "Reload",
  "error.boundary.title": "Something went wrong on this screen",
  "error.code.already_member": "They're already in this room",
  "error.code.forbidden": "You're not a member of this room",
  "error.code.handle_taken": "Already taken",
  "error.code.invalid_request": "The message format is invalid",
  "error.code.last_owner": "You can't remove the last owner",
  "error.code.network_error": "Can't reach the server. Try again shortly.",
  "error.code.not_found": "Not found",
  "error.code.payload_too_large": "The message is too long",
  "error.code.room_archived": "The room is archived",
  "error.code.room_full": "The room is full (32 members)",
  "error.code.unauthorized": "Your session has expired. Sign in again.",
  "error.code.unknown": "Something went wrong. Try again.",
  "error.code.wrong_password": "The current password is wrong",
  "error.retry": "Retry",
  "home.firstRun.title": "Welcome — start with your first room",
  "home.greeting": "Hi, {name}",
  "home.guide.people.body": "Create accounts for people, then invite them",
  "home.guide.people.title": "Add people",
  "home.guide.room.body": "A room is one conversation; people and AI are members",
  "home.guide.room.title": "Create a room",
  "home.noRooms": "Nobody has invited you to a room yet. Ask {operator}.",
  "md.code.copied": "Copied",
  "md.code.copy": "Copy code",
  "members.agentTitle": "AI member",
  "members.attention": "Wake settings",
  "members.attentionCooldown": "Cooldown in seconds (leave empty to keep)",
  "members.attentionHelp.ambient": "May join in on its own (operator must enable)",
  "members.attentionHelp.keyword": "Wakes when a message contains a keyword",
  "members.attentionHelp.mention": "Wakes when @mentioned",
  "members.attentionHelp.silent": "Never wakes",
  "members.attentionKeywords": "Keywords (comma-separated)",
  "members.attentionMode.ambient": "Ambient",
  "members.attentionMode.keyword": "Keyword",
  "members.attentionMode.mention": "On mention",
  "members.attentionMode.silent": "Silent",
  "members.attentionSubmit": "Save",
  "members.attentionTitle": "Wake settings for {name}",
  "members.back": "Back to members",
  "members.cancel": "Cancel",
  "members.close": "Close members",
  "members.detail.attention": "Wake setting in this room",
  "members.detail.limit": "Limits",
  "members.detail.wake": "Who can wake it",
  "members.detail.wakeAnyone": "Anyone in the room",
  "members.detail.wakeOperator": "Only the operator",
  "members.groupAgents": "AI ({n})",
  "members.groupHumans": "People ({n})",
  "members.invite": "Invite",
  "members.limit.fixed": "Fixed reply only: {text}",
  "members.limit.sidecarOff": "Not enabled · Requires the operator's computer",
  "members.loadError": "Couldn't load members",
  "members.loading": "Loading members…",
  "members.menu": "More actions for {name}",
  "members.open": "Members ({n})",
  "members.operatorOnly": "Operator only",
  "members.owner": "Owner",
  "members.remove": "Remove from room",
  "members.removeConfirm": "Remove",
  "members.removeHelp": "They won't see this room any more. Past messages stay.",
  "members.removeTitle": "Remove {name} from this room?",
  "members.title": "Members",
  "members.you": "(you)",
  "mention.label": "Mention a member",
  "message.actions": "Message actions",
  "message.copied": "Copied",
  "message.copy": "Copy text",
  "message.details": "View details",
  "message.detailsTitle": "Message details",
  "notFound.home": "Back to home",
  "notFound.title": "Page not found",
  "reply.failed": "{name} couldn't reply",
  "reply.failedWithReason": "{name} couldn't reply: {reason}",
  "reply.reason.auth": "the model service rejected the credentials",
  "reply.reason.busy": "the provider is busy",
  "reply.reason.notFound": "the model doesn't exist",
  "reply.reason.other": "something went wrong",
  "reply.reason.refused": "the model declined to answer",
  "reply.reason.unreachable": "couldn't reach the model service",
  "reply.replying": "{name} is replying",
  "room.archived.banner": "This room is archived. It's read-only.",
  "room.archived.unarchive": "Unarchive",
  "room.back": "Back to rooms",
  "room.status.connecting": "Connecting…",
  "room.status.offline": "You're offline",
  "room.status.reconnecting": "Connection lost, reconnecting…",
  "rooms.create.cancel": "Cancel",
  "rooms.create.name": "Room name",
  "rooms.create.nameInvalid": "Names need 1–80 characters",
  "rooms.create.open": "New room",
  "rooms.create.slug": "URL slug",
  "rooms.create.slugHelp": "The room URL will be /r/{slug} and can't change later",
  "rooms.create.slugInvalid": "Use 1–40 lowercase letters, digits or hyphens; no leading or trailing hyphen",
  "rooms.create.slugTaken": "Another room already uses this slug",
  "rooms.create.submit": "Create",
  "rooms.create.title": "Create a room",
  "rooms.home.body": "Your rooms are on the left. Pick one to start.",
  "rooms.list.archived": "Archived ({n})",
  "rooms.list.emptyMember": "Nobody has invited you to a room yet",
  "rooms.list.error": "Couldn't load your rooms",
  "rooms.list.justNow": "now",
  "rooms.list.minutesAgo": "{n}m",
  "rooms.list.title": "Rooms",
  "rooms.notFound.back": "Back to rooms",
  "rooms.notFound.title": "This room doesn't exist, or you're not a member",
  "rooms.search.label": "Search rooms",
  "rooms.search.noMatch": "No matching rooms",
  "rooms.search.placeholder": "Search rooms",
  "settings.displayName.invalid": "Display names need 1–64 characters",
  "settings.displayName.label": "Display name",
  "settings.displayName.save": "Save",
  "settings.force.banner": "Welcome! Set your own password to continue.",
  "settings.password.confirm": "Confirm new password",
  "settings.password.mismatch": "The new passwords don't match",
  "settings.password.new": "New password",
  "settings.password.old": "Current password",
  "settings.password.save": "Update password",
  "settings.password.title": "Password",
  "settings.password.tooShort": "Passwords need 12–128 characters",
  "settings.password.wrongOld": "Your current password is wrong",
  "settings.profile.title": "Profile",
  "settings.saved": "Saved",
  "settings.title": "Settings",
  "shortcuts.escape": "Close panels; jump to the latest in the timeline",
  "shortcuts.help": "Show shortcuts",
  "shortcuts.nextRoom": "Previous / next room",
  "shortcuts.nextUnread": "Previous / next unread room",
  "shortcuts.switcher": "Quick switch rooms",
  "shortcuts.title": "Keyboard shortcuts",
  "switcher.empty": "No matching rooms",
  "switcher.placeholder": "Type a room name…",
  "switcher.title": "Switch room",
  "timeline.dismiss": "Got it",
  "timeline.empty": "Say hello",
  "timeline.jumpLatest": "{count} new messages",
  "timeline.jumped": "Jumped to the latest; scroll up for earlier messages",
  "timeline.label": "Messages in {room}",
  "timeline.loadingOlder": "Loading earlier messages…",
  "timeline.newMessages": "New messages",
  "timeline.olderFailed": "Couldn't load earlier messages",
  "timeline.pending.discard": "Discard",
  "timeline.pending.failed": "Failed to send: {reason}",
  "timeline.pending.retry": "Retry",
  "timeline.pending.sending": "Sending…",
  "timeline.pending.unknown": "Resending…",
  "timeline.start.created": "Created {date}",
  "timeline.start.title": "This is the beginning of # {room}",
  "timeline.today": "Today",
  "timeline.unknownSender": "Former member",
  "timeline.yesterday": "Yesterday",
  "timeline.you": "You",
  "typing.many": "{n} people are typing…",
  "typing.one": "{a} is typing…",
  "typing.two": "{a} and {b} are typing…",
  "user.menu.language": "Language",
  "user.menu.settings": "Settings",
  "user.menu.theme": "Theme",
  "user.menu.themeDark": "Dark",
  "user.menu.themeLight": "Light",
  "user.menu.themeSystem": "System",
} satisfies Record<keyof typeof zhTW, string>;
