export const zhTW = {
  "app.loading": "載入中…",
  "app.name": "Kith",
  "app.shell.logout": "登出",
  "auth.login.handle": "帳號（handle）",
  "auth.login.invalidCredentials": "帳號或密碼不正確。",
  "auth.login.password": "密碼",
  "auth.login.submit": "登入",
  "auth.login.submitting": "登入中…",
  "auth.login.subtitle": "登入以繼續使用 Kith",
  "auth.login.title": "歡迎回來",
  "composer.archived": "這個房間已封存，無法送出訊息",
  "composer.archivedPlaceholder": "已封存",
  "composer.label": "訊息",
  "composer.offline": "離線中，恢復連線後才能送出",
  "composer.placeholder": "傳訊息到 # {room}",
  "composer.send": "送出",
  "composer.tooLong": "訊息太長（上限 8 KiB）",
  "console.forbidden.back": "回到首頁",
  "console.forbidden.title": "這裡只有 operator 能進入",
  "console.invite.done": "已邀請",
  "console.invite.query": "搜尋 handle 或名字",
  "console.invite.submit": "邀請 {name}",
  "console.invite.title": "邀請到 # {room}",
  "console.nav.label": "控制台",
  "console.nav.people": "成員",
  "console.nav.rooms": "房間",
  "console.open": "控制台",
  "console.people.add": "新增成員",
  "console.people.copied": "已複製",
  "console.people.copy": "複製帳號與密碼",
  "console.people.createTitle": "新增成員",
  "console.people.createdHelp": "這組密碼只會顯示這一次；對方第一次登入時必須改密碼。",
  "console.people.disable": "停用",
  "console.people.disabled": "已停用",
  "console.people.displayName": "顯示名稱",
  "console.people.done": "完成",
  "console.people.enable": "啟用",
  "console.people.handle": "帳號（handle）",
  "console.people.handleInvalid": "只能用小寫英文、數字與底線，2–32 個字",
  "console.people.handleTaken": "這個 handle 已經有人用了",
  "console.people.initialPassword": "初始密碼",
  "console.people.mustChange": "需改密碼",
  "console.people.operator": "operator",
  "console.people.passwordInvalid": "密碼需要 12–128 個字",
  "console.people.regenerate": "重新產生",
  "console.people.reset": "重設密碼",
  "console.people.resetTitle": "重設 {name} 的密碼",
  "console.people.submit": "建立",
  "console.people.title": "成員",
  "console.rooms.archive": "封存",
  "console.rooms.archiveConfirm": "封存",
  "console.rooms.archiveHelp": "封存後所有人只能閱讀，agent 不會被喚醒；可以隨時解除封存。",
  "console.rooms.archiveTitle": "封存 # {room}？",
  "console.rooms.archived": "已封存",
  "console.rooms.cancel": "取消",
  "console.rooms.invite": "邀請",
  "console.rooms.members": "{n} 位成員",
  "console.rooms.rename": "改名",
  "console.rooms.renameSubmit": "儲存",
  "console.rooms.renameTitle": "重新命名房間",
  "console.rooms.title": "房間",
  "console.rooms.unarchive": "解除封存",
  "error.boundary.reload": "重新載入",
  "error.boundary.title": "畫面發生錯誤",
  "error.code.already_member": "對方已經在這個房間了",
  "error.code.forbidden": "你不是這個房間的成員",
  "error.code.handle_taken": "已經被使用了",
  "error.code.invalid_request": "訊息格式不正確",
  "error.code.network_error": "無法連線到伺服器，請稍後再試。",
  "error.code.not_found": "找不到",
  "error.code.payload_too_large": "訊息太長",
  "error.code.room_archived": "房間已封存",
  "error.code.room_full": "房間已滿（32 人）",
  "error.code.unauthorized": "登入已失效，請重新登入。",
  "error.code.unknown": "發生錯誤，請再試一次。",
  "error.code.wrong_password": "舊密碼不正確",
  "error.retry": "重試",
  "home.firstRun.title": "歡迎，先建立第一個房間",
  "home.greeting": "你好，{name}",
  "home.guide.people.body": "為家人朋友建立帳號，再邀請進房間",
  "home.guide.people.title": "新增成員",
  "home.guide.room.body": "一個房間是一段對話，人和 AI 都是成員",
  "home.guide.room.title": "建立房間",
  "home.noRooms": "還沒有人邀請你加入房間。請聯絡 {operator}。",
  "md.code.copied": "已複製",
  "md.code.copy": "複製程式碼",
  "notFound.home": "回到首頁",
  "notFound.title": "找不到這個頁面",
  "room.archived.banner": "這個房間已封存，只能閱讀。",
  "room.archived.unarchive": "解除封存",
  "room.back": "返回房間列表",
  "room.status.connecting": "連線中…",
  "room.status.offline": "目前離線",
  "room.status.reconnecting": "連線中斷，重新連線中…",
  "rooms.create.cancel": "取消",
  "rooms.create.name": "房間名稱",
  "rooms.create.nameInvalid": "名稱需要 1–80 個字",
  "rooms.create.open": "新房間",
  "rooms.create.slug": "網址代稱",
  "rooms.create.slugHelp": "房間網址會是 /r/{slug}，建立後不能改",
  "rooms.create.slugInvalid": "只能用小寫英文、數字與連字號，1–40 個字，不能以連字號開頭或結尾",
  "rooms.create.slugTaken": "這個代稱已經有房間使用",
  "rooms.create.submit": "建立",
  "rooms.create.title": "建立房間",
  "rooms.home.body": "左邊是你加入的房間，選一個開始。",
  "rooms.list.archived": "已封存（{n}）",
  "rooms.list.emptyMember": "還沒有人邀請你加入房間",
  "rooms.list.error": "無法載入房間列表",
  "rooms.list.justNow": "剛剛",
  "rooms.list.minutesAgo": "{n} 分鐘",
  "rooms.list.title": "房間",
  "rooms.notFound.back": "回到房間列表",
  "rooms.notFound.title": "找不到這個房間，或你不是成員",
  "rooms.search.label": "搜尋房間",
  "rooms.search.noMatch": "沒有符合的房間",
  "rooms.search.placeholder": "搜尋房間",
  "settings.displayName.invalid": "顯示名稱需要 1–64 個字",
  "settings.displayName.label": "顯示名稱",
  "settings.displayName.save": "儲存",
  "settings.force.banner": "第一次登入，請先設定你自己的密碼。",
  "settings.password.confirm": "再輸入一次新密碼",
  "settings.password.mismatch": "兩次輸入的新密碼不同",
  "settings.password.new": "新密碼",
  "settings.password.old": "目前的密碼",
  "settings.password.save": "更新密碼",
  "settings.password.title": "密碼",
  "settings.password.tooShort": "密碼需要 12–128 個字",
  "settings.password.wrongOld": "目前的密碼不正確",
  "settings.profile.title": "個人資料",
  "settings.saved": "已儲存",
  "settings.title": "設定",
  "timeline.dismiss": "知道了",
  "timeline.empty": "打個招呼吧",
  "timeline.jumpLatest": "{count} 則新訊息",
  "timeline.jumped": "已跳到最新；較早的訊息往上捲動載入",
  "timeline.label": "{room} 的訊息",
  "timeline.loadingOlder": "正在載入較早的訊息…",
  "timeline.newMessages": "新訊息",
  "timeline.olderFailed": "無法載入較早的訊息",
  "timeline.pending.discard": "刪除",
  "timeline.pending.failed": "送出失敗：{reason}",
  "timeline.pending.retry": "重試",
  "timeline.pending.sending": "送出中…",
  "timeline.pending.unknown": "重新送出中…",
  "timeline.start.created": "建立於 {date}",
  "timeline.start.title": "這是 # {room} 的開頭",
  "timeline.today": "今天",
  "timeline.unknownSender": "已離開的成員",
  "timeline.yesterday": "昨天",
  "timeline.you": "你",
  "user.menu.language": "語言",
  "user.menu.settings": "設定",
  "user.menu.theme": "主題",
  "user.menu.themeDark": "深色",
  "user.menu.themeLight": "淺色",
  "user.menu.themeSystem": "跟隨系統",
} as const;
