export const zhTW = {
  "app.loading": "載入中…",
  "app.name": "Kith",
  "app.shell.logout": "登出",
  "auth.login.handle": "帳號（handle）",
  "auth.login.invalidCredentials": "帳號或密碼不正確。",
  "auth.login.password": "密碼",
  "auth.login.submit": "登入",
  "auth.login.submitting": "登入中…",
  "auth.login.subtitle": "登入以繼續使用 Kith",
  "auth.login.title": "歡迎回來",
  "common.cancel": "取消",
  "common.copied": "已複製",
  "common.copy": "複製",
  "common.save": "儲存",
  "common.saved": "已儲存",
  "composer.archived": "這個房間已封存，無法送出訊息",
  "composer.archivedPlaceholder": "已封存",
  "composer.label": "訊息",
  "composer.offline": "離線中，恢復連線後才能送出",
  "composer.placeholder": "傳訊息到 # {room}",
  "composer.send": "送出",
  "composer.tooLong": "訊息太長（上限 8 KiB）",
  "console.agents.adapter.claude_code": "Claude Code",
  "console.agents.adapter.codex": "Codex CLI",
  "console.agents.adapter.command": "自訂指令",
  "console.agents.adapter.gemini_cli": "Gemini CLI",
  "console.agents.adapterLabel": "CLI 種類",
  "console.agents.add": "新增 agent",
  "console.agents.addProvider": "新增連線",
  "console.agents.addendum": "附加系統提示",
  "console.agents.apply": "套用",
  "console.agents.back": "上一步",
  "console.agents.changeLine": "{time} {name}：{from} → {to}",
  "console.agents.changeTitle": "套用新的執行方式？",
  "console.agents.connection": "模型連線",
  "console.agents.create": "建立",
  "console.agents.disable": "停用",
  "console.agents.displayName": "顯示名稱",
  "console.agents.doneHosted": "已建立。把它邀請進房間後，@ 它就會回覆。",
  "console.agents.effectInflight": "正在進行的回覆會被丟棄，不會以新設定送出。",
  "console.agents.effectKind": "執行方式：{from} → {to}",
  "console.agents.effectNoDispatch": "Kith 不會替它呼叫模型；它要自己連進來。",
  "console.agents.effectQuota": "額度：{from} → {to}",
  "console.agents.empty": "還沒有 agent。",
  "console.agents.enable": "啟用",
  "console.agents.epoch": "設定版本 {n}",
  "console.agents.finish": "完成",
  "console.agents.handle": "Handle",
  "console.agents.kind.external": "External：任何 MCP client",
  "console.agents.kind.hosted": "Hosted：由 Kith 呼叫模型",
  "console.agents.kind.runner": "Runner：在你的主機上執行 CLI",
  "console.agents.kindHelp.external": "持 bot token 的程式自行決定何時發言。",
  "console.agents.kindHelp.hosted": "選一個模型連線與模型。不帶任何工具。",
  "console.agents.kindHelp.runner": "用 bot token 連線的 kith-runner 啟動 CLI。",
  "console.agents.maxTokens": "最多輸出 token",
  "console.agents.maxTokensInvalid": "1 到 8192 的整數",
  "console.agents.model": "模型",
  "console.agents.modelFree": "輸入模型名稱",
  "console.agents.modelListFailed": "取不到模型清單，請直接輸入",
  "console.agents.modelRequired": "請選擇或輸入模型",
  "console.agents.next": "下一步",
  "console.agents.noProvider": "還沒有模型連線。",
  "console.agents.noRooms": "還沒有加入任何房間",
  "console.agents.notFound": "找不到這個 agent",
  "console.agents.openAgent": "前往 agent",
  "console.agents.quota.api_key": "API 金鑰（房內任何人都能喚醒）",
  "console.agents.quota.operator_personal": "我的個人訂閱（只有我能喚醒）",
  "console.agents.quotaQuestion": "這個 agent 用什麼額度？",
  "console.agents.revokeTokens": "同時撤銷此 agent 的所有 token（{n} 把）",
  "console.agents.roomAdd": "加入房間",
  "console.agents.roomRemove": "移出",
  "console.agents.roomsCount": "{n} 個房間",
  "console.agents.runnerLater": "runner 程式在之後的版本提供；現在設定後會顯示為「runner 未連線」。",
  "console.agents.runnerNever": "尚未連線",
  "console.agents.runnerSeen": "最近上線 {time}",
  "console.agents.runtime.external": "External",
  "console.agents.runtime.hostedWith": "Hosted · {connection} · {model}",
  "console.agents.runtime.runnerWith": "Runner · {adapter}",
  "console.agents.runtime.v1": "v1 設定",
  "console.agents.runtimePending": "agent 已建立，但執行方式還沒設定成功。請在下方重新儲存。",
  "console.agents.runtimeSaved": "已套用，設定版本 {n}",
  "console.agents.snippetExternal": "MCP 設定",
  "console.agents.snippetRunner": "runner.toml 片段",
  "console.agents.status.connection_error": "連線錯誤",
  "console.agents.status.disabled": "已停用",
  "console.agents.status.ok": "可回覆",
  "console.agents.status.runner_offline": "runner 未連線",
  "console.agents.status.unconfigured": "未設定",
  "console.agents.stepBasic": "基本資料",
  "console.agents.stepDone": "完成",
  "console.agents.stepRuntime": "執行方式",
  "console.agents.stream": "邊產生邊顯示",
  "console.agents.streamHelp": "伺服器開啟串流功能時才有效；否則回覆完成後一次顯示",
  "console.agents.tab.generations": "回覆紀錄",
  "console.agents.tab.overview": "概覽",
  "console.agents.tab.rooms": "房間",
  "console.agents.tab.runtime": "執行方式",
  "console.agents.tab.tokens": "Token",
  "console.agents.temperature": "Temperature",
  "console.agents.temperatureHelp": "部分新模型只接受預設值；留空最安全",
  "console.agents.temperatureInvalid": "0 到 2",
  "console.agents.title": "Agents",
  "console.agents.tokenLabel": "Bot token",
  "console.agents.tokenOnce": "關閉後無法再看到這個 token。",
  "console.agents.tokensCount": "{n} 把 token",
  "console.errorClass.auth": "憑證被拒絕",
  "console.errorClass.bad_request": "請求不被接受",
  "console.errorClass.content_filter": "模型拒絕回答",
  "console.errorClass.context_length": "內容太長",
  "console.errorClass.network": "連不上",
  "console.errorClass.not_found": "找不到（模型或網址）",
  "console.errorClass.overloaded": "服務忙碌",
  "console.errorClass.protocol": "回應格式不對",
  "console.errorClass.rate_limited": "被限流",
  "console.errorClass.timeout": "逾時",
  "console.errorClass.unknown": "未知錯誤",
  "console.forbidden.back": "回到首頁",
  "console.forbidden.title": "這裡只有 operator 能進入",
  "console.generations.duration": "{s} 秒",
  "console.generations.empty": "還沒有回覆紀錄",
  "console.generations.refresh": "重新整理",
  "console.generations.room": "# {room}",
  "console.generations.state.completed": "完成",
  "console.generations.state.dispatched": "已送出",
  "console.generations.state.dropped": "未送出",
  "console.generations.state.failed": "失敗",
  "console.generations.state.queued": "排隊中",
  "console.generations.state.streaming": "進行中",
  "console.generations.tokens": "{in} → {out} tokens",
  "console.invite.done": "已邀請",
  "console.invite.query": "搜尋 handle 或名字",
  "console.invite.submit": "邀請 {name}",
  "console.invite.title": "邀請到 # {room}",
  "console.nav.agents": "Agents",
  "console.nav.label": "控制台",
  "console.nav.people": "成員",
  "console.nav.providers": "模型連線",
  "console.nav.rooms": "房間",
  "console.open": "控制台",
  "console.people.add": "新增成員",
  "console.people.copied": "已複製",
  "console.people.copy": "複製帳號與密碼",
  "console.people.createTitle": "新增成員",
  "console.people.createdHelp": "這組密碼只會顯示這一次；對方第一次登入時必須改密碼。",
  "console.people.disable": "停用",
  "console.people.disabled": "已停用",
  "console.people.displayName": "顯示名稱",
  "console.people.done": "完成",
  "console.people.enable": "啟用",
  "console.people.handle": "帳號（handle）",
  "console.people.handleInvalid": "只能用小寫英文、數字與底線，2–32 個字",
  "console.people.handleTaken": "這個 handle 已經有人用了",
  "console.people.initialPassword": "初始密碼",
  "console.people.mustChange": "需改密碼",
  "console.people.operator": "operator",
  "console.people.passwordInvalid": "密碼需要 12–128 個字",
  "console.people.regenerate": "重新產生",
  "console.people.reset": "重設密碼",
  "console.people.resetTitle": "重設 {name} 的密碼",
  "console.people.submit": "建立",
  "console.people.title": "成員",
  "console.providers.add": "新增連線",
  "console.providers.advanced": "進階",
  "console.providers.agentCount": "{n} 個 agent 使用",
  "console.providers.baseUrlLabel": "Base URL",
  "console.providers.delete": "刪除",
  "console.providers.deleteHelp": "刪除後無法復原。",
  "console.providers.deleteInUse": "{n} 個 agent 正在使用；刪除後它們會停止回覆，直到重新設定。",
  "console.providers.deleteTitle": "刪除 {name}？",
  "console.providers.disable": "停用",
  "console.providers.empty": "還沒有連線。新增一個，hosted agent 才能回覆。",
  "console.providers.enable": "啟用",
  "console.providers.format.anthropic_messages": "Anthropic Messages",
  "console.providers.format.gemini": "Google Gemini",
  "console.providers.format.openai_chat": "OpenAI 相容",
  "console.providers.format.openai_responses": "OpenAI Responses",
  "console.providers.formatLabel": "API 格式",
  "console.providers.headers": "額外 header（每行「名稱: 值」）",
  "console.providers.headersInvalid": "每行必須是「名稱: 值」",
  "console.providers.keyEnv": "環境變數 {name}",
  "console.providers.keyLast4": "金鑰 …{last4}",
  "console.providers.keyNone": "不需要金鑰",
  "console.providers.nameInvalid": "1–48 個英數字、空白、點、底線或連字號，第一個字必須是英數字",
  "console.providers.nameLabel": "名稱",
  "console.providers.noSecretsKey": "伺服器沒有設定 KITH_SECRETS_KEY，只能引用環境變數中的金鑰。",
  "console.providers.personal": "個人訂閱",
  "console.providers.personalNo": "否，是 API 金鑰（房內任何人都能喚醒）",
  "console.providers.personalQuestion": "這個連線背後是個人訂閱嗎？",
  "console.providers.personalYes": "是，個人訂閱（只有 operator 能喚醒）",
  "console.providers.preset.anthropic": "Anthropic",
  "console.providers.preset.custom": "自訂",
  "console.providers.preset.deepseek": "DeepSeek",
  "console.providers.preset.google": "Google Gemini",
  "console.providers.preset.groq": "Groq",
  "console.providers.preset.mistral": "Mistral",
  "console.providers.preset.openai": "OpenAI",
  "console.providers.preset.openrouter": "OpenRouter",
  "console.providers.preset.xai": "xAI",
  "console.providers.presetLabel": "服務",
  "console.providers.save": "儲存連線",
  "console.providers.secretEnv": "引用伺服器環境變數",
  "console.providers.secretEnvLabel": "環境變數名稱",
  "console.providers.secretInvalid": "金鑰前後不能有空白，也不能包含換行",
  "console.providers.secretKeep": "…{last4}，留空表示不變",
  "console.providers.secretLabel": "API 金鑰",
  "console.providers.secretNone": "不需要金鑰",
  "console.providers.secretSource": "金鑰來源",
  "console.providers.secretStored": "貼上金鑰（加密保存）",
  "console.providers.status.disabled": "已停用",
  "console.providers.status.error": "錯誤：{reason}",
  "console.providers.status.ok": "正常",
  "console.providers.status.untested": "未測試",
  "console.providers.test": "測試連線",
  "console.providers.testFailed": "連線失敗：{reason}",
  "console.providers.testOk": "連線成功，{n} 個模型",
  "console.providers.testOkNoList": "連線成功（這個服務不提供模型清單）",
  "console.providers.testSaveFirst": "先儲存再測試",
  "console.providers.testing": "測試中…",
  "console.providers.title": "模型連線",
  "console.providers.tokenParam": "輸出長度參數",
  "console.rooms.archive": "封存",
  "console.rooms.archiveConfirm": "封存",
  "console.rooms.archiveHelp": "封存後所有人只能閱讀，agent 不會被喚醒；可以隨時解除封存。",
  "console.rooms.archiveTitle": "封存 # {room}？",
  "console.rooms.archived": "已封存",
  "console.rooms.cancel": "取消",
  "console.rooms.invite": "邀請",
  "console.rooms.members": "{n} 位成員",
  "console.rooms.rename": "改名",
  "console.rooms.renameSubmit": "儲存",
  "console.rooms.renameTitle": "重新命名房間",
  "console.rooms.title": "房間",
  "console.rooms.unarchive": "解除封存",
  "console.tokens.empty": "沒有 token",
  "console.tokens.expired": "已過期",
  "console.tokens.issue": "簽發新 token",
  "console.tokens.lastUsed": "最近使用 {time}",
  "console.tokens.neverUsed": "尚未使用",
  "console.tokens.revoke": "撤銷",
  "console.tokens.revokeHelp": "使用這把 token 的程式會立即收到 401。",
  "console.tokens.revokeTitle": "撤銷這把 token？",
  "console.tokens.revokedAt": "已於 {time} 撤銷",
  "error.boundary.reload": "重新載入",
  "error.boundary.title": "畫面發生錯誤",
  "error.code.already_member": "對方已經在這個房間了",
  "error.code.forbidden": "你不是這個房間的成員",
  "error.code.handle_taken": "已經被使用了",
  "error.code.in_use": "仍有 agent 使用這個連線",
  "error.code.invalid_request": "訊息格式不正確",
  "error.code.last_owner": "不能移出最後一位房主",
  "error.code.name_taken": "這個名稱已被使用",
  "error.code.network_error": "無法連線到伺服器，請稍後再試。",
  "error.code.not_found": "找不到",
  "error.code.payload_too_large": "訊息太長",
  "error.code.provider_disabled": "這個連線已停用",
  "error.code.room_archived": "房間已封存",
  "error.code.room_full": "房間已滿（32 人）",
  "error.code.secret_unavailable": "伺服器上找不到這個金鑰",
  "error.code.secrets_key_missing": "伺服器沒有設定加密金鑰，請改用環境變數",
  "error.code.unauthorized": "登入已失效，請重新登入。",
  "error.code.unknown": "發生錯誤，請再試一次。",
  "error.code.wrong_password": "舊密碼不正確",
  "error.retry": "重試",
  "form.bytes": "{n} / {max} 位元組",
  "home.firstRun.title": "歡迎，先建立第一個房間",
  "home.greeting": "你好，{name}",
  "home.guide.people.body": "為家人朋友建立帳號，再邀請進房間",
  "home.guide.people.title": "新增成員",
  "home.guide.room.body": "一個房間是一段對話，人和 AI 都是成員",
  "home.guide.room.title": "建立房間",
  "home.noRooms": "還沒有人邀請你加入房間。請聯絡 {operator}。",
  "md.code.copied": "已複製",
  "md.code.copy": "複製程式碼",
  "members.agentTitle": "AI 成員",
  "members.attention": "喚醒方式",
  "members.attentionCooldown": "冷卻秒數（留空表示不變）",
  "members.attentionHelp.ambient": "會主動判斷要不要插話（需要 operator 開啟）",
  "members.attentionHelp.keyword": "訊息含關鍵字時喚醒",
  "members.attentionHelp.mention": "被 @ 時喚醒",
  "members.attentionHelp.silent": "永遠不會被喚醒",
  "members.attentionKeywords": "關鍵字（以逗號分隔）",
  "members.attentionMode.ambient": "主動",
  "members.attentionMode.keyword": "關鍵字",
  "members.attentionMode.mention": "被 @ 時",
  "members.attentionMode.silent": "安靜",
  "members.attentionSubmit": "儲存",
  "members.attentionTitle": "{name} 的喚醒方式",
  "members.back": "返回成員列表",
  "members.cancel": "取消",
  "members.close": "關閉成員面板",
  "members.detail.attention": "在這個房間的喚醒方式",
  "members.detail.editInConsole": "在控制台編輯",
  "members.detail.limit": "限制",
  "members.detail.model": "模型",
  "members.detail.runtime": "執行方式",
  "members.detail.runtimeV1": "hosted（v1 設定）",
  "members.detail.wake": "誰能喚醒",
  "members.detail.wakeAnyone": "房內的人都能喚醒",
  "members.detail.wakeOperator": "只有 operator 能喚醒",
  "members.groupAgents": "AI（{n}）",
  "members.groupHumans": "人（{n}）",
  "members.invite": "邀請",
  "members.limit.connection_error": "模型連線出錯，不會回覆",
  "members.limit.disabled": "已停用",
  "members.limit.external": "外部程式，Kith 不保證它遵守喚醒規則",
  "members.limit.fixed": "只會回固定文字：{text}",
  "members.limit.runner_offline": "runner 未連線，不會回覆",
  "members.limit.sidecarOff": "未啟用 · 需要 operator 的電腦",
  "members.limit.unconfigured": "尚未設定，不會回覆",
  "members.loadError": "無法載入成員",
  "members.loading": "正在載入成員…",
  "members.menu": "{name} 的更多動作",
  "members.open": "成員（{n}）",
  "members.operatorOnly": "只有 operator 能喚醒",
  "members.owner": "房主",
  "members.remove": "移出房間",
  "members.removeConfirm": "移出",
  "members.removeHelp": "對方不會再看到這個房間；過去的訊息保留。",
  "members.removeTitle": "把 {name} 移出房間？",
  "members.title": "成員",
  "members.you": "（你）",
  "mention.label": "提及成員",
  "message.actions": "訊息動作",
  "message.copied": "已複製",
  "message.copy": "複製文字",
  "message.details": "查看詳細資料",
  "message.detailsTitle": "訊息詳細資料",
  "message.replyInThread": "在 thread 回覆",
  "notFound.home": "回到首頁",
  "notFound.title": "找不到這個頁面",
  "reply.accepted": "{name} 已接受",
  "reply.blocked": "{name} 沒有完成",
  "reply.failed": "{name} 回覆失敗",
  "reply.failedWithReason": "{name} 回覆失敗：{reason}",
  "reply.reason.auth": "模型服務拒絕了憑證",
  "reply.reason.busy": "上游忙碌",
  "reply.reason.notFound": "模型不存在",
  "reply.reason.other": "回覆失敗",
  "reply.reason.refused": "模型拒絕回答",
  "reply.reason.unreachable": "連不上模型服務",
  "reply.replying": "{name} 正在回覆",
  "reply.running": "{name} 執行中",
  "room.archived.banner": "這個房間已封存，只能閱讀。",
  "room.archived.unarchive": "解除封存",
  "room.back": "返回房間列表",
  "room.status.connecting": "連線中…",
  "room.status.offline": "目前離線",
  "room.status.reconnecting": "連線中斷，重新連線中…",
  "rooms.create.cancel": "取消",
  "rooms.create.name": "房間名稱",
  "rooms.create.nameInvalid": "名稱需要 1–80 個字",
  "rooms.create.open": "新房間",
  "rooms.create.slug": "網址代稱",
  "rooms.create.slugHelp": "房間網址會是 /r/{slug}，建立後不能改",
  "rooms.create.slugInvalid": "只能用小寫英文、數字與連字號，1–40 個字，不能以連字號開頭或結尾",
  "rooms.create.slugTaken": "這個代稱已經有房間使用",
  "rooms.create.submit": "建立",
  "rooms.create.title": "建立房間",
  "rooms.home.body": "左邊是你加入的房間，選一個開始。",
  "rooms.list.archived": "已封存（{n}）",
  "rooms.list.emptyMember": "還沒有人邀請你加入房間",
  "rooms.list.error": "無法載入房間列表",
  "rooms.list.justNow": "剛剛",
  "rooms.list.minutesAgo": "{n} 分鐘",
  "rooms.list.title": "房間",
  "rooms.notFound.back": "回到房間列表",
  "rooms.notFound.title": "找不到這個房間，或你不是成員",
  "rooms.search.label": "搜尋房間",
  "rooms.search.noMatch": "沒有符合的房間",
  "rooms.search.placeholder": "搜尋房間",
  "settings.displayName.invalid": "顯示名稱需要 1–64 個字",
  "settings.displayName.label": "顯示名稱",
  "settings.displayName.save": "儲存",
  "settings.force.banner": "第一次登入，請先設定你自己的密碼。",
  "settings.password.confirm": "再輸入一次新密碼",
  "settings.password.mismatch": "兩次輸入的新密碼不同",
  "settings.password.new": "新密碼",
  "settings.password.old": "目前的密碼",
  "settings.password.save": "更新密碼",
  "settings.password.title": "密碼",
  "settings.password.tooShort": "密碼需要 12–128 個字",
  "settings.password.wrongOld": "目前的密碼不正確",
  "settings.profile.title": "個人資料",
  "settings.saved": "已儲存",
  "settings.title": "設定",
  "shortcuts.escape": "關閉面板；在時間線時捲到最新",
  "shortcuts.help": "顯示快捷鍵",
  "shortcuts.nextRoom": "上／下一個房間",
  "shortcuts.nextUnread": "上／下一個有未讀的房間",
  "shortcuts.switcher": "快速切換房間",
  "shortcuts.title": "鍵盤快捷鍵",
  "switcher.empty": "沒有符合的房間",
  "switcher.placeholder": "輸入房名…",
  "switcher.title": "切換房間",
  "thread.close": "關閉 thread",
  "thread.notFound": "找不到這個 thread",
  "thread.placeholder": "在 thread 回覆…",
  "thread.replies": "{n} 則回覆",
  "thread.title": "Thread",
  "timeline.dismiss": "知道了",
  "timeline.empty": "打個招呼吧",
  "timeline.jumpLatest": "{count} 則新訊息",
  "timeline.jumped": "已跳到最新；較早的訊息往上捲動載入",
  "timeline.label": "{room} 的訊息",
  "timeline.loadingOlder": "正在載入較早的訊息…",
  "timeline.newMessages": "新訊息",
  "timeline.olderFailed": "無法載入較早的訊息",
  "timeline.pending.discard": "刪除",
  "timeline.pending.failed": "送出失敗：{reason}",
  "timeline.pending.retry": "重試",
  "timeline.pending.sending": "送出中…",
  "timeline.pending.unknown": "重新送出中…",
  "timeline.start.created": "建立於 {date}",
  "timeline.start.title": "這是 # {room} 的開頭",
  "timeline.today": "今天",
  "timeline.unknownSender": "已離開的成員",
  "timeline.yesterday": "昨天",
  "timeline.you": "你",
  "trace.fullUnavailable": "沒有完整紀錄",
  "trace.label": "工作紀錄",
  "trace.loadFull": "載入完整紀錄",
  "typing.many": "{n} 人正在輸入…",
  "typing.one": "{a} 正在輸入…",
  "typing.two": "{a}、{b} 正在輸入…",
  "user.menu.language": "語言",
  "user.menu.settings": "設定",
  "user.menu.theme": "主題",
  "user.menu.themeDark": "深色",
  "user.menu.themeLight": "淺色",
  "user.menu.themeSystem": "跟隨系統",
} as const;
