import type { AttentionItem, ImpactItem, WorkItem } from './model';

export const projectFixture = {
  id: 'prj_01HBOARDFIXTURE',
  name: 'HAI Taskboard P0-A',
  cursor: '7:42',
};

export const workItemsFixture: WorkItem[] = [
  {
    id: 'wi_01HDRAFT',
    title: 'Clarify offline import boundary',
    owner: 'operator',
    phase: 'Draft',
    version: 3,
    conditions: [],
    blockerCount: 0,
    acCoverage: [0, 2],
    run: 'No run',
    evidence: 'NotRun',
    pendingAction: 'Accept AC revision',
  },
  {
    id: 'wi_01HREADY',
    title: 'Implement Board-first fixture shell',
    owner: 'operator',
    phase: 'Ready',
    version: 8,
    conditions: [],
    blockerCount: 0,
    acCoverage: [2, 2],
    run: 'No run',
    evidence: '2/2 applicable',
    pendingAction: 'Dispatch fake run',
  },
  {
    id: 'wi_01HDEV',
    title: 'Bounded fake adapter scenario',
    owner: 'operator',
    phase: 'Developing',
    version: 5,
    conditions: [],
    blockerCount: 0,
    acCoverage: [1, 2],
    run: 'Running · heartbeat 12:04Z',
    evidence: '1/2 applicable',
    pendingAction: 'Inspect candidate',
  },
  {
    id: 'wi_01HREVIEW',
    title: 'Review current candidate subject',
    owner: 'reviewer-1',
    phase: 'Review',
    version: 12,
    conditions: [],
    blockerCount: 0,
    acCoverage: [3, 3],
    run: 'Succeeded · candidate present',
    evidence: '3/3 applicable',
    pendingAction: 'Publish independent review',
  },
  {
    id: 'wi_01HQA',
    title: 'Verify completion recipe',
    owner: 'verifier-1',
    phase: 'QA',
    version: 9,
    conditions: [],
    blockerCount: 0,
    acCoverage: [3, 3],
    run: 'Succeeded',
    evidence: '2/3 passed · 1 NotRun',
    pendingAction: 'Run required verification',
  },
  {
    id: 'wi_01HDONE',
    title: 'Archive accepted evidence',
    owner: 'operator',
    phase: 'Done',
    version: 18,
    conditions: ['DoneStale'],
    blockerCount: 0,
    acCoverage: [2, 2],
    run: 'Succeeded',
    evidence: 'Historical evidence stale',
    pendingAction: 'Inspect cause path',
    revision: 'sha256:7f1c…9ca0',
    causePath: 'AC revision → completion subject',
  },
  {
    id: 'wi_01HBLOCK',
    title: 'Reconcile uncertain fake observation',
    owner: 'operator',
    phase: 'Developing',
    version: 14,
    conditions: ['Blocked', 'OutcomeUnknown', 'CancelRequested'],
    blockerCount: 1,
    acCoverage: [1, 2],
    run: 'OutcomeUnknown · stop unconfirmed',
    evidence: 'Unknown',
    pendingAction: 'Reconcile before retry',
  },
];

export const attentionFixture: AttentionItem[] = [
  {
    id: 'attn_disconnected',
    kind: 'Disconnected',
    title: 'Projection stream disconnected',
    cause: 'Last known cursor 7:42. Cached projection remains readable.',
    risk: 'Revalidate risky actions',
    action: 'Reconnect / resync',
  },
  {
    id: 'attn_conflict',
    kind: 'Version conflict',
    title: 'Board move rejected by current version',
    cause:
      'wi_01HREADY changed from version 8 to 9 on the authoritative server.',
    risk: 'Blocks transition',
    action: 'Refresh and review',
  },
  {
    id: 'attn_stale',
    kind: 'Stale input',
    title: 'Evidence no longer applies',
    cause:
      'AC revision sha256:7f1c…9ca0 changed through AC → completion subject.',
    risk: 'Blocks Done',
    action: 'Inspect impact',
  },
  {
    id: 'attn_unknown',
    kind: 'OutcomeUnknown',
    title: 'Side effect cannot be confirmed',
    cause:
      'Run run_01HUNKNOWN lost contact; automatic retry, publish, and Done are unavailable.',
    risk: 'Blocks publish',
    action: 'Open reconciliation',
  },
  {
    id: 'attn_cancel',
    kind: 'CancelRequested',
    title: 'Cancellation requested; stop unconfirmed',
    cause:
      'The current phase remains Developing until a verified stop observation arrives.',
    risk: 'Blocks dispatch',
    action: 'Confirm stop or reconcile',
  },
  {
    id: 'attn_done_stale',
    kind: 'Done · Stale',
    title: 'Historical completion is ineffective',
    cause:
      'CompletionRecord is retained, but the accepted baseline has changed.',
    risk: 'Blocks Done',
    action: 'Inspect cause path',
  },
];

export const impactFixture: ImpactItem[] = [
  {
    id: 'wi_01HREADY',
    applicability: 'Stale',
    causePath: 'spec:board-shell → AC:keyboard-parity',
    reuse: 'Rebuild',
  },
  {
    id: 'wi_01HQA',
    applicability: 'Unknown',
    causePath: 'AC:keyboard-parity → evidence:axe',
    reuse: 'Unknown',
  },
  {
    id: 'wi_01HREVIEW',
    applicability: 'Fresh',
    causePath: 'No changed dependency path',
    reuse: 'Reusable',
  },
];
