#!/usr/bin/env node
/**
 * kithctl — local hash + seed-SQL helper. Stays off Cloudflare.
 *
 * From products/kith:
 *   node cmd/kithctl.mjs hash-password
 *     Read one password line from stdin; write
 *     pbkdf2-sha256$100000$<salt_b64url>$<dk_b64url> plus newline.
 *     WebCrypto PBKDF2-SHA-256 only (salt 16 bytes, dk 32 bytes).
 *     Does not log the password.
 *
 *   node cmd/kithctl.mjs bootstrap \
 *     --operator-id ID --operator-handle HANDLE --operator-hash HASH \
 *     --room-id ID --room-slug SLUG --room-name NAME \
 *     --second-id ID --second-handle HANDLE --second-hash HASH
 *     Write INSERT SQL to stdout: operator human (is_operator = 1),
 *     second human (is_operator = 0, not joined), one room, owner
 *     membership for the operator only.
 */

const ITERATIONS = 100000;
const SALT_BYTES = 16;
const DK_BITS = 256;

const BOOTSTRAP_FLAGS = [
  "operator-id",
  "operator-handle",
  "operator-hash",
  "room-id",
  "room-slug",
  "room-name",
  "second-id",
  "second-handle",
  "second-hash",
];

function usage() {
  process.stderr.write(
    "Usage:\n" +
      "  node cmd/kithctl.mjs hash-password\n" +
      "  node cmd/kithctl.mjs bootstrap --operator-id ID --operator-handle HANDLE --operator-hash HASH --room-id ID --room-slug SLUG --room-name NAME --second-id ID --second-handle HANDLE --second-hash HASH\n",
  );
}

function b64url(bytes) {
  let bin = "";
  for (const b of bytes) bin += String.fromCharCode(b);
  return btoa(bin).replaceAll("+", "-").replaceAll("/", "_").replaceAll("=", "");
}

function sqlString(value) {
  return `'${String(value).replaceAll("'", "''")}'`;
}

async function readPasswordLine() {
  const chunks = [];
  for await (const chunk of process.stdin) {
    chunks.push(typeof chunk === "string" ? Buffer.from(chunk) : chunk);
  }
  const text = Buffer.concat(chunks).toString("utf8");
  const nl = text.search(/\r|\n/);
  return nl === -1 ? text : text.slice(0, nl);
}

async function hashPassword() {
  const password = await readPasswordLine();
  if (password.length === 0) {
    process.stderr.write("hash-password: empty password line\n");
    process.exitCode = 1;
    return;
  }
  const salt = crypto.getRandomValues(new Uint8Array(SALT_BYTES));
  const material = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(password),
    "PBKDF2",
    false,
    ["deriveBits"],
  );
  const bits = await crypto.subtle.deriveBits(
    {
      name: "PBKDF2",
      hash: "SHA-256",
      salt,
      iterations: ITERATIONS,
    },
    material,
    DK_BITS,
  );
  const dk = new Uint8Array(bits);
  process.stdout.write(`pbkdf2-sha256$${ITERATIONS}$${b64url(salt)}$${b64url(dk)}\n`);
}

function parseFlags(argv) {
  const flags = {};
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (!arg.startsWith("--")) {
      throw new Error(`unexpected argument: ${arg}`);
    }
    const body = arg.slice(2);
    const eq = body.indexOf("=");
    let key;
    let value;
    if (eq >= 0) {
      key = body.slice(0, eq);
      value = body.slice(eq + 1);
    } else {
      key = body;
      const next = argv[i + 1];
      if (next === undefined || next.startsWith("--")) {
        throw new Error(`missing value for --${key}`);
      }
      value = next;
      i++;
    }
    flags[key] = value;
  }
  return flags;
}

function renderBootstrapSql(flags) {
  const createdAt = sqlString(new Date().toISOString());
  const operatorId = sqlString(flags["operator-id"]);
  const operatorHandle = sqlString(flags["operator-handle"]);
  const operatorHash = sqlString(flags["operator-hash"]);
  const roomId = sqlString(flags["room-id"]);
  const roomSlug = sqlString(flags["room-slug"]);
  const roomName = sqlString(flags["room-name"]);
  const secondId = sqlString(flags["second-id"]);
  const secondHandle = sqlString(flags["second-handle"]);
  const secondHash = sqlString(flags["second-hash"]);

  return [
    "-- kith bootstrap seed (generated by cmd/kithctl.mjs bootstrap).",
    "-- Inserts one operator human, one second human, one room, and owner membership.",
    "-- Second human is NOT auto-joined; owner later POST /api/rooms/:id/members.",
    "-- Do not commit real password hashes, passwords, or API keys.",
    "",
    "INSERT INTO members (id, kind, handle, display_name, password_hash, capabilities_json, quota_class, is_operator, created_at)",
    `VALUES (${operatorId}, 'human', ${operatorHandle}, ${operatorHandle}, ${operatorHash}, '[]', 'api_key', 1, ${createdAt}); -- is_operator = 1`,
    "",
    "INSERT INTO members (id, kind, handle, display_name, password_hash, capabilities_json, quota_class, is_operator, created_at)",
    `VALUES (${secondId}, 'human', ${secondHandle}, ${secondHandle}, ${secondHash}, '[]', 'api_key', 0, ${createdAt}); -- is_operator = 0`,
    "",
    "INSERT INTO rooms (id, slug, name, created_by, created_at)",
    `VALUES (${roomId}, ${roomSlug}, ${roomName}, ${operatorId}, ${createdAt});`,
    "",
    "INSERT INTO room_members (room_id, member_id, role, attention_mode, keywords_json, cooldown_ms, debounce_ms, classifier, policy_epoch)",
    `VALUES (${roomId}, ${operatorId}, 'owner', 'mention', '[]', 15000, 2000, 'heuristic', 1);`,
    "",
  ].join("\n");
}

function bootstrap(argv) {
  let flags;
  try {
    flags = parseFlags(argv);
  } catch (err) {
    process.stderr.write(`${err instanceof Error ? err.message : String(err)}\n`);
    usage();
    process.exitCode = 1;
    return;
  }
  const missing = BOOTSTRAP_FLAGS.filter((name) => !flags[name]);
  const unknown = Object.keys(flags).filter((name) => !BOOTSTRAP_FLAGS.includes(name));
  if (missing.length > 0 || unknown.length > 0) {
    if (missing.length > 0) {
      process.stderr.write(`missing flags: ${missing.map((n) => `--${n}`).join(", ")}\n`);
    }
    if (unknown.length > 0) {
      process.stderr.write(`unknown flags: ${unknown.map((n) => `--${n}`).join(", ")}\n`);
    }
    usage();
    process.exitCode = 1;
    return;
  }
  process.stdout.write(renderBootstrapSql(flags));
}

async function main() {
  const [command, ...rest] = process.argv.slice(2);
  if (command === "hash-password") {
    await hashPassword();
    return;
  }
  if (command === "bootstrap") {
    bootstrap(rest);
    return;
  }
  usage();
  process.exitCode = 1;
}

main().catch((err) => {
  process.stderr.write(`${err instanceof Error ? err.message : String(err)}\n`);
  process.exitCode = 1;
});
