use std::{
    collections::{BTreeMap, BTreeSet},
    fmt::Write as _,
    fs,
    path::{Path, PathBuf},
    process,
    time::{SystemTime, UNIX_EPOCH},
};

use flowshot_core::contracts::{
    AppErrorCode, AppErrorDto, BuildInfoDto, EmptyRequest, command_descriptors,
};
use serde_json::json;
use sha2::{Digest, Sha256};
use ts_rs::{Config, TS};

const GENERATOR_VERSION: &str = "1.0.0";
const GENERATED_RELATIVE: &str = "src/generated/contracts";
const SOURCE_FILES: [&str; 4] = [
    "crates/core/src/contracts/mod.rs",
    "crates/core/src/contracts/common.rs",
    "crates/core/src/contracts/error.rs",
    "crates/core/src/contracts/build_info.rs",
];

pub fn run(mut args: impl Iterator<Item = String>) -> Result<String, String> {
    let mut check = false;
    let mut check_determinism = false;
    let mut out_dir = None;

    while let Some(argument) = args.next() {
        match argument.as_str() {
            "--check" => check = true,
            "--check-determinism" => check_determinism = true,
            "--out-dir" => {
                let value = args
                    .next()
                    .ok_or_else(|| "--out-dir requires a path".to_owned())?;
                out_dir = Some(PathBuf::from(value));
            }
            unknown => return Err(format!("unknown contracts option `{unknown}`")),
        }
    }

    let root = repository_root();
    if check_determinism {
        verify_determinism(&root)?;
    }

    let destination = out_dir.unwrap_or_else(|| root.join(GENERATED_RELATIVE));
    if check {
        check_destination(&root, &destination)?;
        Ok(format!(
            "contracts are current in {}",
            display_path(&root, &destination)
        ))
    } else {
        write_contracts(&destination)?;
        Ok(format!(
            "generated contracts in {}",
            display_path(&root, &destination)
        ))
    }
}

fn repository_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

fn display_path(root: &Path, path: &Path) -> String {
    path.strip_prefix(root)
        .unwrap_or(path)
        .to_string_lossy()
        .replace('\\', "/")
}

fn generated_files() -> Result<BTreeMap<&'static str, String>, String> {
    let config = Config::default();
    let commands = command_descriptors(&config);
    let command = commands
        .first()
        .ok_or_else(|| "command manifest is empty".to_owned())?;

    let header = format!(
        "// @generated by flowshot-xtask contracts v{GENERATOR_VERSION}.\n\
         // Rust sources are authoritative. Do not edit this file.\n\n"
    );

    let declarations = [
        AppErrorCode::decl(&config),
        AppErrorDto::decl(&config),
        EmptyRequest::decl(&config),
        BuildInfoDto::decl(&config),
    ]
    .map(|declaration| format!("export {declaration}\n"))
    .join("\n");
    let types = format!("{header}{declarations}");

    let commands_ts = format!(
        "{header}import {{ invoke }} from \"@tauri-apps/api/core\";\n\
         import type {{ AppErrorDto, BuildInfoDto, EmptyRequest }} from \"./types\";\n\n\
         export const commandNames = {{\n\
         \x20 getBuildInfo: \"{}\",\n\
         }} as const;\n\n\
         export type CommandError = AppErrorDto;\n\n\
         export async function getBuildInfo(\n\
         \x20 request: EmptyRequest = {{}},\n\
         ): Promise<BuildInfoDto> {{\n\
         \x20 return invoke<BuildInfoDto>(commandNames.getBuildInfo, {{ request }});\n\
         }}\n",
        command.name
    );

    let index = format!(
        "{header}export * from \"./commands\";\n\
         export type * from \"./types\";\n"
    );

    let manifest = serde_json::to_string_pretty(&json!({
        "schemaVersion": 1,
        "generatorVersion": GENERATOR_VERSION,
        "commands": commands,
    }))
    .map_err(|error| format!("failed to serialize command manifest: {error}"))?
        + "\n";

    Ok(BTreeMap::from([
        ("commands.ts", commands_ts),
        ("index.ts", index),
        ("manifest.json", manifest),
        ("types.ts", types),
    ]))
}

fn write_contracts(destination: &Path) -> Result<(), String> {
    fs::create_dir_all(destination).map_err(|error| {
        format!(
            "failed to create contract directory {}: {error}",
            destination.display()
        )
    })?;

    for (name, content) in generated_files()? {
        let path = destination.join(name);
        fs::write(&path, content)
            .map_err(|error| format!("failed to write {}: {error}", path.display()))?;
    }
    Ok(())
}

fn check_destination(root: &Path, destination: &Path) -> Result<(), String> {
    let expected = generated_files()?;
    let expected_names = expected.keys().copied().collect::<BTreeSet<_>>();
    let mut drift = Vec::new();

    for (name, content) in expected {
        let path = destination.join(name);
        match fs::read_to_string(&path) {
            Ok(actual) if actual == content => {}
            Ok(_) => drift.push(format!("{name} differs")),
            Err(_) => drift.push(format!("{name} is missing")),
        }
    }

    if let Ok(entries) = fs::read_dir(destination) {
        for entry in entries.flatten() {
            let name = entry.file_name();
            let name = name.to_string_lossy();
            if entry.path().is_file() && !expected_names.contains(name.as_ref()) {
                drift.push(format!("{name} is unexpected"));
            }
        }
    }

    check_lock(root, &mut drift)?;

    if drift.is_empty() {
        Ok(())
    } else {
        drift.sort();
        Err(format!("contract drift:\n- {}", drift.join("\n- ")))
    }
}

fn check_lock(root: &Path, drift: &mut Vec<String>) -> Result<(), String> {
    let lock_path = root.join("contracts/locks/N00.json");
    let bytes = fs::read(&lock_path)
        .map_err(|error| format!("failed to read {}: {error}", lock_path.display()))?;
    let lock: serde_json::Value = serde_json::from_slice(&bytes)
        .map_err(|error| format!("failed to parse {}: {error}", lock_path.display()))?;

    if lock["status"] != "frozen" {
        drift.push("contracts/locks/N00.json is not frozen".into());
    }
    if lock["generator_version"] != GENERATOR_VERSION {
        drift.push("contracts/locks/N00.json has a stale generator_version".into());
    }
    let digest = source_digest(root)?;
    if lock["source_sha256"] != digest {
        drift.push("contracts/locks/N00.json has a stale source_sha256".into());
    }
    Ok(())
}

fn source_digest(root: &Path) -> Result<String, String> {
    let mut hasher = Sha256::new();
    for relative in SOURCE_FILES {
        let path = root.join(relative);
        let bytes =
            fs::read(&path).map_err(|error| format!("failed to read {relative}: {error}"))?;
        hasher.update(relative.as_bytes());
        hasher.update([0]);
        hasher.update(bytes);
        hasher.update([0]);
    }
    let mut encoded = String::with_capacity(64);
    for byte in hasher.finalize() {
        write!(&mut encoded, "{byte:02x}")
            .map_err(|error| format!("failed to encode source digest: {error}"))?;
    }
    Ok(encoded)
}

fn verify_determinism(root: &Path) -> Result<(), String> {
    let first = temporary_directory("first");
    let second = temporary_directory("second");

    let result = (|| {
        write_contracts(&first)?;
        write_contracts(&second)?;
        compare_directories(&first, &second)
    })();

    let _ = fs::remove_dir_all(&first);
    let _ = fs::remove_dir_all(&second);

    result.map_err(|error| format!("{error} (repository: {})", root.display()))
}

fn temporary_directory(label: &str) -> PathBuf {
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos();
    std::env::temp_dir().join(format!(
        "flowshot-contracts-{}-{label}-{nanos}",
        process::id()
    ))
}

fn compare_directories(first: &Path, second: &Path) -> Result<(), String> {
    let expected = generated_files()?;
    for name in expected.keys() {
        let first_bytes = fs::read(first.join(name))
            .map_err(|error| format!("failed to read first {name}: {error}"))?;
        let second_bytes = fs::read(second.join(name))
            .map_err(|error| format!("failed to read second {name}: {error}"))?;
        if first_bytes != second_bytes {
            return Err(format!("non-deterministic generated file: {name}"));
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn isolated_generations_are_byte_identical() {
        verify_determinism(&repository_root()).expect("generation should be deterministic");
    }

    #[test]
    fn drift_check_names_the_changed_file() {
        let destination = temporary_directory("drift");
        write_contracts(&destination).expect("fixture generation should succeed");
        fs::write(destination.join("types.ts"), "changed").expect("fixture should mutate");

        let mut drift = Vec::new();
        let expected = generated_files().expect("expected output should render");
        for (name, content) in expected {
            let actual = fs::read_to_string(destination.join(name)).expect("file should exist");
            if actual != content {
                drift.push(format!("{name} differs"));
            }
        }

        let _ = fs::remove_dir_all(&destination);
        assert_eq!(drift, ["types.ts differs"]);
    }

    #[test]
    fn generated_output_contains_no_absolute_repository_path() {
        let root = repository_root();
        let root_text = root.to_string_lossy();
        for content in generated_files()
            .expect("output should render")
            .into_values()
        {
            assert!(!content.contains(root_text.as_ref()));
        }
    }
}
