\set ON_ERROR_STOP on
CREATE EXTENSION jev CASCADE;
CREATE ROLE lab_reader LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE TABLE lab_sentinel (id integer PRIMARY KEY);
INSERT INTO lab_sentinel VALUES (1);
GRANT SELECT ON lab_sentinel TO lab_reader;
