// User-visible strings of web-back (zh-Hant). Key rule: docs/v2/waves/W0.md §4.6.
// W1 removes every engineering phrase (U-01, V2-AC-15): no API verbs, field keys, "origin" or "(string)".
export const copy = {
  "app.name": "CMS 作業台",
  "login.title": "登入 CMS 作業台",
  "nav.home": "首頁",
  "nav.views": "視圖",
  "nav.content": "內容",
  "view.album.composer": "相簿編排",
  "view.clinic.schedule": "當日行程",
  "view.projects.board": "看板",
  "view.album.composer.lead": "調整相片順序與封面。",
  "view.clinic.schedule.lead": "查看某一天的就診。",
  "view.projects.board.lead": "依狀態檢視與移動議題。",
  "role.admin": "管理員",
  "role.operator": "營運",
  "role.editor": "編輯",
  "role.member": "會員",
  "surface.forbidden.title": "沒有權限",
  "surface.forbidden.body": "這個帳號不能使用作業台。",
  "forbidden.title": "沒有權限",
  "forbidden.body": "你沒有檢視這個頁面的權限。如果需要，請聯絡管理員。",
  "notFound.title": "找不到頁面",
  "notFound.body": "這個頁面或項目不存在，可能已被移到回收。",
  "status.home": "回到首頁",
  "home.title": "作業台",
  "home.lead": "選擇要處理的內容或視圖。",
  "home.types": "內容",
  "home.views": "視圖",
  "home.noTypes": "沒有可作業的內容類型",
  "home.noTypesBody": "這個帳號目前沒有任何內容類型的作業權限。如果需要，請聯絡管理員。",
  "index.create": "新增{name}",
  "index.tab.all": "全部",
  "index.tab.draft": "草稿",
  "index.tab.published": "已發布",
  "index.tab.archived": "已封存",
  "index.sort.updatedDesc": "最近更新",
  "index.sort.updatedAsc": "最早更新",
  "index.sort.titleAsc": "標題 A→Z",
  "index.sort.titleDesc": "標題 Z→A",
  "index.sort.createdDesc": "最新建立",
  "index.col.title": "標題",
  "index.col.status": "狀態",
  "index.col.updated": "更新時間",
  "index.untitled": "（未命名）",
  "index.empty": "還沒有{name}",
  "index.emptyCreate": "建立第一筆後，它會出現在這裡。",
  "index.emptyReadOnly": "目前沒有可以檢視的項目。",
  "index.noMatch": "沒有符合的條目",
  "index.noMatchBody": "換個關鍵字或清除篩選再試一次。",
  "details.new": "新增{name}",
  "details.create": "建立",
  "details.created": "已建立",
  "details.saved": "已儲存",
  "details.publish": "發布",
  "details.publishChanges": "發布變更",
  "details.published": "已發布",
  "details.unpublish": "下架",
  "details.unpublished": "已下架，現在是草稿",
  "details.archive": "封存",
  "details.archived": "已封存",
  "details.restore": "還原為草稿",
  "details.restored": "已還原為草稿",
  "details.delete": "移到回收",
  "details.deleted": "已移到回收",
  "details.failed": "操作沒有完成，請再試一次。",
  "details.fixFields": "有欄位需要修正。",
  "details.publishBlocked": "發布前請先修正標示的欄位。",
  "details.readOnlyArchived": "已封存的項目不能編輯。還原為草稿後才能修改。",
  "details.readOnlyNoUpdate": "你可以檢視這個項目，但不能修改。",
  "details.stateChanged": "這個項目的狀態已被其他人改變，已重新載入。",
  "details.singletonExists": "這個類型只能有一筆，已經存在。",
  "details.referenced": "還有其他項目連結到它，不能移到回收。",
  "details.archiveTitle": "封存「{title}」？",
  "details.archiveBody": "封存後會從公開網站移除，也不能再編輯。之後可以還原為草稿。",
  "details.deleteTitle": "把「{title}」移到回收？",
  "details.deleteBody": "移到回收後，作業台與公開網站都不再顯示它。",
  "details.cancel": "取消",
  "card.publish": "發布",
  "card.publish.state": "狀態",
  "card.publish.lastPublished": "最後發布",
  "card.publish.never": "尚未發布",
  "card.relations": "關聯",
  "card.url": "網址",
  "card.url.slug": "網址代稱",
  "card.url.slugHelp": "建議只用小寫英文、數字與連字號，例如 coast-light-2026。",
  "card.url.notPublished": "發布後才能開啟公開網址。",
  "card.url.open": "在新分頁開啟公開頁面",
  "card.meta": "中繼資料",
  "card.meta.id": "識別碼",
  "card.meta.copy": "複製識別碼",
  "card.meta.copied": "已複製識別碼",
  "card.meta.version": "版本",
  "card.meta.updated": "最後更新",
  "slug.error.REQUIRED": "這個類型需要網址代稱。",
  "slug.error.SLUG_CONFLICT": "這個網址代稱已被使用，請換一個。",
  "slug.error.CANNOT_CLEAR": "已設定的網址代稱不能清空。",
  "conflict.title": "這個項目已被其他人修改",
  "conflict.body": "你的修改還沒有儲存。載入最新版本會捨棄你的修改；也可以先繼續編輯，把內容另外記下來。",
  "conflict.reload": "載入最新版本",
  "conflict.keep": "繼續編輯",
  "composer.album": "相簿",
  "composer.albumList": "所有相簿",
  "composer.empty": "這本相簿還沒有相片。",
  "composer.up": "上移",
  "composer.down": "下移",
  "composer.cover": "設為封面",
  "composer.edit": "編輯",
  "composer.reordered": "已更新順序",
  "composer.coverSet": "已設為封面",
  "composer.noMedia": "這張相片還沒有圖片",
  "composer.position": "第 {n} 張",
  "schedule.newVisit": "新增就診",
  "schedule.date": "日期",
  "schedule.empty": "這一天沒有就診。",
  "schedule.untitled": "未命名的就診",
  "board.issueList": "所有議題",
  "board.project": "專案",
  "board.lead": "在卡片上變更狀態，會立即儲存，但不會發布。",
  "board.statusLabel": "「{title}」的狀態",
  "board.moved": "已把「{title}」移到「{status}」",
  "board.untitled": "未命名的議題",
  "view.failed": "操作沒有完成，請再試一次。",
} as const;

export type CopyKey = keyof typeof copy;
