// User-visible strings of web-back (zh-Hant). Key rule: docs/v2/waves/W0.md §4.6.
// W0 keeps the v1 wording; W1 rewrites the engineering phrases (U-01).
export const copy = {
  "app.name": "CMS 作業台",
  "login.title": "登入 CMS 作業台",
  "nav.home": "首頁",
  "nav.views": "視圖",
  "nav.content": "內容",
  "view.album.composer": "相簿編排",
  "view.clinic.schedule": "當日行程",
  "view.projects.board": "看板",
  "forbidden.title": "沒有權限",
  "forbidden.body": "這個帳號不能進 Back office。",
  "home.title": "作業台",
  "home.lead": "以內容類型作業。沒有 Admin 治理選單。自訂視圖寫入仍走 entry API。",
  "home.allTypes": "全部類型",
  "list.create": "新建",
  "list.empty": "尚無內容。建立第一筆草稿。",
  "editor.newTitle": "新建",
  "editor.previewNote": "草稿預覽留在 Back（工作副本），不會開 Front origin。",
  "editor.slug": "slug",
  "editor.save": "儲存草稿",
  "editor.saved": "已儲存工作副本",
  "editor.stateUpdated": "內容狀態已更新：",
  "editor.publish": "發布",
  "editor.unpublish": "下架",
  "editor.archive": "封存",
  "editor.uploaded": "已上傳",
  "editor.error": "操作失敗",
  "editor.retry": "請檢查輸入或連線後重試。",
  "editor.conflict": "內容已被其他操作更新。本地輸入已保留；請先複製需要的內容，重新載入後再重試。",
  "editor.integerError": "請輸入有限整數，範圍為 -9007199254740991 至 9007199254740991。",
  "editor.saveFirst": "請先儲存變更，再發布、下架或封存。",
  "editor.unset": "未設定",
  "editor.yes": "是",
  "editor.no": "否",
  "composer.albumList": "相簿列表",
  "composer.album": "相簿",
  "composer.empty": "這本相簿還沒有相片。請從 photo 類型新增。",
  "composer.up": "上移",
  "composer.down": "下移",
  "composer.cover": "設為封面",
  "composer.edit": "編輯",
  "composer.reordered": "已更新 sortOrder",
  "composer.coverSet": "已設封面",
  "composer.noMedia": "這張相片沒有 media",
  "schedule.newVisit": "新就診",
  "schedule.date": "日期",
  "schedule.empty": "這一天沒有 visit。列表來自通用 entries，沒有診所專用行程 API。",
  "schedule.fallbackTitle": "Visit",
  "board.issueList": "Issue 列表",
  "board.project": "專案",
  "board.note": "挪卡只 PATCH issue.status，不會 publish。沒有看板寫入 API。",
  "board.statusLabel": "狀態",
  "board.moved": "已移動",
} as const;
