// @cms/ui — shadcn components, tokens and the Polaris-style patterns (01 §4.2, §6).
export { cn } from "./lib/utils";
export { fill, uiCopy, type UiCopyKey } from "./copy";

export * from "./components/ui/alert";
export * from "./components/ui/alert-dialog";
export * from "./components/ui/badge";
export * from "./components/ui/breadcrumb";
export * from "./components/ui/button";
export * from "./components/ui/calendar";
export * from "./components/ui/card";
export * from "./components/ui/checkbox";
export * from "./components/ui/dialog";
export * from "./components/ui/dropdown-menu";
export * from "./components/ui/input";
export * from "./components/ui/label";
export * from "./components/ui/popover";
export * from "./components/ui/progress";
export * from "./components/ui/radio-group";
export * from "./components/ui/select";
export * from "./components/ui/separator";
export * from "./components/ui/sheet";
export * from "./components/ui/skeleton";
export * from "./components/ui/switch";
export * from "./components/ui/table";
export * from "./components/ui/tabs";
export * from "./components/ui/textarea";

export { AppFrame, type AppFrameProps, type NavItem, type NavSection } from "./patterns/app-frame";
export { EmptyState, type EmptyStateProps } from "./patterns/empty-state";
export { PageHeader, type PageAction, type PageHeaderProps } from "./patterns/page-header";
export { DefaultSkeleton, ErrorState, QueryBoundary, type QueryBoundaryProps, type QueryLike } from "./patterns/query-boundary";
export { TitleSuffixContext, useDocumentTitle } from "./patterns/document-title";
export { ContextualSaveBar, type ContextualSaveBarProps } from "./patterns/contextual-save-bar";
export { IndexFilters, type FilterOption, type IndexFilter, type IndexFiltersProps } from "./patterns/index-filters";
export { IndexPagination, PAGE_SIZES, type IndexPaginationProps } from "./patterns/index-pagination";
export { IndexTable, type IndexColumn, type IndexTableProps } from "./patterns/index-table";
export { ResourceLayout } from "./patterns/resource-layout";
export { StatusBadge, type PublicationStateValue } from "./patterns/status-badge";
export { Toaster, toast } from "./patterns/toaster";
